//! `CairnMcpHandler` — MCP `ServerHandler` implementation.
//!
//! Wires the IDL-generated [`TOOLS`] constant into the `tools/list` response
//! and routes `tools/call` through [`dispatch_stub`] while real verb dispatch
//! is pending.

use std::sync::Arc;

use rmcp::{
    RoleServer, ServerHandler,
    model::{
        CallToolRequestParams, CallToolResult, Content, Implementation, ListToolsResult,
        PaginatedRequestParams, ServerCapabilities, ServerInfo, Tool, ToolsCapability,
    },
    service::RequestContext,
};

use crate::generated::TOOLS;

/// MCP server handler for the Cairn verb layer.
///
/// Implements [`rmcp::ServerHandler`]. P0 scaffold: `tools/list` is served
/// from the IDL-generated [`TOOLS`] constant; `tools/call` returns a
/// [`dispatch_stub`] error until real verb dispatch lands in a follow-up PR.
#[derive(Debug, Default)]
pub struct CairnMcpHandler;

impl CairnMcpHandler {
    /// Create a new handler instance.
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl ServerHandler for CairnMcpHandler {
    /// Return server identity and advertise tool capability.
    fn get_info(&self) -> ServerInfo {
        let mut caps = ServerCapabilities::default();
        caps.tools = Some(ToolsCapability { list_changed: None });
        let mut info = ServerInfo::default();
        info.capabilities = caps;
        info.server_info = Implementation::new("cairn", env!("CARGO_PKG_VERSION"));
        info
    }

    /// Return all Cairn verbs as MCP tools.
    ///
    /// Converts each [`crate::generated::ToolDecl`] entry in [`TOOLS`] into
    /// an rmcp [`Tool`], parsing the embedded JSON-schema bytes with
    /// `serde_json`.
    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListToolsResult, rmcp::ErrorData>> + Send + '_
    {
        let tools: Vec<Tool> = TOOLS
            .iter()
            .map(|decl| {
                // `input_schema` is `&'static [u8]` containing a valid JSON object.
                // Failure here means IDL-generated bytes are corrupt — fall back to
                // an empty schema rather than panicking in a library.
                let schema_value: serde_json::Value = serde_json::from_slice(decl.input_schema)
                    .unwrap_or_else(|_| serde_json::json!({"type": "object", "properties": {}}));
                let schema_obj = match schema_value {
                    serde_json::Value::Object(m) => m,
                    _ => serde_json::Map::new(),
                };
                Tool::new(decl.name, decl.description, Arc::new(schema_obj))
            })
            .collect();

        std::future::ready(Ok(ListToolsResult::with_all_items(tools)))
    }

    /// Dispatch a tool call.
    ///
    /// Validates that the requested verb exists in [`TOOLS`], then delegates
    /// to [`dispatch_stub`]. Real verb dispatch lands in a follow-up PR.
    fn call_tool(
        &self,
        request: CallToolRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<CallToolResult, rmcp::ErrorData>> + Send + '_
    {
        let name = request.name.clone();
        let known = TOOLS.iter().any(|d| d.name == name.as_ref());
        let result = if known {
            dispatch_stub(&name)
        } else {
            CallToolResult::error(vec![Content::text(format!(
                "cairn: unknown verb '{name}'. Available verbs: {}",
                TOOLS.iter().map(|d| d.name).collect::<Vec<_>>().join(", ")
            ))])
        };
        std::future::ready(Ok(result))
    }
}

/// Stub dispatcher returned while real verb wiring is pending.
///
/// Returns a [`CallToolResult`] with `is_error = true` and a message
/// explaining that the verb is not yet wired. This function is `pub` so the
/// parity test in Task 8 can call it directly.
#[must_use]
pub fn dispatch_stub(verb: &str) -> CallToolResult {
    CallToolResult::error(vec![Content::text(format!(
        "cairn {verb}: not yet implemented in this P0 scaffold. \
         Verb dispatch lands in a follow-up PR; no memory operation was performed."
    ))])
}
