//! Job persistence contract for `WorkflowOrchestrator` implementations.
//!
//! Brief §10 (v0.1 row): the default `tokio` orchestrator is backed by a
//! durable `SQLite` job table providing **crash-safe resume, exponential
//! retry, single-writer queue per key, step-level idempotency via
//! `operation_id`**. This trait names that persistence surface so the
//! tokio scheduler can be tested against any backend that satisfies it
//! (in-memory for unit tests, `SQLite` for production), and so a future
//! Temporal adapter ignores it entirely (Temporal owns its own state
//! machine).
//!
//! Adapter rule (`CLAUDE.md` §6.1): no `cairn-core` -> adapter dep, so
//! the types below are pure-data — opaque payload bytes, integer epoch
//! milliseconds, newtyped IDs. Backend errors are surfaced through
//! [`JobStoreError::Backend`].

pub mod failure_class;
pub use failure_class::FailureClass;

use crate::domain::Rfc3339Timestamp;

/// Stable identifier for a job row. ULID (or any string) chosen by the
/// caller of [`JobStore::enqueue`]. Identity is immutable on disk
/// (enforced by trigger in migration 0020).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct JobId(pub String);

impl JobId {
    /// Wrap a raw string id.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for JobId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Workflow discriminator — the worker name a handler registers under
/// (e.g. `"dream.light"`, `"expire.tier"`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct JobKind(pub String);

impl JobKind {
    /// Wrap a raw kind string.
    #[must_use]
    pub fn new(kind: impl Into<String>) -> Self {
        Self(kind.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for JobKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Opaque worker-supplied bytes. The `JobStore` does not interpret them.
/// Workflows are responsible for their own serialization (typically
/// `serde_json` or `bincode`).
pub type JobPayload = Vec<u8>;

/// Token identifying a successful lease. The scheduler must present the
/// same token for [`JobStore::heartbeat`], [`JobStore::complete`], and
/// [`JobStore::fail`]; an expired or stolen lease causes those calls to
/// fail with [`JobStoreError::LeaseLost`].
///
/// `nonce` is the stable CAS key — it stays constant across heartbeats
/// so a worker that successfully heartbeats can still complete the job.
/// `expires_at_ms` is informational only (it advances on every
/// heartbeat) and not used by the store for authentication.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeaseToken {
    /// Stable owner identity for the leasing scheduler (e.g.
    /// `"<incarnation_id>:<worker_id>"`).
    pub owner: String,
    /// Per-lease nonce (typically ULID). Generated by the store on
    /// `lease`; preserved across heartbeats; cleared by the reaper when
    /// the lease expires.
    pub nonce: String,
    /// Wall-clock at which the lease becomes eligible for reaping. Epoch
    /// milliseconds. Advances on each heartbeat.
    pub expires_at_ms: i64,
}

/// Lifecycle states. Mirrors the SQL CHECK in migration 0020.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum JobState {
    /// Eligible for lease; `next_run_at` may be in the future.
    Queued,
    /// Held by a worker; `lease_owner` + `lease_expires_at` are set.
    Leased,
    /// Terminal success.
    Done,
    /// Terminal failure (max attempts exhausted or workflow surfaced a
    /// non-retryable error).
    Failed,
}

/// Backoff schedule applied when a workflow surfaces a retryable failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RetryPolicy {
    /// Maximum number of execution attempts (post-start, counted on
    /// first heartbeat / fail / complete). Once `attempts` reaches this
    /// value the row transitions to [`JobState::Failed`].
    ///
    /// **Not** a cap on raw lease deliveries: a worker that crashes
    /// before its first heartbeat does not consume an attempt. Stores
    /// may apply a separate, larger ceiling on deliveries to bound
    /// pre-start crash loops, but that ceiling is implementation-defined
    /// and not part of this contract.
    pub max_attempts: u32,
    /// Base delay before the first retry, milliseconds.
    pub base_backoff_ms: u32,
    /// Multiplier applied per attempt. `delay = base * multiplier^(attempt-1)`,
    /// capped by `max_backoff_ms`.
    pub backoff_multiplier: u32,
    /// Upper bound on backoff between retries, milliseconds.
    pub max_backoff_ms: u32,
}

impl RetryPolicy {
    /// P0 default: 5 attempts, 1s base, ×2 per try, capped at 60s.
    pub const DEFAULT: Self = Self {
        max_attempts: 5,
        base_backoff_ms: 1_000,
        backoff_multiplier: 2,
        max_backoff_ms: 60_000,
    };

    /// Compute the next-run delay for a given attempt count (1-based).
    /// Pure function — exposed so the scheduler and tests share one
    /// definition.
    #[must_use]
    pub const fn delay_for_attempt(self, attempt: u32) -> u32 {
        if attempt == 0 {
            return 0;
        }
        // Saturating-multiply to keep this `const`.
        let mut delay = self.base_backoff_ms;
        let mut i = 1;
        while i < attempt {
            delay = delay.saturating_mul(self.backoff_multiplier);
            if delay >= self.max_backoff_ms {
                return self.max_backoff_ms;
            }
            i += 1;
        }
        delay
    }
}

/// Insertion request to [`JobStore::enqueue`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnqueueRequest {
    /// Caller-chosen ULID. Must be unique across all jobs.
    pub job_id: JobId,
    /// Workflow discriminator.
    pub kind: JobKind,
    /// Opaque payload bytes; `JobStore` stores them verbatim.
    pub payload: JobPayload,
    /// Optional single-writer queue identifier. Many jobs may share a
    /// `queue_key` and be persisted as `Queued`; the store guarantees
    /// at most one of them is `Leased` at a time, so they execute in
    /// FIFO order. Enforced by `workflow_jobs_queue_key_leased_uniq`
    /// (partial-unique index over `state = 'leased'`) plus a
    /// queue-key-aware `lease` predicate that skips queued rows whose
    /// key is currently leased.
    pub queue_key: Option<String>,
    /// Optional step-level idempotency key (e.g. WAL `operation_id`).
    /// Combined with `kind` it forms a unique constraint that lets the
    /// scheduler call `enqueue` from a retry-prone path.
    pub dedupe_key: Option<String>,
    /// Earliest time the job becomes lease-eligible. Epoch milliseconds.
    pub not_before_ms: i64,
    /// Retry policy applied if [`JobStore::fail`] requests a retry.
    pub retry: RetryPolicy,
}

/// One leased job handed to a worker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeasedJob {
    /// The job identifier.
    pub job_id: JobId,
    /// Workflow kind.
    pub kind: JobKind,
    /// Opaque payload bytes.
    pub payload: JobPayload,
    /// Number of attempts including the current one (≥1 once leased).
    pub attempts: u32,
    /// Retry policy persisted with the job.
    pub retry: RetryPolicy,
    /// Active lease token; the scheduler must present this on
    /// heartbeat / complete / fail.
    pub lease: LeaseToken,
    /// Class of the most recent failure, if any. `None` for first
    /// attempts and successfully completed retries. Set by the store
    /// when a previously-failed row is re-leased.
    pub failure_class: Option<FailureClass>,
}

/// Disposition for [`JobStore::fail`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FailDisposition {
    /// Bump `attempts`, schedule per `RetryPolicy`. If the new attempts
    /// would exceed `max_attempts`, the row terminates as `Failed`.
    Retry,
    /// Force terminal `Failed` regardless of remaining attempts.
    Permanent,
}

/// Errors raised by [`JobStore`] implementations.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum JobStoreError {
    /// Caller's lease no longer matches the row (expired / reaped /
    /// stolen). The worker should drop its result and exit cleanly.
    #[error("lease lost for job {job_id}")]
    LeaseLost {
        /// Job whose lease no longer matched.
        job_id: JobId,
    },
    /// `enqueue` rejected because `(kind, dedupe_key)` already exists.
    #[error("duplicate dedupe_key {dedupe_key:?} for kind {kind}")]
    DuplicateDedupeKey {
        /// Workflow kind.
        kind: JobKind,
        /// The dedupe key that conflicted.
        dedupe_key: String,
    },
    /// A lease/heartbeat deadline argument was non-positive or
    /// non-future relative to the supplied `now_ms`. The store
    /// refused to mutate; the caller is buggy (clock skew, bad
    /// arithmetic, misconfigured duration). Distinct from
    /// [`Self::LeaseLost`] so a scheduler can tell its own bad input
    /// from a stolen/expired lease.
    #[error("invalid lease deadline: {reason}")]
    InvalidLeaseDeadline {
        /// Human-readable reason.
        reason: String,
    },
    /// Backend-specific error (`SQLite` I/O, lock contention, etc.).
    #[error("job store backend: {0}")]
    Backend(String),
}

/// Persistence contract for the `tokio` workflow orchestrator's job table.
///
/// Implementors must be `Send + Sync` and safe to call from multiple
/// concurrent worker tasks. The `lease` operation must be atomic: at most
/// one caller observes `Some(_)` for any given queued row.
///
/// **Clock authority.** Every method that takes `now_ms` treats it as
/// the authoritative wall-clock at the call site. The store does not
/// derive its own time — callers (typically a single scheduler in
/// `cairn-workflows`) must supply a coordinated clock. A multi-process
/// deployment that backs onto the same `SQLite` file is responsible for
/// ensuring its scheduler instances share a monotonic clock; otherwise
/// skew can cause spurious `LeaseLost` or premature reaping. P0
/// scope (single binary, single scheduler) sidesteps this by definition.
///
/// **Delivery semantics.** This contract is **at-least-once**. The
/// scheduler may hand the same `(job_id, attempts)` to a worker more
/// than once if the worker crashes before its first heartbeat (the
/// signal that user code actually started). A pre-heartbeat crash
/// does not consume retry budget; a second worker can receive the
/// same payload with the same `attempts` value. **Callers that
/// perform externally-visible side effects before heartbeating must
/// guard against replay** — typically by setting `dedupe_key` to a
/// stable workflow-step `operation_id` so duplicate enqueues
/// short-circuit, and by making each step's side effects idempotent
/// against that key. This is the brief §10 v0.1 "step-level
/// idempotency via `operation_id`" contract: exactly-once delivery
/// is a workflow-author concern, not a store-level guarantee. The
/// store does bound replay (poison cap on `delivery_count`) so
/// pathological pre-heartbeat crash loops can't run forever.
#[async_trait::async_trait]
pub trait JobStore: Send + Sync {
    /// Insert a new job. Idempotent on `(kind, dedupe_key)` when
    /// `dedupe_key` is `Some` — duplicates surface as
    /// [`JobStoreError::DuplicateDedupeKey`].
    ///
    /// # Errors
    ///
    /// Returns [`JobStoreError::DuplicateDedupeKey`] when `(kind,
    /// dedupe_key)` collides with an existing non-failed row, or
    /// [`JobStoreError::Backend`] for backend failures. `queue_key`
    /// never rejects at enqueue time — many queued rows may share a
    /// key and serialize at lease time.
    async fn enqueue(&self, req: EnqueueRequest) -> Result<(), JobStoreError>;

    /// Atomically lease the next eligible job. Returns `Ok(None)` when no
    /// queued row has `next_run_at <= now_ms`. The lease expires at
    /// `now_ms + lease_duration_ms`; the scheduler must heartbeat or
    /// finish before then.
    ///
    /// # Errors
    ///
    /// Returns [`JobStoreError::Backend`] for backend failures.
    async fn lease(
        &self,
        owner: &str,
        now_ms: i64,
        lease_duration_ms: i64,
    ) -> Result<Option<LeasedJob>, JobStoreError>;

    /// Extend the lease deadline of a currently-held job. `now_ms` is
    /// the caller's wall-clock; the store rejects the call (with
    /// [`JobStoreError::LeaseLost`]) when the persisted
    /// `lease_expires_at <= now_ms`, even if the reaper has not yet run
    /// — so a worker that wakes up after its deadline cannot extend or
    /// finish its job.
    ///
    /// # Errors
    ///
    /// [`JobStoreError::LeaseLost`] if the row no longer matches the
    /// presented lease (reaped, completed, expired, or owned by
    /// someone else).
    async fn heartbeat(
        &self,
        job_id: &JobId,
        lease: &LeaseToken,
        now_ms: i64,
        new_expires_at_ms: i64,
    ) -> Result<(), JobStoreError>;

    /// Mark the job as terminally `Done`. `now_ms` is checked against
    /// the persisted `lease_expires_at` so an expired worker cannot
    /// commit results before the reaper runs.
    ///
    /// # Errors
    ///
    /// [`JobStoreError::LeaseLost`] if the lease no longer matches or
    /// has expired at `now_ms`.
    async fn complete(
        &self,
        job_id: &JobId,
        lease: &LeaseToken,
        now_ms: i64,
    ) -> Result<(), JobStoreError>;

    /// Record a failure. With [`FailDisposition::Retry`] the row goes
    /// back to `Queued` (or terminates if `attempts == max_attempts`);
    /// [`FailDisposition::Permanent`] forces terminal `Failed`.
    /// `class` is persisted on the row when a terminal disposition is
    /// reached (used by the lint `workflow_health` check).
    ///
    /// # Errors
    ///
    /// [`JobStoreError::LeaseLost`] if the lease no longer matches.
    async fn fail(
        &self,
        job_id: &JobId,
        lease: &LeaseToken,
        disposition: FailDisposition,
        class: FailureClass,
        last_error: &str,
        now_ms: i64,
    ) -> Result<(), JobStoreError>;

    /// Reclaim leased rows whose `lease_expires_at <= now_ms`. Used by
    /// the scheduler's reaper loop and on startup to recover orphans
    /// from a prior incarnation. Returns the number of rows reclaimed.
    ///
    /// # Errors
    ///
    /// Backend failure only.
    async fn reap_expired(&self, now_ms: i64) -> Result<usize, JobStoreError>;
}

// `Rfc3339Timestamp` is used elsewhere in the contract surface; bring it
// into scope so the doc-link in module docs resolves once any future
// change starts emitting timestamped events.
#[allow(dead_code)]
fn _ts_doc_anchor(_: Rfc3339Timestamp) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn retry_policy_default_grows_geometrically_until_cap() {
        let p = RetryPolicy::DEFAULT;
        assert_eq!(p.delay_for_attempt(0), 0);
        assert_eq!(p.delay_for_attempt(1), 1_000);
        assert_eq!(p.delay_for_attempt(2), 2_000);
        assert_eq!(p.delay_for_attempt(3), 4_000);
        assert_eq!(p.delay_for_attempt(4), 8_000);
        assert_eq!(p.delay_for_attempt(5), 16_000);
        assert_eq!(p.delay_for_attempt(6), 32_000);
        assert_eq!(p.delay_for_attempt(7), 60_000); // capped
        assert_eq!(p.delay_for_attempt(50), 60_000);
    }

    #[test]
    fn job_id_round_trip_string() {
        let id = JobId::new("01HQZ123");
        assert_eq!(id.as_str(), "01HQZ123");
        assert_eq!(format!("{id}"), "01HQZ123");
    }
}
