//! Skill emitter — writes the Cairn skill bundle into `skills/cairn/`.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;

use super::ir::{CliCommand, CliFlag, CliShape, Document, VerbDef};
use super::skill_compat::{
    any_of_required_branches, collect_arg_property_schemas, is_signed_int_source,
    is_unsigned_int_source, one_of_required_branches, required_excluding_const,
    variant_required_specs,
};
use super::{CodegenError, GeneratedFile};

const HEADER_MD: &str = "<!-- @generated by cairn-codegen — DO NOT EDIT. -->\n";

/// Emit the three skill-bundle files (`SKILL.md`, `conventions.md`, `.version`)
/// for the `skills/cairn/` directory.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    Ok(vec![
        emit_skill_md(doc)?,
        emit_conventions(doc),
        emit_version(doc),
    ])
}

fn emit_skill_md(doc: &Document) -> Result<GeneratedFile, CodegenError> {
    let mut s = String::new();
    s.push_str(HEADER_MD);
    s.push_str("---\n");
    s.push_str("name: cairn\n");
    s.push_str("description: Cairn memory system. Use for persistent memory across turns, sessions, and agents.\n");
    s.push_str("---\n\n");
    s.push_str("# Cairn Memory Skill\n\n");
    s.push_str("Persistent memory via the `cairn` CLI. The eight verbs below are the contract. ");
    s.push_str("Status / handshake are protocol preludes — see the bottom of this file.\n\n");
    for verb in &doc.verbs {
        push_verb_section(&mut s, verb)?;
    }
    s.push_str("---\n\n## Protocol preludes (not core verbs)\n\n");
    for prelude in &doc.preludes {
        let desc = match prelude.id.as_str() {
            "status" => "deterministic capability discovery (cacheable, no side effects).",
            "handshake" => "fresh per-call challenge mint.",
            _ => "(prelude)",
        };
        let _ = writeln!(s, "- `cairn {} --json` — {}", prelude.id, desc);
    }
    s.push('\n');
    Ok(GeneratedFile {
        path: PathBuf::from("skills/cairn/SKILL.md"),
        bytes: s.into_bytes(),
    })
}

fn push_verb_section(s: &mut String, verb: &VerbDef) -> Result<(), CodegenError> {
    let _ = write!(s, "## `cairn {}`\n\n", verb.id);
    if !verb.skill.positive.is_empty() {
        s.push_str("**Use when:**\n");
        for p in &verb.skill.positive {
            s.push_str("- ");
            s.push_str(p);
            s.push('\n');
        }
        s.push('\n');
    }
    if !verb.skill.negative.is_empty() {
        s.push_str("**Do NOT use when:**\n");
        for n in &verb.skill.negative {
            s.push_str("- ");
            s.push_str(n);
            s.push('\n');
        }
        s.push('\n');
    }
    if let Some(ex) = &verb.skill.exclusivity {
        s.push_str("**Exclusivity:** ");
        s.push_str(ex);
        s.push_str("\n\n");
    }
    push_verb_examples(s, verb)?;
    Ok(())
}

/// Emit canonical CLI example blocks per `CliCommand`. Coverage:
/// - one example per `anyOf` × `oneOf` branch combination so every
///   disjunctive/exclusive arm is exercised (e.g., `ingest --body` /
///   `--file` / `--url`, `retrieve --profile --user` / `--agent`); and
/// - one extra example per "interesting" optional flag (`json`,
///   `list<...>`, bounded ints, primitive `$ref` strings) so optional
///   user-visible paths participate in the compat gate too.
fn push_verb_examples(s: &mut String, verb: &VerbDef) -> Result<(), CodegenError> {
    let cmds: Vec<&CliCommand> = match &verb.cli {
        CliShape::Single(c) => vec![c],
        CliShape::Variants(v) => v.iter().collect(),
    };
    let specs = variant_specs_per_command(verb, &cmds);
    let prop_schemas = collect_arg_property_schemas(verb);
    let mut emitted_any = false;
    let mut buf = String::new();
    for (idx, cmd) in cmds.iter().enumerate() {
        let spec = specs.get(idx).cloned().unwrap_or_default();
        let branch_sets = expand_branches(&spec);
        let no_required_at_all =
            spec.base.is_empty() && spec.any_of.is_empty() && spec.one_of.is_empty();
        let any_renderable = branch_sets.iter().any(|req| set_is_renderable(cmd, req));
        // Fail closed for every command (single-shape or tagged-union
        // variant) whose schema *has* required fields but none of them
        // line up with a CLI flag/positional. A silent skip here would
        // hide CLI/schema drift on a verb that previously had a working
        // example (round-8 finding). Verbs with genuinely no required
        // fields (e.g., `assemble_hot`) keep their bare example below.
        if !no_required_at_all && !any_renderable {
            return Err(CodegenError::Emit(format!(
                "verb `{}` command `{}` (idx {idx}): no required field could be paired to a schema variant — CLI/schema drift likely",
                verb.id, cmd.command
            )));
        }
        for required in &branch_sets {
            if !set_is_renderable(cmd, required) {
                continue;
            }
            render_example(&mut buf, cmd, required, &prop_schemas, None);
            emitted_any = true;
        }
        // Once per branch we exercise required-field-only. Now layer in
        // every optional flag one at a time so the compat gate sees the
        // whole declared CLI surface — a rename or removal would block
        // codegen (round-9 finding). Skip flags that belong to any
        // anyOf/oneOf branch: those alter which disjunctive arm is
        // satisfied and would create XOR collisions on top of the
        // carrier (e.g., adding `--file` on top of the body branch).
        let carrier = branch_sets
            .iter()
            .find(|r| set_is_renderable(cmd, r))
            .cloned()
            .unwrap_or_default();
        let mut branch_flags: BTreeSet<String> = BTreeSet::new();
        for branch in spec.any_of.iter().chain(spec.one_of.iter()) {
            for f in branch {
                branch_flags.insert(f.clone());
            }
        }
        for flag in &cmd.flags {
            if carrier.contains(&flag.name) || branch_flags.contains(&flag.name) {
                continue;
            }
            render_example(
                &mut buf,
                cmd,
                &carrier,
                &prop_schemas,
                Some(flag.name.as_str()),
            );
            emitted_any = true;
        }
    }
    if emitted_any {
        s.push_str("**Example:**\n\n");
        s.push_str(&buf);
    }
    Ok(())
}

/// True when the example for `cmd` constrained to `required` would render
/// at least one token after the verb (a known flag or its positional). An
/// unrenderable required set means an empty `cairn <verb>` line, which the
/// gate rejects as ambiguous.
fn set_is_renderable(cmd: &CliCommand, required: &BTreeSet<String>) -> bool {
    let positional_in_required = cmd
        .positional
        .as_ref()
        .is_some_and(|p| required.contains(&p.name));
    let any_required_flag = cmd.flags.iter().any(|f| required.contains(&f.name));
    positional_in_required || any_required_flag
}

/// Per-command [`VariantSpec`] — for tagged-union verbs this defers to
/// `variant_required_specs`; for single-shape verbs it lifts `required` plus
/// every `anyOf`/`oneOf` branch off `$defs/Args`. Unlike the prior
/// `required_args_per_command`, this preserves the full branch list so the
/// emitter can render one example per disjunct.
fn variant_specs_per_command(
    verb: &VerbDef,
    cmds: &[&CliCommand],
) -> Vec<super::skill_compat::VariantSpec> {
    use super::skill_compat::VariantSpec;
    let cmd_count = cmds.len();
    if cmd_count > 1 {
        return variant_required_specs(verb, cmds);
    }
    let Ok(schema) = serde_json::from_slice::<serde_json::Value>(&verb.args_schema_bytes) else {
        return vec![VariantSpec::default(); cmd_count];
    };
    let Some(args) = schema.get("$defs").and_then(|d| d.get("Args")) else {
        return vec![VariantSpec::default(); cmd_count];
    };
    let spec = VariantSpec {
        base: required_excluding_const(args),
        any_of: any_of_required_branches(args),
        one_of: one_of_required_branches(args),
    };
    let mut out = Vec::with_capacity(cmd_count);
    out.push(spec);
    out.resize(cmd_count, VariantSpec::default());
    out
}

/// Produce one required-field set per branch combination so each disjunctive
/// (`anyOf`) and exclusive (`oneOf`) arm gets its own example. With no
/// branches this collapses to a single set equal to `base`.
fn expand_branches(spec: &super::skill_compat::VariantSpec) -> Vec<BTreeSet<String>> {
    let any_of: Vec<BTreeSet<String>> = if spec.any_of.is_empty() {
        vec![BTreeSet::new()]
    } else {
        spec.any_of.clone()
    };
    let one_of: Vec<BTreeSet<String>> = if spec.one_of.is_empty() {
        vec![BTreeSet::new()]
    } else {
        spec.one_of.clone()
    };
    let mut out = Vec::new();
    for a in &any_of {
        for o in &one_of {
            let mut combined = spec.base.clone();
            combined.extend(a.iter().cloned());
            combined.extend(o.iter().cloned());
            if !out.contains(&combined) {
                out.push(combined);
            }
        }
    }
    out
}

/// Render one `cairn <verb> ...` example into `buf`. `required` selects which
/// flags / positional to emit; `extra_optional` (when set) appends one more
/// flag after the required block — used to exercise an optional flag.
fn render_example(
    buf: &mut String,
    cmd: &CliCommand,
    required: &BTreeSet<String>,
    prop_schemas: &std::collections::BTreeMap<String, serde_json::Value>,
    extra_optional: Option<&str>,
) {
    buf.push_str("```bash\n");
    let _ = write!(buf, "cairn {}", cmd.command);
    for flag in &cmd.flags {
        if required.contains(&flag.name) {
            push_flag(buf, flag, prop_schemas);
        }
    }
    if let Some(extra) = extra_optional
        && let Some(flag) = cmd.flags.iter().find(|f| f.name == extra)
    {
        push_flag(buf, flag, prop_schemas);
    }
    if let Some(p) = &cmd.positional
        && required.contains(&p.name)
    {
        push_positional(buf, p, prop_schemas);
    }
    buf.push_str("\n```\n\n");
}

fn push_flag(
    buf: &mut String,
    flag: &CliFlag,
    prop_schemas: &std::collections::BTreeMap<String, serde_json::Value>,
) {
    if flag.value_source == "bool" {
        let _ = write!(buf, " --{}", flag.long);
    } else {
        let exemplar = exemplar_for_flag(
            &flag.name,
            &flag.value_source,
            flag.cli_exemplar.as_deref(),
            prop_schemas.get(&flag.name),
        );
        let _ = write!(buf, " --{} {}", flag.long, shell_quote(&exemplar));
    }
}

fn push_positional(
    buf: &mut String,
    p: &super::ir::CliPositional,
    prop_schemas: &std::collections::BTreeMap<String, serde_json::Value>,
) {
    let item_schema = prop_schemas.get(&p.name).and_then(|s| {
        if s.get("type").and_then(serde_json::Value::as_str) == Some("array") {
            s.get("items")
        } else {
            Some(s)
        }
    });
    let primitive_sample = item_schema
        .and_then(|s| s.get("$ref").and_then(serde_json::Value::as_str))
        .and_then(primitive_ref_exemplar);
    if p.repeatable {
        if let Some(sample) = primitive_sample {
            let _ = write!(buf, " {sample} {sample}");
        } else {
            let stem = placeholder_for(&p.name);
            let stem = stem.trim_end_matches('S');
            let _ = write!(buf, " {stem}_1 {stem}_2");
        }
    } else if let Some(sample) = primitive_sample {
        let _ = write!(buf, " {sample}");
    } else {
        let _ = write!(buf, " {}", placeholder_for(&p.name));
    }
}

/// Render a schema field name as an uppercase shell placeholder (`session_id`
/// → `SESSION_ID`).
fn placeholder_for(field: &str) -> String {
    field.to_ascii_uppercase()
}

/// Wrap a value in single quotes if it contains characters that would break
/// shell parsing (whitespace, JSON braces). `ALL_CAPS` placeholders and bare
/// values are emitted unquoted.
fn shell_quote(value: &str) -> String {
    if value
        .chars()
        .any(|c| c.is_whitespace() || matches!(c, '{' | '}' | '[' | ']' | '"' | '\''))
    {
        format!("'{value}'")
    } else {
        value.to_string()
    }
}

/// Pick a schema-valid concrete value for a required flag where the IDL
/// constrains it to a closed set (`enum(a,b,c)`, `list<enum(...)>`, integer
/// with `minimum`). For freeform value sources (`string`, `path`, `json`,
/// `list<string>`, …) fall back to an `ALL_CAPS` placeholder — the user is
/// expected to substitute their own value.
///
/// Emitting concrete exemplars for closed forms is what lets the skill-compat
/// gate validate the value (the validator bypasses `ALL_CAPS` placeholders).
fn exemplar_for_flag(
    field: &str,
    value_source: &str,
    cli_exemplar: Option<&str>,
    prop_schema: Option<&serde_json::Value>,
) -> String {
    if let Some(custom) = cli_exemplar {
        return custom.to_string();
    }
    if let Some(rest) = value_source.strip_prefix("enum(")
        && let Some(inner) = rest.strip_suffix(')')
        && let Some(first) = inner.split(',').next()
    {
        return first.trim().to_string();
    }
    if let Some(rest) = value_source.strip_prefix("list<enum(")
        && let Some(inner) = rest.strip_suffix(")>")
        && let Some(first) = inner.split(',').next()
    {
        return first.trim().to_string();
    }
    if is_unsigned_int_source(value_source) || is_signed_int_source(value_source) {
        if let Some(p) = prop_schema
            && let Some(min) = p.get("minimum").and_then(serde_json::Value::as_i64)
        {
            return min.to_string();
        }
        return "0".to_string();
    }
    // Constrained string/path with a primitive `$ref`: emit a concrete
    // schema-valid sample so the compat gate actually validates the value
    // instead of bypassing the placeholder.
    if let Some(p) = prop_schema
        && let Some(reference) = p.get("$ref").and_then(serde_json::Value::as_str)
        && let Some(sample) = primitive_ref_exemplar(reference)
    {
        return sample.to_string();
    }
    placeholder_for(field)
}

/// Concrete schema-valid sample for a well-known primitive `$ref`. Mirrors
/// `skill_compat::primitive_ref_pattern` so generated examples round-trip
/// through the validator. Add new entries here whenever a new primitive
/// becomes part of the public CLI surface.
fn primitive_ref_exemplar(reference: &str) -> Option<&'static str> {
    let suffix = reference.rsplit('/').next()?;
    match suffix {
        "Ulid" => Some("01H8XGJWBWBAQ4N1NQK1A8X9YZ"),
        "Identity" => Some("usr:alice"),
        _ => None,
    }
}

fn emit_conventions(doc: &Document) -> GeneratedFile {
    let mut s = String::new();
    s.push_str(HEADER_MD);
    s.push_str("# Cairn skill conventions\n\n");
    s.push_str("Verb ids in the contract:\n\n");
    for verb in &doc.verbs {
        let _ = writeln!(s, "- `{}`", verb.id);
    }
    s.push_str("\n<!-- Kinds cheat-sheet integrates when #4 lands the taxonomy IDL slice. -->\n");
    GeneratedFile {
        path: PathBuf::from("skills/cairn/conventions.md"),
        bytes: s.into_bytes(),
    }
}

fn emit_version(_doc: &Document) -> GeneratedFile {
    let s = format!(
        "contract: cairn.mcp.v1\ncairn-idl: {}\n",
        env!("CARGO_PKG_VERSION"),
    );
    GeneratedFile {
        path: PathBuf::from("skills/cairn/.version"),
        bytes: s.into_bytes(),
    }
}
