//! MCP emitter — writes tool declarations and JSON schemas into
//! `crates/cairn-mcp/src/generated/`.

use std::fmt::Write as _;
use std::path::PathBuf;

use serde_json::Value;

use super::fmt::{RustWriter, write_json_canonical};
use super::ir::{Document, VerbDef};
use super::{CodegenError, GeneratedFile};

const HEADER_RS: &str = "// @generated by cairn-codegen — DO NOT EDIT.\n";
const FILE_LINTS: &str = "#![allow(clippy::module_name_repetitions, clippy::large_enum_variant, clippy::missing_errors_doc, clippy::missing_panics_doc, clippy::doc_markdown, clippy::needless_raw_string_hashes, missing_docs, dead_code)]\n";
const ROOT: &str = "crates/cairn-mcp/src/generated";

/// Emit the MCP tool declaration module plus per-verb / per-prelude JSON schemas.
///
/// # Errors
///
/// Returns [`CodegenError::Emit`] if a stored schema fails to parse as JSON
/// during the canonicalisation pass.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    let mut out = Vec::new();
    out.push(emit_mod(doc));
    for verb in &doc.verbs {
        out.push(emit_schema(
            &format!("{ROOT}/schemas/verbs/{}.json", verb.id),
            &verb.args_schema_bytes,
        )?);
    }
    for prelude in &doc.preludes {
        out.push(emit_schema(
            &format!("{ROOT}/schemas/prelude/{}.json", prelude.id),
            &prelude.schema_bytes,
        )?);
    }
    Ok(out)
}

fn emit_mod(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER_RS);
    w.raw(FILE_LINTS);
    w.line("//! Generated MCP tool declarations for cairn.mcp.v1.");
    w.blank();
    w.line("/// Static tool declaration the MCP transport layer registers at startup.");
    w.line("pub struct ToolDecl {");
    w.indent();
    w.line("pub name: &'static str,");
    w.line("pub description: &'static str,");
    w.line("pub input_schema: &'static [u8],");
    w.line("pub capability: Option<&'static str>,");
    w.line("pub auth: &'static str,");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("pub const TOOLS: &[ToolDecl] = &[");
    w.indent();
    for verb in &doc.verbs {
        emit_tool_decl(&mut w, verb);
    }
    w.dedent();
    w.line("];");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

fn emit_tool_decl(w: &mut RustWriter, verb: &VerbDef) {
    let description = build_description(verb);
    w.line("ToolDecl {");
    w.indent();
    w.line(&format!("name: \"{}\",", verb.id));
    // Multi-line raw string so embedded newlines stay readable.
    w.line(&format!("description: r#\"{description}\"#,"));
    w.line(&format!(
        "input_schema: include_bytes!(\"schemas/verbs/{}.json\"),",
        verb.id
    ));
    match &verb.capability {
        Some(c) => w.line(&format!("capability: Some(\"{c}\"),")),
        None => w.line("capability: None,"),
    }
    w.line(&format!("auth: \"{}\",", verb.auth.as_str()));
    w.dedent();
    w.line("},");
}

fn build_description(verb: &VerbDef) -> String {
    // §8.0.b: one-line purpose + positive triggers + negative triggers + exclusivity.
    let mut s = String::new();
    let _ = writeln!(s, "`{}` — verb {}.", verb.id, verb.id);
    if !verb.skill.positive.is_empty() {
        s.push_str("\nPOSITIVE — use when:\n");
        for p in &verb.skill.positive {
            s.push_str("• ");
            s.push_str(p);
            s.push('\n');
        }
    }
    if !verb.skill.negative.is_empty() {
        s.push_str("\nNEGATIVE — do not use when:\n");
        for n in &verb.skill.negative {
            s.push_str("• ");
            s.push_str(n);
            s.push('\n');
        }
    }
    if let Some(ex) = &verb.skill.exclusivity {
        s.push_str("\nEXCLUSIVITY: ");
        s.push_str(ex);
        s.push('\n');
    }
    s
}

fn emit_schema(rel_path: &str, raw_bytes: &[u8]) -> Result<GeneratedFile, CodegenError> {
    // Parse + re-serialise canonically so the on-disk schema is normalised
    // (sorted keys, two-space indent, trailing newline). Validation guarantees
    // the input parses; if it ever doesn't, surface the error.
    let value: Value = serde_json::from_slice(raw_bytes)
        .map_err(|e| CodegenError::Emit(format!("schema parse: {e}")))?;
    Ok(GeneratedFile {
        path: PathBuf::from(rel_path),
        bytes: write_json_canonical(&value).into_bytes(),
    })
}
