//! CLI emitter — writes a clap `Command` builder into
//! `crates/cairn-cli/src/generated/`.
//!
//! Walks the `Document` IR and produces:
//!
//! * `mod.rs` — `pub fn command() -> clap::Command` returning the full tree.
//! * `verbs.rs` — one `pub fn <verb>_subcommand() -> clap::Command` per verb.
//! * `prelude.rs` — `status_subcommand` and `handshake_subcommand`.
//!
//! The CLI shape is taken from the IR's [`CliShape`] which mirrors the
//! `x-cairn-cli` block in the IDL. `value_source` strings are translated to
//! clap `Arg` value parsers / actions per the table in the design brief.

use std::fmt::Write as _;
use std::path::PathBuf;

use super::fmt::RustWriter;
use super::ir::{CliCommand, CliFlag, CliShape, Document, PreludeDef, VerbDef};
use super::{CodegenError, GeneratedFile};

const HEADER: &str = "// @generated by cairn-codegen — DO NOT EDIT.\n";
const RUSTFMT_SKIP: &str = "#![cfg_attr(rustfmt, rustfmt_skip)]\n";
const ROOT: &str = "crates/cairn-cli/src/generated";
const FILE_LINTS: &str = "#![allow(clippy::too_many_lines, clippy::missing_errors_doc, clippy::missing_panics_doc, clippy::doc_markdown, missing_docs, dead_code)]\n";

/// Emit every CLI file declared by `doc`.
///
/// # Errors
/// Returns [`CodegenError::Emit`] when an IR construct cannot be rendered.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    Ok(vec![
        emit_root_mod(doc),
        emit_verbs(doc)?,
        emit_prelude(doc),
    ])
}

// ── Root mod.rs ──────────────────────────────────────────────────────────────

fn emit_root_mod(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Generated clap `Command` tree for the cairn.mcp.v1 contract.");
    w.line("//!");
    w.line("//! Regenerate with `cargo run -p cairn-idl --bin cairn-codegen`.");
    w.blank();
    w.line("pub mod prelude;");
    w.line("pub mod verbs;");
    w.blank();
    w.line("/// Every subcommand name advertised by [`command`] in declaration order");
    w.line("/// (eight verbs followed by every protocol prelude).");
    w.line("pub const SUBCOMMANDS: &[&str] = &[");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!("\"{}\",", verb.id));
    }
    for prelude in &doc.preludes {
        w.line(&format!("\"{}\",", prelude.id));
    }
    w.dedent();
    w.line("];");
    w.blank();
    w.line("/// Build the full clap `Command` tree (verbs + protocol preludes).");
    w.line("#[must_use]");
    w.line("pub fn command() -> clap::Command {");
    w.indent();
    w.line("clap::Command::new(\"cairn\")");
    w.indent();
    w.line(".about(\"Cairn — agent memory framework (cairn.mcp.v1)\")");
    w.line(".subcommand_required(true)");
    w.line(".arg_required_else_help(true)");
    for verb in &doc.verbs {
        w.line(&format!(".subcommand(verbs::{}_subcommand())", verb.id));
    }
    for prelude in &doc.preludes {
        w.line(&format!(
            ".subcommand(prelude::{}_subcommand())",
            prelude.id
        ));
    }
    w.dedent();
    w.dedent();
    w.line("}");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── verbs.rs ─────────────────────────────────────────────────────────────────

fn emit_verbs(doc: &Document) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Per-verb clap subcommand builders.");
    w.blank();
    for (i, verb) in doc.verbs.iter().enumerate() {
        if i > 0 {
            w.blank();
        }
        write_verb_subcommand(&mut w, verb)?;
    }
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join("verbs.rs"),
        bytes: w.finish().into_bytes(),
    })
}

fn write_verb_subcommand(w: &mut RustWriter, verb: &VerbDef) -> Result<(), CodegenError> {
    w.line(&format!("/// `cairn {}` subcommand builder.", verb.id));
    w.line("#[must_use]");
    w.line(&format!(
        "pub fn {}_subcommand() -> clap::Command {{",
        verb.id
    ));
    w.indent();

    match &verb.cli {
        CliShape::Single(cmd) => write_single_command(w, cmd),
        CliShape::Variants(variants) => write_variant_command(w, &verb.id, variants)?,
    }

    w.dedent();
    w.line("}");
    Ok(())
}

/// Emit a single subcommand (no variants). The `cmd.command` is the
/// subcommand name; flags + optional positional are translated to clap args.
fn write_single_command(w: &mut RustWriter, cmd: &CliCommand) {
    w.line(&format!("clap::Command::new(\"{}\")", cmd.command));
    w.indent();
    w.line(&format!(".about(\"cairn.mcp.v1 verb: {}\")", cmd.command));
    for flag in &cmd.flags {
        w.line(&format!(".arg({})", render_flag_arg(flag)));
    }
    if let Some(pos) = &cmd.positional {
        w.line(&format!(
            ".arg(clap::Arg::new(\"{}\").help(\"{}\").required(false){})",
            pos.name,
            escape_rust_str(&pos.description),
            if pos.repeatable {
                // Repeatable positional → clap `num_args(1..)` so the parser
                // accepts `cairn summarize ID1 ID2 …` instead of treating
                // every token after the first as an excess arg.
                ".num_args(1..)"
            } else {
                ""
            }
        ));
    }
    w.dedent();
}

/// Emit a subcommand whose `Args` is a tagged union. Each variant contributes
/// its own flag set; an `ArgGroup` keyed on the discriminator-bearing flag
/// (the first flag of each variant) enforces exactly-one selection.
fn write_variant_command(
    w: &mut RustWriter,
    verb_id: &str,
    variants: &[CliCommand],
) -> Result<(), CodegenError> {
    if variants.is_empty() {
        return Err(CodegenError::Emit(format!(
            "{verb_id}: CliShape::Variants must have at least one variant"
        )));
    }
    // The subcommand name is shared across variants — take the first.
    let name = &variants[0].command;
    w.line(&format!("clap::Command::new(\"{name}\")"));
    w.indent();
    w.line(&format!(".about(\"cairn.mcp.v1 verb: {name}\")"));

    // Merge flags by `name` while preserving first-seen order. Variants may
    // share flag names (e.g. `session_id`) — clap requires unique arg ids, so
    // we de-duplicate while emitting.
    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut group_members: Vec<String> = Vec::new();
    for variant in variants {
        // The discriminator-bearing flag: prefer the first flag, falling back
        // to the positional name when the variant has only a positional (e.g.
        // `retrieve <id>` for ArgsRecord).
        if let Some(first) = variant.flags.first() {
            if !group_members.contains(&first.name) {
                group_members.push(first.name.clone());
            }
        } else if let Some(pos) = &variant.positional
            && !group_members.contains(&pos.name)
        {
            group_members.push(pos.name.clone());
        }
        for flag in &variant.flags {
            if seen.insert(flag.name.clone()) {
                w.line(&format!(".arg({})", render_flag_arg(flag)));
            }
        }
        if let Some(pos) = &variant.positional
            && seen.insert(pos.name.clone())
        {
            w.line(&format!(
                ".arg(clap::Arg::new(\"{}\").help(\"{}\").required(false){})",
                pos.name,
                escape_rust_str(&pos.description),
                if pos.repeatable { ".num_args(1..)" } else { "" }
            ));
        }
    }

    // ArgGroup — exactly one of the discriminator flags must be supplied.
    if !group_members.is_empty() {
        let mut group_line = format!(".group(clap::ArgGroup::new(\"{verb_id}_target\")");
        group_line.push_str(".required(true).multiple(false)");
        for member in &group_members {
            let _ = write!(group_line, ".arg(\"{member}\")");
        }
        group_line.push(')');
        w.line(&group_line);
    }

    w.dedent();
    Ok(())
}

// ── prelude.rs ───────────────────────────────────────────────────────────────

fn emit_prelude(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Protocol-prelude clap subcommands (status, handshake).");
    w.blank();
    for (i, prelude) in doc.preludes.iter().enumerate() {
        if i > 0 {
            w.blank();
        }
        write_prelude_subcommand(&mut w, prelude);
    }
    GeneratedFile {
        path: PathBuf::from(ROOT).join("prelude.rs"),
        bytes: w.finish().into_bytes(),
    }
}

fn write_prelude_subcommand(w: &mut RustWriter, prelude: &PreludeDef) {
    w.line(&format!(
        "/// `cairn {}` protocol-prelude subcommand builder.",
        prelude.id
    ));
    w.line("#[must_use]");
    w.line(&format!(
        "pub fn {}_subcommand() -> clap::Command {{",
        prelude.id
    ));
    w.indent();
    w.line(&format!("clap::Command::new(\"{}\")", prelude.id));
    w.indent();
    w.line(&format!(".about(\"cairn.mcp.v1 prelude: {}\")", prelude.id));
    w.dedent();
    w.dedent();
    w.line("}");
}

// ── Flag rendering ───────────────────────────────────────────────────────────

/// Render one `CliFlag` as a clap `Arg` builder expression.
fn render_flag_arg(flag: &CliFlag) -> String {
    let mut out = format!("clap::Arg::new(\"{}\").long(\"{}\")", flag.name, flag.long);
    let (action, parser, value_name) = parse_value_source(&flag.value_source);
    if let Some(name) = value_name {
        let _ = write!(out, ".value_name(\"{name}\")");
    }
    if let Some(parser) = parser {
        let _ = write!(out, ".value_parser({parser})");
    }
    if let Some(action) = action {
        let _ = write!(out, ".action({action})");
    }
    // For closed `list<enum(...)>` flags, expose comma-delimited single-
    // token form in addition to repeated occurrences. We deliberately do
    // NOT delimit `list<string>` / `list<path>` because commas are valid
    // payload data there (e.g., `ingest --tags "foo,bar"` must preserve
    // `foo,bar` as a single tag, not split into two).
    if flag
        .value_source
        .strip_prefix("list<enum(")
        .and_then(|s| s.strip_suffix(")>"))
        .is_some()
    {
        let _ = write!(out, ".value_delimiter(',')");
    }
    out
}

/// Translate a `value_source` string into clap action / parser / value-name
/// fragments. Returns `(action, parser, value_name)` — each optional.
fn parse_value_source(source: &str) -> (Option<String>, Option<String>, Option<String>) {
    // list<...> — recurse on inner type and switch action to Append.
    if let Some(inner) = source
        .strip_prefix("list<")
        .and_then(|s| s.strip_suffix('>'))
    {
        let (_, parser, value_name) = parse_value_source(inner);
        return (
            Some("clap::ArgAction::Append".to_string()),
            parser,
            value_name.or_else(|| Some("VALUE".to_string())),
        );
    }
    // enum(a,b,c) — closed string set.
    if let Some(inner) = source
        .strip_prefix("enum(")
        .and_then(|s| s.strip_suffix(')'))
    {
        let variants: Vec<&str> = inner.split(',').map(str::trim).collect();
        let parser = format!(
            "[{}]",
            variants
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join(", ")
        );
        return (None, Some(parser), Some("ENUM".to_string()));
    }
    match source {
        "string" => (None, None, Some("STRING".to_string())),
        "u8" => (
            None,
            Some("clap::value_parser!(u8)".to_string()),
            Some("U8".to_string()),
        ),
        "u32" => (
            None,
            Some("clap::value_parser!(u32)".to_string()),
            Some("U32".to_string()),
        ),
        "u64" => (
            None,
            Some("clap::value_parser!(u64)".to_string()),
            Some("U64".to_string()),
        ),
        "i64" => (
            None,
            Some("clap::value_parser!(i64)".to_string()),
            Some("I64".to_string()),
        ),
        "path" => (
            None,
            Some("clap::builder::PathBufValueParser::new()".to_string()),
            Some("PATH".to_string()),
        ),
        "bool" => (Some("clap::ArgAction::SetTrue".to_string()), None, None),
        "json" => (None, None, Some("JSON".to_string())),
        // Unknown — treat as raw string (no parser); snapshot tests in Phase 6
        // will catch any surprise value_source.
        _ => (None, None, Some("VALUE".to_string())),
    }
}

/// Escape a string for embedding inside a Rust `"..."` literal.
fn escape_rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::ir::CliPositional;

    /// Tagged-union variant with a repeatable positional must emit
    /// `.num_args(1..)` so the generated clap command actually accepts
    /// multiple values, matching the skill-compat gate's expectations.
    #[test]
    fn variant_command_emits_num_args_for_repeatable_positional() {
        let variants = vec![
            CliCommand {
                command: "demo".to_string(),
                flags: vec![CliFlag {
                    name: "session_id".to_string(),
                    long: "session".to_string(),
                    value_source: "string".to_string(),
                    cli_exemplar: None,
                }],
                positional: None,
            },
            CliCommand {
                command: "demo".to_string(),
                flags: vec![],
                positional: Some(CliPositional {
                    name: "ids".to_string(),
                    description: "Many IDs".to_string(),
                    repeatable: true,
                    aliases_one_of: Vec::new(),
                }),
            },
        ];
        let mut w = RustWriter::new();
        write_variant_command(&mut w, "demo", &variants).expect("emit");
        let rendered = w.finish();
        assert!(
            rendered.contains(".num_args(1..)"),
            "variant repeatable positional must emit num_args(1..); got:\n{rendered}"
        );
    }
}
