//! SDK emitter — writes Rust types into `crates/cairn-core/src/generated/`.
//!
//! Walks the `Document` IR and produces:
//!
//! * `mod.rs` — root re-exports.
//! * `verbs/mod.rs` — `VerbId` enum + capability/auth registry + capability list.
//! * `verbs/<id>.rs` (× 8) — per-verb `Args` and `Data` Rust types.
//! * `common/mod.rs` — shared types lifted from `common/*.json`.
//! * `errors/mod.rs` — `ErrorCode` enum.
//! * `envelope/mod.rs` — Request / Response / `SignedIntent` types.
//! * `status.rs`, `handshake.rs` — protocol prelude responses.
//!
//! Output bytes are deterministic per `Document` IR; snapshot tests in Phase 6
//! lock down the exact representation.

use std::collections::BTreeSet;
use std::path::PathBuf;

use super::fmt::RustWriter;
use super::ir::{
    Document, EnumDef, EnumVariant, PreludeDef, Prim, RecursiveEnumDef, RustType, StructDef,
    StructField, TaggedUnionDef, TaggedVariant, TypeName, UntaggedUnionDef, VerbDef, pascal_case,
};
use super::{CodegenError, GeneratedFile};

const HEADER: &str = "// @generated by cairn-codegen — DO NOT EDIT.\n";
const RUSTFMT_SKIP: &str = "#![cfg_attr(rustfmt, rustfmt_skip)]\n";
const ROOT: &str = "crates/cairn-core/src/generated";
const FILE_LINTS: &str = "#![allow(clippy::module_name_repetitions, clippy::large_enum_variant, clippy::missing_errors_doc, clippy::missing_panics_doc, clippy::doc_markdown, clippy::match_same_arms, clippy::cast_lossless, clippy::bool_to_int_with_if, missing_docs, dead_code)]\n";

/// Emit every SDK file declared by `doc`.
///
/// # Errors
/// Returns [`CodegenError::Emit`] when an IR construct cannot be rendered.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    let common_names: BTreeSet<String> = doc.common.keys().map(|t| t.0.clone()).collect();

    let mut out = Vec::new();
    out.push(emit_root_mod(doc));
    out.push(emit_verbs_mod(doc));
    for verb in &doc.verbs {
        out.push(emit_verb_file(verb, &common_names)?);
    }
    out.push(emit_common(doc, &common_names)?);
    out.push(emit_errors(doc));
    out.push(emit_envelope(doc, &common_names)?);
    for prelude in &doc.preludes {
        out.push(emit_prelude(prelude, &common_names)?);
    }
    Ok(out)
}

// ── Root re-exports ──────────────────────────────────────────────────────────

fn emit_root_mod(_doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Generated SDK surface for the cairn.mcp.v1 contract.");
    w.line("//!");
    w.line("//! Regenerate with `cargo run -p cairn-idl --bin cairn-codegen`.");
    w.blank();
    w.line("pub mod common;");
    w.line("pub mod envelope;");
    w.line("pub mod errors;");
    w.line("pub mod handshake;");
    w.line("pub mod status;");
    w.line("pub mod verbs;");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Verbs registry ───────────────────────────────────────────────────────────

fn emit_verbs_mod(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Verb registry. The eight P0 verbs in IDL order.");
    w.blank();
    for verb in &doc.verbs {
        w.line(&format!("pub mod {};", verb.id));
    }
    w.blank();
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
    w.line("#[non_exhaustive]");
    w.line("pub enum VerbId {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!("{},", pascal_case(&verb.id)));
    }
    w.dedent();
    w.line("}");
    w.blank();
    w.line("impl VerbId {");
    w.indent();
    w.line("#[must_use]");
    w.line("pub const fn as_str(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&verb.id),
            verb.id
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("#[must_use]");
    w.line("pub const fn capability(self) -> Option<&'static str> {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        match &verb.capability {
            Some(c) => w.line(&format!(
                "Self::{} => Some(\"{c}\"),",
                pascal_case(&verb.id)
            )),
            None => w.line(&format!("Self::{} => None,", pascal_case(&verb.id))),
        }
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("#[must_use]");
    w.line("pub const fn auth(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&verb.id),
            verb.auth.as_str()
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("/// Every advertised capability string in declaration order.");
    w.line("pub const CAPABILITIES: &[&str] = &[");
    w.indent();
    for cap in &doc.capabilities {
        w.line(&format!("\"{cap}\","));
    }
    w.dedent();
    w.line("];");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("verbs/mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Per-verb file ────────────────────────────────────────────────────────────

fn emit_verb_file(
    verb: &VerbDef,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line(&format!(
        "//! Generated SDK types for the `{}` verb.",
        verb.id
    ));
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    // Sibling locally-defined types referenced from Args/Data (e.g. `Hit`).
    // Emit before Args/Data so source-order references resolve.
    for (name, ty) in &verb.local_types {
        let renamed = renamed_to(ty, name.clone());
        write_type_decl(&mut w, &renamed, common_names)?;
        w.blank();
    }
    let args_fallback = format!("{}Args", pascal_case(&verb.id));
    let data_fallback = format!("{}Data", pascal_case(&verb.id));
    write_named_type(&mut w, &verb.args, &args_fallback, common_names)?;
    w.blank();
    write_named_type(&mut w, &verb.data, &data_fallback, common_names)?;
    w.blank();
    let schema_path = format!(
        "../../../../cairn-mcp/src/generated/schemas/verbs/{}.json",
        verb.id
    );
    w.line(&format!(
        "pub const ARGS_SCHEMA: &[u8] = include_bytes!(\"{schema_path}\");"
    ));
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join(format!("verbs/{}.rs", verb.id)),
        bytes: w.finish().into_bytes(),
    })
}

// ── Common types ─────────────────────────────────────────────────────────────

fn emit_common(
    doc: &Document,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Common types shared across verbs (Ulid, Cursor, Identity, ...).");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();

    // BTreeMap iterates in sorted key order — deterministic.
    for (name, ty) in &doc.common {
        emit_common_entry(&mut w, name, ty, common_names)?;
        w.blank();
    }

    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join("common/mod.rs"),
        bytes: w.finish().into_bytes(),
    })
}

/// Emit one entry of the `common/` namespace. Primitive entries become
/// `pub type Foo = Bar;` (or newtype if aliasable to a primitive); structured
/// entries dispatch through `write_type_decl`.
fn emit_common_entry(
    w: &mut RustWriter,
    name: &TypeName,
    ty: &RustType,
    common_names: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Primitive(p) => {
            // Common primitives are exposed as transparent newtype wrappers
            // so the IDL-declared identity (e.g. `Ulid`) survives in the
            // type system.
            w.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]");
            w.line("#[serde(transparent)]");
            w.line(&format!("pub struct {}(pub {});", name.0, render_prim(*p)));
        }
        RustType::Json => {
            w.line(&format!("pub type {} = serde_json::Value;", name.0));
        }
        RustType::Map(inner) => {
            w.line(&format!(
                "pub type {} = std::collections::BTreeMap<String, {}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Vec(inner) => {
            w.line(&format!(
                "pub type {} = Vec<{}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Optional(inner) => {
            w.line(&format!(
                "pub type {} = Option<{}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Ref(target) => {
            w.line(&format!(
                "pub type {} = {};",
                name.0,
                render_ref(target, common_names)
            ));
        }
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            // Force the IR's nominal name onto a clone of the IR variant so
            // top-level emission preserves the common-namespace identifier.
            let aliased = renamed_to(ty, name.clone());
            write_type_decl(w, &aliased, common_names)?;
        }
    }
    Ok(())
}

/// Return a copy of `ty` with its nominal name swapped to `name` (only the
/// outer Struct/Enum/Union — inner names are preserved).
fn renamed_to(ty: &RustType, name: TypeName) -> RustType {
    match ty.clone() {
        RustType::Struct(mut s) => {
            s.name = name;
            RustType::Struct(s)
        }
        RustType::Enum(mut e) => {
            e.name = name;
            RustType::Enum(e)
        }
        RustType::TaggedUnion(mut t) => {
            t.name = name;
            RustType::TaggedUnion(t)
        }
        RustType::UntaggedUnion(mut u) => {
            u.name = name;
            RustType::UntaggedUnion(u)
        }
        RustType::Recursive(mut r) => {
            r.name = name;
            RustType::Recursive(r)
        }
        other => other,
    }
}

// ── Errors enum ──────────────────────────────────────────────────────────────

fn emit_errors(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Errors enum lowered from errors/error.json.");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]");
    // No `rename_all` — IDL error codes are PascalCase wire constants and the
    // generated variant idents are already byte-identical to the wire form, so
    // serde's default naming serialises/deserialises them without any rename.
    w.line("#[non_exhaustive]");
    w.line("pub enum ErrorCode {");
    w.indent();
    for code in &doc.error_codes {
        w.line(&format!("{},", pascal_case(&code.code)));
    }
    w.dedent();
    w.line("}");
    w.blank();
    w.line("impl ErrorCode {");
    w.indent();
    w.line("#[must_use]");
    w.line("pub const fn as_str(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for code in &doc.error_codes {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&code.code),
            code.code
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("errors/mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Envelope (request, response, signed_intent) ──────────────────────────────

fn emit_envelope(
    doc: &Document,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Request / response envelope types.");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    for ty in doc.envelope.values() {
        write_type_decl(&mut w, ty, common_names)?;
        w.blank();
    }
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join("envelope/mod.rs"),
        bytes: w.finish().into_bytes(),
    })
}

// ── Preludes ─────────────────────────────────────────────────────────────────

fn emit_prelude(
    prelude: &PreludeDef,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line(&format!(
        "//! Generated SDK type for the `{}` prelude.",
        prelude.id
    ));
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    let fallback = format!("{}Response", pascal_case(&prelude.id));
    write_named_type(&mut w, &prelude.response, &fallback, common_names)?;
    w.blank();
    let schema_path = format!(
        "../../../cairn-mcp/src/generated/schemas/prelude/{}.json",
        prelude.id
    );
    w.line(&format!(
        "pub const SCHEMA: &[u8] = include_bytes!(\"{schema_path}\");"
    ));
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join(format!("{}.rs", prelude.id)),
        bytes: w.finish().into_bytes(),
    })
}

// ── Top-level type declaration writer ────────────────────────────────────────

/// Walk a `RustType` and emit a top-level Rust declaration. Nested types are
/// flattened into siblings so the file stays a flat module. (Recursive on
/// nested struct fields where the field type is itself a Struct/Enum/etc.)
fn write_type_decl(
    w: &mut RustWriter,
    ty: &RustType,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Struct(s) => write_struct(w, s, common),
        RustType::Enum(e) => {
            write_enum(w, e);
            Ok(())
        }
        RustType::TaggedUnion(t) => write_tagged_union(w, t, common),
        RustType::UntaggedUnion(u) => write_untagged_union(w, u, common),
        RustType::Recursive(r) => write_recursive(w, r, common),
        // For top-level emission, scalar variants get wrapped in a tiny
        // module-level newtype so they are addressable. In practice the IR
        // never lands here at the verb-file level — the verb's Args/Data is
        // always one of the declarable variants above.
        other => Err(CodegenError::Emit(format!(
            "write_type_decl: cannot emit non-named type at top level: {other:?}"
        ))),
    }
}

/// Like `write_type_decl`, but accepts an explicit fallback name to use when
/// the IR variant doesn't carry one (Json, Primitive, Vec, ...). Named
/// variants (Struct/Enum/...) are emitted as-is — the existing IR name wins
/// over the fallback.
fn write_named_type(
    w: &mut RustWriter,
    ty: &RustType,
    fallback: &str,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => write_type_decl(w, ty, common),
        RustType::Primitive(p) => {
            w.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]");
            w.line("#[serde(transparent)]");
            w.line(&format!("pub struct {fallback}(pub {});", render_prim(*p)));
            Ok(())
        }
        RustType::Json => {
            w.line(&format!("pub type {fallback} = serde_json::Value;"));
            Ok(())
        }
        RustType::Vec(inner) => {
            w.line(&format!(
                "pub type {fallback} = Vec<{}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Map(inner) => {
            w.line(&format!(
                "pub type {fallback} = std::collections::BTreeMap<String, {}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Optional(inner) => {
            w.line(&format!(
                "pub type {fallback} = Option<{}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Ref(name) => {
            w.line(&format!(
                "pub type {fallback} = {};",
                render_ref(name, common)
            ));
            Ok(())
        }
    }
}

// ── Struct ───────────────────────────────────────────────────────────────────

fn write_struct(
    w: &mut RustWriter,
    s: &StructDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Emit any nested structured types in the fields *first* so the parent
    // declaration's references resolve in source order.
    let mut nested = Vec::new();
    collect_nested_from_fields(&s.fields, &s.name.0, &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &s.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    if s.deny_unknown_fields {
        w.line("#[serde(deny_unknown_fields)]");
    }
    w.line(&format!("pub struct {} {{", s.name.0));
    w.indent();
    for field in &s.fields {
        write_field(w, field, &s.name.0, common, true);
    }
    w.dedent();
    w.line("}");
    Ok(())
}

fn write_field(
    w: &mut RustWriter,
    field: &StructField,
    parent_name: &str,
    common: &BTreeSet<String>,
    pub_qualifier: bool,
) {
    if let Some(doc) = &field.doc {
        write_doc(w, doc);
    }
    let serde_name = if rust_keyword(&field.name) || !is_valid_ident(&field.name) {
        Some(field.name.clone())
    } else {
        None
    };
    if matches!(field.ty, RustType::Optional(_)) {
        w.line("#[serde(default, skip_serializing_if = \"Option::is_none\")]");
    }
    if let Some(name) = &serde_name {
        w.line(&format!("#[serde(rename = \"{name}\")]"));
    }
    let ident = sanitise_ident(&field.name);
    let ty_str = render_field_type(&field.ty, parent_name, &field.name, common);
    let prefix = if pub_qualifier { "pub " } else { "" };
    w.line(&format!("{prefix}{ident}: {ty_str},"));
}

// ── Enum (string enum) ───────────────────────────────────────────────────────

fn write_enum(w: &mut RustWriter, e: &EnumDef) {
    if let Some(doc) = &e.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]");
    if let Some(rename) = e.rename_all {
        w.line(&format!("#[serde(rename_all = \"{rename}\")]"));
    }
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", e.name.0));
    w.indent();
    for variant in &e.variants {
        write_enum_variant(w, variant);
    }
    w.dedent();
    w.line("}");
    if e.variants.iter().any(|v| v.capability.is_some()) {
        w.blank();
        w.line(&format!("impl {} {{", e.name.0));
        w.indent();
        w.line("/// Capability advertised by the IDL for the matched variant, or `None`.");
        w.line("#[must_use]");
        w.line("pub const fn capability(self) -> Option<&'static str> {");
        w.indent();
        w.line("match self {");
        w.indent();
        for variant in &e.variants {
            match &variant.capability {
                Some(cap) => w.line(&format!("Self::{} => Some(\"{cap}\"),", variant.rust_ident)),
                None => w.line(&format!("Self::{} => None,", variant.rust_ident)),
            }
        }
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }
}

fn write_enum_variant(w: &mut RustWriter, variant: &EnumVariant) {
    if let Some(doc) = &variant.doc {
        write_doc(w, doc);
    }
    // Serde's rename_all handles the wire mapping for snake_case identifiers,
    // but if the wire form contains characters that don't fit the rename rule
    // we attach an explicit rename.
    if !wire_matches_rename(&variant.wire, &variant.rust_ident) {
        w.line(&format!("#[serde(rename = \"{}\")]", variant.wire));
    }
    w.line(&format!("{},", variant.rust_ident));
}

// ── Tagged union ─────────────────────────────────────────────────────────────

fn write_tagged_union(
    w: &mut RustWriter,
    t: &TaggedUnionDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Hoist nested structured types referenced by variant fields.
    let mut nested = Vec::new();
    for variant in &t.variants {
        let parent = format!("{}{}", t.name.0, variant.rust_ident);
        collect_nested_from_fields(&variant.fields, &parent, &mut nested);
    }
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &t.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    w.line(&format!(
        "#[serde(tag = \"{}\", rename_all = \"snake_case\")]",
        t.discriminator
    ));
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", t.name.0));
    w.indent();
    for variant in &t.variants {
        write_tagged_variant(w, variant, &t.name.0, common);
    }
    w.dedent();
    w.line("}");
    if t.variants.iter().any(|v| v.capability.is_some()) {
        w.blank();
        w.line(&format!("impl {} {{", t.name.0));
        w.indent();
        w.line("/// Capability advertised by the IDL for the matched variant, or `None`.");
        w.line("#[must_use]");
        w.line("pub fn capability(&self) -> Option<&'static str> {");
        w.indent();
        w.line("match self {");
        w.indent();
        for variant in &t.variants {
            // Match arm pattern depends on whether the variant has fields.
            let arm = if variant.fields.is_empty() {
                format!("Self::{}", variant.rust_ident)
            } else {
                format!("Self::{} {{ .. }}", variant.rust_ident)
            };
            match &variant.capability {
                Some(cap) => w.line(&format!("{arm} => Some(\"{cap}\"),")),
                None => w.line(&format!("{arm} => None,")),
            }
        }
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }
    Ok(())
}

fn write_tagged_variant(
    w: &mut RustWriter,
    variant: &TaggedVariant,
    parent_name: &str,
    common: &BTreeSet<String>,
) {
    if let Some(doc) = &variant.doc {
        write_doc(w, doc);
    }
    if !wire_matches_rename(&variant.wire, &variant.rust_ident) {
        w.line(&format!("#[serde(rename = \"{}\")]", variant.wire));
    }
    if variant.fields.is_empty() {
        w.line(&format!("{},", variant.rust_ident));
        return;
    }
    w.line(&format!("{} {{", variant.rust_ident));
    w.indent();
    let nested_parent = format!("{parent_name}{}", variant.rust_ident);
    for field in &variant.fields {
        // Enum variant fields cannot carry visibility qualifiers (E0449).
        write_field(w, field, &nested_parent, common, false);
    }
    w.dedent();
    w.line("},");
}

// ── Untagged union ───────────────────────────────────────────────────────────

fn write_untagged_union(
    w: &mut RustWriter,
    u: &UntaggedUnionDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Hoist nested structured field types.
    let mut nested = Vec::new();
    collect_nested_from_fields(&u.fields, &u.name.0, &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &u.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    w.line("#[serde(deny_unknown_fields)]");
    w.line(&format!("pub struct {} {{", u.name.0));
    w.indent();
    // Render fields exactly as the IR carries them — outer `required` fields
    // stay non-Optional, xor_group members are Optional. The IR's
    // `lower_untagged_union` already enforced this split.
    for field in &u.fields {
        write_field(w, field, &u.name.0, common, true);
    }
    w.dedent();
    w.line("}");
    w.blank();
    w.line(&format!("impl {} {{", u.name.0));
    w.indent();
    w.line(
        "/// Enforce exactly-one-of presence across each XOR group declared in the IDL `oneOf`.",
    );
    w.line("pub fn validate(&self) -> Result<(), &'static str> {");
    w.indent();
    // The contract of `oneOf: [{required: [...]}, ...]` is "exactly one of the
    // entries matches". For our shape (each entry's `required` lists fields
    // that are otherwise optional in the type), this collapses to "exactly one
    // of the union of all xor-group fields is present". Compute the union once,
    // sum is_some() across it, require == 1.
    let mut union: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for group in &u.xor_groups {
        for name in group {
            union.insert(name.as_str());
        }
    }
    if !union.is_empty() {
        let checks = union
            .iter()
            .map(|name| format!("self.{}.is_some() as u8", sanitise_ident(name)))
            .collect::<Vec<_>>()
            .join(" + ");
        let union_str = union.iter().copied().collect::<Vec<_>>().join(", ");
        w.line(&format!(
            "if ({checks}) != 1 {{ return Err(\"exactly one of [{union_str}] is required\"); }}"
        ));
    }
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    Ok(())
}

// ── Recursive enum (filter family) ───────────────────────────────────────────

fn write_recursive(
    w: &mut RustWriter,
    r: &RecursiveEnumDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Emit the leaf type as a sibling so the enum can reference it by name.
    let leaf_name = format!("{}Leaf", r.name.0);
    let leaf_ty = renamed_to(&r.leaf, TypeName::new(&leaf_name));
    // The leaf may itself be a non-named type (Json, Ref, ...). In that case
    // we render it inline rather than emitting a top-level declaration.
    let leaf_inline = matches!(
        &*r.leaf,
        RustType::Json
            | RustType::Ref(_)
            | RustType::Primitive(_)
            | RustType::Vec(_)
            | RustType::Map(_)
            | RustType::Optional(_)
    );
    if !leaf_inline {
        write_type_decl(w, &leaf_ty, common)?;
        w.blank();
    }
    let leaf_render = if leaf_inline {
        render_inline_type(&r.leaf, common)
    } else {
        leaf_name
    };

    if let Some(doc) = &r.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    w.line("#[serde(untagged)]");
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", r.name.0));
    w.indent();
    w.line(&format!("Leaf({leaf_render}),"));
    w.line("And(Vec<Self>),");
    w.line("Or(Vec<Self>),");
    w.line("Not(Box<Self>),");
    w.dedent();
    w.line("}");
    Ok(())
}

// ── Field type rendering ─────────────────────────────────────────────────────

/// Render a field's `RustType` as the inline Rust source string used inside a
/// struct definition. Nested struct/enum/union types are referenced by their
/// hoisted sibling name (`<parent><field>`).
fn render_field_type(
    ty: &RustType,
    parent: &str,
    field: &str,
    common: &BTreeSet<String>,
) -> String {
    match ty {
        RustType::Primitive(p) => render_prim(*p).to_string(),
        RustType::Optional(inner) => {
            format!(
                "Option<{}>",
                render_field_type(inner, parent, field, common)
            )
        }
        RustType::Vec(inner) => {
            format!("Vec<{}>", render_field_type(inner, parent, field, common))
        }
        RustType::Map(inner) => {
            format!(
                "std::collections::BTreeMap<String, {}>",
                render_field_type(inner, parent, field, common)
            )
        }
        RustType::Json => "serde_json::Value".to_string(),
        RustType::Ref(name) => render_ref(name, common),
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            format!("{parent}{}", pascal_case(field))
        }
    }
}

/// Render a `RustType` as an inline expression — mirrors `render_field_type`
/// but without a parent/field context (used for top-level type aliases).
fn render_inline_type(ty: &RustType, common: &BTreeSet<String>) -> String {
    match ty {
        RustType::Primitive(p) => render_prim(*p).to_string(),
        RustType::Optional(inner) => format!("Option<{}>", render_inline_type(inner, common)),
        RustType::Vec(inner) => format!("Vec<{}>", render_inline_type(inner, common)),
        RustType::Map(inner) => format!(
            "std::collections::BTreeMap<String, {}>",
            render_inline_type(inner, common)
        ),
        RustType::Json => "serde_json::Value".to_string(),
        RustType::Ref(name) => render_ref(name, common),
        RustType::Struct(s) => s.name.0.clone(),
        RustType::Enum(e) => e.name.0.clone(),
        RustType::TaggedUnion(t) => t.name.0.clone(),
        RustType::UntaggedUnion(u) => u.name.0.clone(),
        RustType::Recursive(r) => r.name.0.clone(),
    }
}

fn render_ref(name: &TypeName, common: &BTreeSet<String>) -> String {
    if common.contains(&name.0) {
        format!("crate::generated::common::{}", name.0)
    } else {
        name.0.clone()
    }
}

fn render_prim(p: Prim) -> &'static str {
    match p {
        Prim::String => "String",
        Prim::I64 => "i64",
        Prim::U64 => "u64",
        Prim::F64 => "f64",
        Prim::Bool => "bool",
    }
}

/// Walk a list of struct fields and accumulate nested types that need their
/// own top-level declaration (`Struct`, `Enum`, `TaggedUnion`, `UntaggedUnion`,
/// `Recursive`). The returned `(name, type)` pairs are sibling declarations the
/// caller should emit before the enclosing parent. Names are formed as
/// `<parent><field-pascal>`.
fn collect_nested_from_fields(
    fields: &[StructField],
    parent: &str,
    out: &mut Vec<(String, RustType)>,
) {
    for field in fields {
        collect_nested(&field.ty, parent, &field.name, out);
    }
}

fn collect_nested(ty: &RustType, parent: &str, field: &str, out: &mut Vec<(String, RustType)>) {
    match ty {
        RustType::Optional(inner) | RustType::Vec(inner) | RustType::Map(inner) => {
            collect_nested(inner, parent, field, out);
        }
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            let name = format!("{parent}{}", pascal_case(field));
            out.push((name, ty.clone()));
        }
        RustType::Primitive(_) | RustType::Json | RustType::Ref(_) => {}
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn write_doc(w: &mut RustWriter, doc: &str) {
    for line in doc.lines() {
        w.line(&format!("/// {line}"));
    }
}

fn sanitise_ident(name: &str) -> String {
    // Replace dots/hyphens/spaces with underscores so the result is a valid
    // Rust identifier; if it collides with a keyword, prefix with `r#`.
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if rust_keyword(&s) {
        format!("r#{s}")
    } else {
        s
    }
}

fn is_valid_ident(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap_or(' ');
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

/// Returns true when serde's `rename_all = "snake_case"` mapping would
/// reproduce `wire` from `rust_ident`. When it does, no explicit `rename`
/// attribute is needed.
fn wire_matches_rename(wire: &str, rust_ident: &str) -> bool {
    // Convert PascalCase → snake_case and compare.
    let mut snake = String::with_capacity(rust_ident.len() + 4);
    for (i, c) in rust_ident.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                snake.push('_');
            }
            snake.extend(c.to_lowercase());
        } else {
            snake.push(c);
        }
    }
    snake == wire
}
