//! SDK emitter — writes Rust types into `crates/cairn-core/src/generated/`.
//!
//! Walks the `Document` IR and produces:
//!
//! * `mod.rs` — root re-exports.
//! * `verbs/mod.rs` — `VerbId` enum + capability/auth registry + capability list.
//! * `verbs/<id>.rs` (× 8) — per-verb `Args` and `Data` Rust types.
//! * `common/mod.rs` — shared types lifted from `common/*.json`.
//! * `errors/mod.rs` — `ErrorCode` enum.
//! * `envelope/mod.rs` — Request / Response / `SignedIntent` types.
//! * `status.rs`, `handshake.rs` — protocol prelude responses.
//!
//! Output bytes are deterministic per `Document` IR; snapshot tests in Phase 6
//! lock down the exact representation.

use std::collections::BTreeSet;
use std::path::PathBuf;

use super::fmt::RustWriter;
use super::ir::{
    Document, EnumDef, EnumVariant, PreludeDef, Prim, RecursiveEnumDef, RustType, StructDef,
    StructField, TaggedUnionDef, TaggedVariant, TypeName, UntaggedUnionDef, VerbDef, pascal_case,
};
use super::{CodegenError, GeneratedFile};

const HEADER: &str = "// @generated by cairn-codegen — DO NOT EDIT.\n";
const RUSTFMT_SKIP: &str = "#![cfg_attr(rustfmt, rustfmt_skip)]\n";
const ROOT: &str = "crates/cairn-core/src/generated";
const FILE_LINTS: &str = "#![allow(clippy::module_name_repetitions, clippy::large_enum_variant, clippy::missing_errors_doc, clippy::missing_panics_doc, clippy::doc_markdown, clippy::match_same_arms, clippy::cast_lossless, clippy::bool_to_int_with_if, missing_docs, dead_code)]\n";

/// Emit every SDK file declared by `doc`.
///
/// # Errors
/// Returns [`CodegenError::Emit`] when an IR construct cannot be rendered.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    let common_names: BTreeSet<String> = doc.common.keys().map(|t| t.0.clone()).collect();

    let mut out = Vec::new();
    out.push(emit_root_mod(doc));
    out.push(emit_verbs_mod(doc));
    for verb in &doc.verbs {
        out.push(emit_verb_file(verb, &common_names)?);
    }
    out.push(emit_common(doc, &common_names)?);
    out.push(emit_errors(doc));
    out.push(emit_envelope(doc, &common_names)?);
    for prelude in &doc.preludes {
        out.push(emit_prelude(prelude, &common_names)?);
    }
    Ok(out)
}

// ── Root re-exports ──────────────────────────────────────────────────────────

fn emit_root_mod(_doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Generated SDK surface for the cairn.mcp.v1 contract.");
    w.line("//!");
    w.line("//! Regenerate with `cargo run -p cairn-idl --bin cairn-codegen`.");
    w.blank();
    w.line("pub mod common;");
    w.line("pub mod envelope;");
    w.line("pub mod errors;");
    w.line("pub mod handshake;");
    w.line("pub mod status;");
    w.line("pub mod verbs;");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Verbs registry ───────────────────────────────────────────────────────────

fn emit_verbs_mod(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Verb registry. The eight P0 verbs in IDL order.");
    w.blank();
    for verb in &doc.verbs {
        w.line(&format!("pub mod {};", verb.id));
    }
    w.blank();
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
    w.line("#[non_exhaustive]");
    w.line("pub enum VerbId {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!("{},", pascal_case(&verb.id)));
    }
    w.dedent();
    w.line("}");
    w.blank();
    w.line("impl VerbId {");
    w.indent();
    w.line("#[must_use]");
    w.line("pub const fn as_str(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&verb.id),
            verb.id
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("#[must_use]");
    w.line("pub const fn capability(self) -> Option<&'static str> {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        match &verb.capability {
            Some(c) => w.line(&format!(
                "Self::{} => Some(\"{c}\"),",
                pascal_case(&verb.id)
            )),
            None => w.line(&format!("Self::{} => None,", pascal_case(&verb.id))),
        }
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("#[must_use]");
    w.line("pub const fn auth(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for verb in &doc.verbs {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&verb.id),
            verb.auth.as_str()
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("/// Every advertised capability string in declaration order.");
    w.line("pub const CAPABILITIES: &[&str] = &[");
    w.indent();
    for cap in &doc.capabilities {
        w.line(&format!("\"{cap}\","));
    }
    w.dedent();
    w.line("];");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("verbs/mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Per-verb file ────────────────────────────────────────────────────────────

fn emit_verb_file(
    verb: &VerbDef,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line(&format!(
        "//! Generated SDK types for the `{}` verb.",
        verb.id
    ));
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    // Sibling locally-defined types referenced from Args/Data (e.g. `Hit`).
    // Emit before Args/Data so source-order references resolve.
    for (name, ty) in &verb.local_types {
        let renamed = renamed_to(ty, name.clone());
        write_type_decl(&mut w, &renamed, common_names)?;
        w.blank();
    }
    let args_fallback = format!("{}Args", pascal_case(&verb.id));
    let data_fallback = format!("{}Data", pascal_case(&verb.id));
    write_named_type(&mut w, &verb.args, &args_fallback, common_names)?;
    w.blank();
    write_named_type(&mut w, &verb.data, &data_fallback, common_names)?;
    w.blank();
    let schema_path = format!(
        "../../../../cairn-mcp/src/generated/schemas/verbs/{}.json",
        verb.id
    );
    w.line(&format!(
        "pub const ARGS_SCHEMA: &[u8] = include_bytes!(\"{schema_path}\");"
    ));
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join(format!("verbs/{}.rs", verb.id)),
        bytes: w.finish().into_bytes(),
    })
}

// ── Common types ─────────────────────────────────────────────────────────────

fn emit_common(
    doc: &Document,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Common types shared across verbs (Ulid, Cursor, Identity, ...).");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();

    // BTreeMap iterates in sorted key order — deterministic.
    for (name, ty) in &doc.common {
        emit_common_entry(&mut w, name, ty, common_names)?;
        w.blank();
    }

    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join("common/mod.rs"),
        bytes: w.finish().into_bytes(),
    })
}

/// Emit one entry of the `common/` namespace. Primitive entries become
/// `pub type Foo = Bar;` (or newtype if aliasable to a primitive); structured
/// entries dispatch through `write_type_decl`.
fn emit_common_entry(
    w: &mut RustWriter,
    name: &TypeName,
    ty: &RustType,
    common_names: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Primitive(p) => {
            // Common primitives are exposed as transparent newtype wrappers
            // so the IDL-declared identity (e.g. `Ulid`) survives in the
            // type system.
            w.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]");
            w.line("#[serde(transparent)]");
            w.line(&format!("pub struct {}(pub {});", name.0, render_prim(*p)));
        }
        RustType::Json => {
            w.line(&format!("pub type {} = serde_json::Value;", name.0));
        }
        RustType::Map(inner) => {
            w.line(&format!(
                "pub type {} = std::collections::BTreeMap<String, {}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Vec(inner) => {
            w.line(&format!(
                "pub type {} = Vec<{}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Optional(inner) => {
            w.line(&format!(
                "pub type {} = Option<{}>;",
                name.0,
                render_inline_type(inner, common_names)
            ));
        }
        RustType::Ref(target) => {
            w.line(&format!(
                "pub type {} = {};",
                name.0,
                render_ref(target, common_names)
            ));
        }
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            // Force the IR's nominal name onto a clone of the IR variant so
            // top-level emission preserves the common-namespace identifier.
            let aliased = renamed_to(ty, name.clone());
            write_type_decl(w, &aliased, common_names)?;
        }
    }
    Ok(())
}

/// Return a copy of `ty` with its nominal name swapped to `name` (only the
/// outer Struct/Enum/Union — inner names are preserved).
fn renamed_to(ty: &RustType, name: TypeName) -> RustType {
    match ty.clone() {
        RustType::Struct(mut s) => {
            s.name = name;
            RustType::Struct(s)
        }
        RustType::Enum(mut e) => {
            e.name = name;
            RustType::Enum(e)
        }
        RustType::TaggedUnion(mut t) => {
            t.name = name;
            RustType::TaggedUnion(t)
        }
        RustType::UntaggedUnion(mut u) => {
            u.name = name;
            RustType::UntaggedUnion(u)
        }
        RustType::Recursive(mut r) => {
            r.name = name;
            RustType::Recursive(r)
        }
        other => other,
    }
}

// ── Errors enum ──────────────────────────────────────────────────────────────

fn emit_errors(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Errors enum lowered from errors/error.json.");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]");
    // No `rename_all` — IDL error codes are PascalCase wire constants and the
    // generated variant idents are already byte-identical to the wire form, so
    // serde's default naming serialises/deserialises them without any rename.
    w.line("#[non_exhaustive]");
    w.line("pub enum ErrorCode {");
    w.indent();
    for code in &doc.error_codes {
        w.line(&format!("{},", pascal_case(&code.code)));
    }
    w.dedent();
    w.line("}");
    w.blank();
    w.line("impl ErrorCode {");
    w.indent();
    w.line("#[must_use]");
    w.line("pub const fn as_str(self) -> &'static str {");
    w.indent();
    w.line("match self {");
    w.indent();
    for code in &doc.error_codes {
        w.line(&format!(
            "Self::{} => \"{}\",",
            pascal_case(&code.code),
            code.code
        ));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("errors/mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

// ── Envelope (request, response, signed_intent) ──────────────────────────────

fn emit_envelope(
    doc: &Document,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Request / response envelope types.");
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    for (name, ty) in &doc.envelope {
        if name.0 == "Request" {
            write_request_envelope(&mut w, doc, ty, common_names)?;
        } else if name.0 == "Response" {
            write_response_envelope(&mut w, doc, ty, common_names)?;
        } else {
            write_type_decl(&mut w, ty, common_names)?;
        }
        w.blank();
    }
    // SignedIntent's bespoke TryFrom uses `is_ulid_shape`. Emit the helper
    // once, at module scope, so any TryFrom validation can reference it.
    write_ulid_shape_helper(&mut w);
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join("envelope/mod.rs"),
        bytes: w.finish().into_bytes(),
    })
}

/// Bespoke emitter for the `Request` envelope.
///
/// The IDL request schema declares `args: object|array` and binds the
/// concrete shape via `allOf` if/then arms keyed off `verb`. The default
/// struct lowering drops those arms and types `args` as
/// `serde_json::Value`, so any wrong-shape payload would silently round-trip.
///
/// To restore the contract on the wire we emit:
///   * a typed `RequestArgs` enum (one variant per verb, holding the verb's
///     concrete `Args` type),
///   * the public `Request` struct using `RequestArgs` (Serialize-only),
///   * a hand-rolled `Deserialize` that goes through a `RawRequest` shim,
///     enforces the `contract` literal, then dispatches `args` by `verb`.
#[allow(
    clippy::too_many_lines,
    reason = "single-pass emission keeps the bespoke envelope dispatch in one place"
)]
fn write_request_envelope(
    w: &mut RustWriter,
    doc: &Document,
    ty: &RustType,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Pull the field list out of the lowered Request struct so any future
    // schema additions (signed_intent, contract, ...) flow through without a
    // bespoke field list to maintain.
    let RustType::Struct(s) = ty else {
        return Err(CodegenError::Emit(
            "envelope/Request expected to lower to a Struct".to_string(),
        ));
    };

    // Emit nested structured types in the fields first (e.g. the `RequestVerb`
    // enum hoisted from the `verb` field). Same convention `write_struct` uses.
    let mut nested = Vec::new();
    collect_nested_from_fields(&s.fields, "Request", &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    // Variants enumerate every verb in IDL order — same order the IR carries.
    // Each variant wraps `crate::generated::verbs::<id>::<Pascal>Args`.
    w.line("/// Per-verb request payload, dispatched on `Request.verb` at deserialize time.");
    w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    w.line("#[serde(untagged)]");
    w.line("#[non_exhaustive]");
    w.line("pub enum RequestArgs {");
    w.indent();
    for verb in &doc.verbs {
        let pascal = pascal_case(&verb.id);
        w.line(&format!(
            "{pascal}(crate::generated::verbs::{}::{pascal}Args),",
            verb.id
        ));
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Public struct — Serialize only; Deserialize is hand-rolled below.
    if let Some(doc_str) = &s.doc {
        write_doc(w, doc_str);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    if s.deny_unknown_fields {
        w.line("#[serde(deny_unknown_fields)]");
    }
    w.line("pub struct Request {");
    w.indent();
    for field in &s.fields {
        if field.name == "args" {
            // Override `args` to the typed enum.
            if let Some(d) = &field.doc {
                write_doc(w, d);
            }
            w.line("pub args: RequestArgs,");
        } else {
            write_field(w, field, "Request", common, true);
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Private raw shim — same fields as the public struct, but `args` is an
    // opaque `serde_json::Value` so the dispatch happens after the verb has
    // been parsed.
    w.line("#[derive(Deserialize)]");
    w.line("#[serde(deny_unknown_fields)]");
    w.line("struct RawRequest {");
    w.indent();
    for field in &s.fields {
        if field.name == "args" {
            w.line("args: serde_json::Value,");
        } else {
            // Raw shim is Deserialize-only; pass `serializing = false`.
            write_field_inner(w, field, "Request", common, false, false);
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Hand-rolled Deserialize: parse the shim, enforce contract literal,
    // then dispatch args by verb.
    w.line("impl<'de> ::serde::Deserialize<'de> for Request {");
    w.indent();
    w.line("fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>");
    w.line("where D: ::serde::Deserializer<'de> {");
    w.indent();
    w.line("let raw = RawRequest::deserialize(deserializer)?;");
    w.line(&format!("if raw.contract != \"{}\" {{", doc.contract));
    w.indent();
    w.line(&format!(
        "return Err(::serde::de::Error::custom(format!(\"contract: expected \\\"{}\\\", got {{:?}}\", raw.contract)));",
        doc.contract
    ));
    w.dedent();
    w.line("}");
    w.line("let args = match raw.verb {");
    w.indent();
    for verb in &doc.verbs {
        let pascal = pascal_case(&verb.id);
        w.line(&format!("RequestVerb::{pascal} => RequestArgs::{pascal}("));
        w.indent();
        w.line(&format!(
            "<crate::generated::verbs::{}::{pascal}Args as ::serde::Deserialize>::deserialize(raw.args).map_err(::serde::de::Error::custom)?",
            verb.id
        ));
        w.dedent();
        w.line("),");
    }
    w.dedent();
    w.line("};");
    w.line("Ok(Self {");
    w.indent();
    for field in &s.fields {
        let ident = sanitise_ident(&field.name);
        if field.name == "args" {
            w.line("args,");
        } else {
            w.line(&format!("{ident}: raw.{ident},"));
        }
    }
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    Ok(())
}

/// Bespoke emitter for the `Response` envelope.
///
/// The IDL response schema declares `data: object|array` and binds the
/// concrete shape per-verb via allOf if/then arms, plus four cross-cutting
/// invariants:
///   * status=committed ⟹ data present, error absent
///   * status∈{rejected,aborted} ⟹ error present, data absent
///   * verb=retrieve + status=committed ⟹ target present
///   * verb≠retrieve ⟹ target absent
///
/// The default Struct lowering drops every arm, so a malformed response
/// (e.g. `status=committed` without data, or non-retrieve with a stray
/// `target`) silently round-trips. We dispatch `data` by verb (typed) and
/// enforce the four invariants in a hand-rolled Deserialize.
///
/// Retrieve sub-dispatch by target (DataRecord vs DataSession vs ...) is
/// deferred — the per-target Data variants live in `verbs/retrieve.rs` as
/// untyped Json today, and pulling them through here would add 6 more
/// variants and a second discriminator. Tracked as a follow-up; the four
/// invariants below catch the load-bearing structural mistakes the
/// adversarial review surfaced.
#[allow(
    clippy::too_many_lines,
    reason = "single-pass emission keeps the bespoke envelope dispatch in one place"
)]
fn write_response_envelope(
    w: &mut RustWriter,
    doc: &Document,
    ty: &RustType,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    let RustType::Struct(s) = ty else {
        return Err(CodegenError::Emit(
            "envelope/Response expected to lower to a Struct".to_string(),
        ));
    };

    // Hoist nested types (ResponseStatus, ResponseTarget, ResponseVerb,
    // ResponsePolicyTrace, ...) the same way `write_struct` does.
    let mut nested = Vec::new();
    collect_nested_from_fields(&s.fields, "Response", &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    // Typed per-verb data dispatch. Each variant wraps the verb's Data type
    // (`crate::generated::verbs::<id>::<Pascal>Data`). The `unknown` verb
    // (UnknownVerb sentinel) carries no data — there is no `verbs/unknown.rs`.
    w.line("/// Per-verb response payload, dispatched on `Response.verb` at deserialize time.");
    w.line("///");
    w.line("/// Retrieve currently lands as opaque JSON; per-target sub-dispatch");
    w.line("/// (`DataRecord` vs `DataSession` vs ...) is a follow-up.");
    w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    w.line("#[serde(untagged)]");
    w.line("#[non_exhaustive]");
    w.line("pub enum ResponseData {");
    w.indent();
    for verb in &doc.verbs {
        let pascal = pascal_case(&verb.id);
        if verb.id == "retrieve" {
            // Retrieve's `Data` is itself a oneOf over six sub-types. Until
            // the sub-dispatch lands, surface it as raw JSON so the verb
            // layer can route on `target` after the structural checks pass.
            w.line(&format!("{pascal}(serde_json::Value),"));
        } else {
            w.line(&format!(
                "{pascal}(crate::generated::verbs::{}::{pascal}Data),",
                verb.id
            ));
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Public struct — Serialize-derived, Deserialize hand-rolled below.
    if let Some(doc_str) = &s.doc {
        write_doc(w, doc_str);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    if s.deny_unknown_fields {
        w.line("#[serde(deny_unknown_fields)]");
    }
    w.line("pub struct Response {");
    w.indent();
    for field in &s.fields {
        if field.name == "data" {
            if let Some(d) = &field.doc {
                write_doc(w, d);
            }
            w.line("#[serde(default, skip_serializing_if = \"Option::is_none\")]");
            w.line("pub data: Option<ResponseData>,");
        } else {
            write_field(w, field, "Response", common, true);
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Private raw shim mirrors the public struct but keeps `data` as
    // serde_json::Value so dispatch happens after `verb` and the four
    // structural invariants are checked.
    w.line("#[derive(Deserialize)]");
    w.line("#[serde(deny_unknown_fields)]");
    w.line("struct RawResponse {");
    w.indent();
    for field in &s.fields {
        if field.name == "data" {
            w.line("#[serde(default)]");
            w.line("data: Option<serde_json::Value>,");
        } else {
            write_field_inner(w, field, "Response", common, false, false);
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Hand-rolled Deserialize: contract literal, status/data/error/target
    // invariants, then per-verb data dispatch.
    w.line("impl<'de> ::serde::Deserialize<'de> for Response {");
    w.indent();
    w.line("fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>");
    w.line("where D: ::serde::Deserializer<'de> {");
    w.indent();
    w.line("let raw = RawResponse::deserialize(deserializer)?;");
    w.line(&format!("if raw.contract != \"{}\" {{", doc.contract));
    w.indent();
    w.line(&format!(
        "return Err(::serde::de::Error::custom(format!(\"contract: expected \\\"{}\\\", got {{:?}}\", raw.contract)));",
        doc.contract
    ));
    w.dedent();
    w.line("}");
    // Invariant: committed ⟹ data present, error absent.
    w.line("if matches!(raw.status, ResponseStatus::Committed) {");
    w.indent();
    w.line(
        "if raw.data.is_none() { return Err(::serde::de::Error::custom(\"status=committed requires data\")); }",
    );
    w.line(
        "if raw.error.is_some() { return Err(::serde::de::Error::custom(\"status=committed forbids error\")); }",
    );
    w.dedent();
    w.line("}");
    // Invariant: rejected/aborted ⟹ error present, data absent.
    w.line("if matches!(raw.status, ResponseStatus::Rejected | ResponseStatus::Aborted) {");
    w.indent();
    w.line(
        "if raw.error.is_none() { return Err(::serde::de::Error::custom(\"status=rejected|aborted requires error\")); }",
    );
    w.line(
        "if raw.data.is_some() { return Err(::serde::de::Error::custom(\"status=rejected|aborted forbids data\")); }",
    );
    w.dedent();
    w.line("}");
    // Invariant: verb=retrieve + committed ⟹ target present.
    w.line(
        "if matches!(raw.verb, ResponseVerb::Retrieve) && matches!(raw.status, ResponseStatus::Committed) && raw.target.is_none() {",
    );
    w.indent();
    w.line(
        "return Err(::serde::de::Error::custom(\"verb=retrieve + status=committed requires target\"));",
    );
    w.dedent();
    w.line("}");
    // Invariant: verb≠retrieve ⟹ target absent.
    w.line("if !matches!(raw.verb, ResponseVerb::Retrieve) && raw.target.is_some() {");
    w.indent();
    w.line(
        "return Err(::serde::de::Error::custom(\"target is retrieve-only — forbidden for other verbs\"));",
    );
    w.dedent();
    w.line("}");
    // Per-verb data dispatch. Skipped on rejected/aborted (data was just
    // proven None above).
    w.line("let data = if let Some(payload) = raw.data {");
    w.indent();
    w.line("Some(match raw.verb {");
    w.indent();
    for verb in &doc.verbs {
        let pascal = pascal_case(&verb.id);
        if verb.id == "retrieve" {
            // Retrieve sub-dispatch deferred — accept opaque JSON.
            w.line(&format!(
                "ResponseVerb::{pascal} => ResponseData::{pascal}(payload),"
            ));
        } else {
            w.line(&format!(
                "ResponseVerb::{pascal} => ResponseData::{pascal}("
            ));
            w.indent();
            w.line(&format!(
                "<crate::generated::verbs::{}::{pascal}Data as ::serde::Deserialize>::deserialize(payload).map_err(::serde::de::Error::custom)?",
                verb.id
            ));
            w.dedent();
            w.line("),");
        }
    }
    // The `unknown` sentinel verb only appears on rejected responses (per
    // the IDL UnknownVerb binding); the rejected path above already proved
    // data is None, so this match arm is unreachable. Reject defensively in
    // case the caller violates that invariant on the wire.
    w.line(
        "ResponseVerb::Unknown => return Err(::serde::de::Error::custom(\"verb=unknown is rejected-only and cannot carry data\")),",
    );
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("} else { None };");
    w.line("Ok(Self {");
    w.indent();
    for field in &s.fields {
        let ident = sanitise_ident(&field.name);
        if field.name == "data" {
            w.line("data,");
        } else {
            w.line(&format!("{ident}: raw.{ident},"));
        }
    }
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    Ok(())
}

// ── Preludes ─────────────────────────────────────────────────────────────────

fn emit_prelude(
    prelude: &PreludeDef,
    common_names: &BTreeSet<String>,
) -> Result<GeneratedFile, CodegenError> {
    let mut w = RustWriter::new();
    w.raw(HEADER);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line(&format!(
        "//! Generated SDK type for the `{}` prelude.",
        prelude.id
    ));
    w.blank();
    w.line("use serde::{Deserialize, Serialize};");
    w.blank();
    let fallback = format!("{}Response", pascal_case(&prelude.id));
    write_named_type(&mut w, &prelude.response, &fallback, common_names)?;
    w.blank();
    let schema_path = format!(
        "../../../cairn-mcp/src/generated/schemas/prelude/{}.json",
        prelude.id
    );
    w.line(&format!(
        "pub const SCHEMA: &[u8] = include_bytes!(\"{schema_path}\");"
    ));
    Ok(GeneratedFile {
        path: PathBuf::from(ROOT).join(format!("{}.rs", prelude.id)),
        bytes: w.finish().into_bytes(),
    })
}

// ── Top-level type declaration writer ────────────────────────────────────────

/// Walk a `RustType` and emit a top-level Rust declaration. Nested types are
/// flattened into siblings so the file stays a flat module. (Recursive on
/// nested struct fields where the field type is itself a Struct/Enum/etc.)
fn write_type_decl(
    w: &mut RustWriter,
    ty: &RustType,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Struct(s) => write_struct(w, s, common),
        RustType::Enum(e) => {
            write_enum(w, e);
            Ok(())
        }
        RustType::TaggedUnion(t) => write_tagged_union(w, t, common),
        RustType::UntaggedUnion(u) => write_untagged_union(w, u, common),
        RustType::Recursive(r) => write_recursive(w, r, common),
        // For top-level emission, scalar variants get wrapped in a tiny
        // module-level newtype so they are addressable. In practice the IR
        // never lands here at the verb-file level — the verb's Args/Data is
        // always one of the declarable variants above.
        other => Err(CodegenError::Emit(format!(
            "write_type_decl: cannot emit non-named type at top level: {other:?}"
        ))),
    }
}

/// Like `write_type_decl`, but accepts an explicit fallback name to use when
/// the IR variant doesn't carry one (Json, Primitive, Vec, ...). Named
/// variants (Struct/Enum/...) are emitted as-is — the existing IR name wins
/// over the fallback.
fn write_named_type(
    w: &mut RustWriter,
    ty: &RustType,
    fallback: &str,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    match ty {
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => write_type_decl(w, ty, common),
        RustType::Primitive(p) => {
            w.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]");
            w.line("#[serde(transparent)]");
            w.line(&format!("pub struct {fallback}(pub {});", render_prim(*p)));
            Ok(())
        }
        RustType::Json => {
            w.line(&format!("pub type {fallback} = serde_json::Value;"));
            Ok(())
        }
        RustType::Vec(inner) => {
            w.line(&format!(
                "pub type {fallback} = Vec<{}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Map(inner) => {
            w.line(&format!(
                "pub type {fallback} = std::collections::BTreeMap<String, {}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Optional(inner) => {
            w.line(&format!(
                "pub type {fallback} = Option<{}>;",
                render_inline_type(inner, common)
            ));
            Ok(())
        }
        RustType::Ref(name) => {
            w.line(&format!(
                "pub type {fallback} = {};",
                render_ref(name, common)
            ));
            Ok(())
        }
    }
}

// ── Struct ───────────────────────────────────────────────────────────────────

fn write_struct(
    w: &mut RustWriter,
    s: &StructDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Emit any nested structured types in the fields *first* so the parent
    // declaration's references resolve in source order.
    let mut nested = Vec::new();
    collect_nested_from_fields(&s.fields, &s.name.0, &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &s.doc {
        write_doc(w, doc);
    }
    // When the struct carries a presence-of-anyOf constraint, derive only
    // Serialize on the public type and hand-roll Deserialize via a private
    // Raw companion so the constraint becomes a wire-level invariant.
    let derive_deserialize = s.any_of_required.is_none();
    if derive_deserialize {
        w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    } else {
        w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    }
    if s.deny_unknown_fields {
        w.line("#[serde(deny_unknown_fields)]");
    }
    w.line(&format!("pub struct {} {{", s.name.0));
    w.indent();
    for field in &s.fields {
        write_field(w, field, &s.name.0, common, true);
    }
    w.dedent();
    w.line("}");

    if let Some(any_of) = &s.any_of_required {
        w.blank();
        write_struct_any_of_companion(w, s, common, any_of);
    }
    Ok(())
}

/// Emit the `Raw<Name>` companion + `TryFrom` + hand-rolled `Deserialize`
/// for a struct with an `any_of_required` presence constraint. The shape
/// mirrors the untagged-union path: a private deserialise-only mirror, a
/// `TryFrom` that runs the presence check, and a `Deserialize` that funnels
/// every parse through `TryFrom`.
fn write_struct_any_of_companion(
    w: &mut RustWriter,
    s: &StructDef,
    common: &BTreeSet<String>,
    any_of: &[String],
) {
    let raw_name = format!("Raw{}", s.name.0);

    w.line("#[derive(Deserialize)]");
    if s.deny_unknown_fields {
        w.line("#[serde(deny_unknown_fields)]");
    }
    w.line(&format!("struct {raw_name} {{"));
    w.indent();
    for field in &s.fields {
        write_field_inner(w, field, &s.name.0, common, false, false);
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!(
        "impl ::core::convert::TryFrom<{raw_name}> for {} {{",
        s.name.0
    ));
    w.indent();
    w.line("type Error = &'static str;");
    w.line(&format!(
        "fn try_from(raw: {raw_name}) -> Result<Self, Self::Error> {{"
    ));
    w.indent();
    let presence_checks = any_of
        .iter()
        .map(|n| format!("raw.{}.is_some()", sanitise_ident(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    let names = any_of.join(", ");
    w.line(&format!(
        "if !({presence_checks}) {{ return Err(\"at least one of [{names}] is required\"); }}"
    ));
    // Type-specific extra invariants. The IDL annotates ScopeFilter's
    // string fields with `minLength: 1` and array fields with `minItems: 1`.
    // The generic IR strips those, so without this hook
    // `{"tags": []}` and `{"user": ""}` slip through the presence check.
    if s.name.0 == "ScopeFilter" {
        write_scope_filter_extra_checks(w);
    }
    w.line("Ok(Self {");
    w.indent();
    for field in &s.fields {
        let ident = sanitise_ident(&field.name);
        w.line(&format!("{ident}: raw.{ident},"));
    }
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!(
        "impl<'de> ::serde::Deserialize<'de> for {} {{",
        s.name.0
    ));
    w.indent();
    w.line("fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>");
    w.line("where D: ::serde::Deserializer<'de> {");
    w.indent();
    w.line(&format!(
        "let raw = {raw_name}::deserialize(deserializer)?;"
    ));
    w.line("Self::try_from(raw).map_err(::serde::de::Error::custom)");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

fn write_field(
    w: &mut RustWriter,
    field: &StructField,
    parent_name: &str,
    common: &BTreeSet<String>,
    pub_qualifier: bool,
) {
    write_field_inner(w, field, parent_name, common, pub_qualifier, true);
}

/// Emit a struct field. `serializing` controls whether serialise-only attrs
/// (`skip_serializing_if`) are included — set to `false` when the host struct
/// derives only `Deserialize` (e.g. the private `Raw…` companion of an
/// untagged-union public type), so the generated code stays free of dead
/// attribute noise.
fn write_field_inner(
    w: &mut RustWriter,
    field: &StructField,
    parent_name: &str,
    common: &BTreeSet<String>,
    pub_qualifier: bool,
    serializing: bool,
) {
    if let Some(doc) = &field.doc {
        write_doc(w, doc);
    }
    let serde_name = if rust_keyword(&field.name) || !is_valid_ident(&field.name) {
        Some(field.name.clone())
    } else {
        None
    };
    if matches!(field.ty, RustType::Optional(_)) {
        if serializing {
            w.line("#[serde(default, skip_serializing_if = \"Option::is_none\")]");
        } else {
            w.line("#[serde(default)]");
        }
    }
    if let Some(name) = &serde_name {
        w.line(&format!("#[serde(rename = \"{name}\")]"));
    }
    let ident = sanitise_ident(&field.name);
    let ty_str = render_field_type(&field.ty, parent_name, &field.name, common);
    let prefix = if pub_qualifier { "pub " } else { "" };
    w.line(&format!("{prefix}{ident}: {ty_str},"));
}

// ── Enum (string enum) ───────────────────────────────────────────────────────

fn write_enum(w: &mut RustWriter, e: &EnumDef) {
    if let Some(doc) = &e.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]");
    if let Some(rename) = e.rename_all {
        w.line(&format!("#[serde(rename_all = \"{rename}\")]"));
    }
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", e.name.0));
    w.indent();
    for variant in &e.variants {
        write_enum_variant(w, variant);
    }
    w.dedent();
    w.line("}");
    if e.variants.iter().any(|v| v.capability.is_some()) {
        w.blank();
        w.line(&format!("impl {} {{", e.name.0));
        w.indent();
        w.line("/// Capability advertised by the IDL for the matched variant, or `None`.");
        w.line("#[must_use]");
        w.line("pub const fn capability(self) -> Option<&'static str> {");
        w.indent();
        w.line("match self {");
        w.indent();
        for variant in &e.variants {
            match &variant.capability {
                Some(cap) => w.line(&format!("Self::{} => Some(\"{cap}\"),", variant.rust_ident)),
                None => w.line(&format!("Self::{} => None,", variant.rust_ident)),
            }
        }
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }
}

fn write_enum_variant(w: &mut RustWriter, variant: &EnumVariant) {
    if let Some(doc) = &variant.doc {
        write_doc(w, doc);
    }
    // Serde's rename_all handles the wire mapping for snake_case identifiers,
    // but if the wire form contains characters that don't fit the rename rule
    // we attach an explicit rename.
    if !wire_matches_rename(&variant.wire, &variant.rust_ident) {
        w.line(&format!("#[serde(rename = \"{}\")]", variant.wire));
    }
    w.line(&format!("{},", variant.rust_ident));
}

// ── Tagged union ─────────────────────────────────────────────────────────────

fn write_tagged_union(
    w: &mut RustWriter,
    t: &TaggedUnionDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Hoist nested structured types referenced by variant fields.
    let mut nested = Vec::new();
    for variant in &t.variants {
        let parent = format!("{}{}", t.name.0, variant.rust_ident);
        collect_nested_from_fields(&variant.fields, &parent, &mut nested);
    }
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &t.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    w.line(&format!(
        "#[serde(tag = \"{}\", rename_all = \"snake_case\")]",
        t.discriminator
    ));
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", t.name.0));
    w.indent();
    for variant in &t.variants {
        write_tagged_variant(w, variant, &t.name.0, common);
    }
    w.dedent();
    w.line("}");
    if t.variants.iter().any(|v| v.capability.is_some()) {
        w.blank();
        w.line(&format!("impl {} {{", t.name.0));
        w.indent();
        w.line("/// Capability advertised by the IDL for the matched variant, or `None`.");
        w.line("#[must_use]");
        w.line("pub fn capability(&self) -> Option<&'static str> {");
        w.indent();
        w.line("match self {");
        w.indent();
        for variant in &t.variants {
            // Match arm pattern depends on whether the variant has fields.
            let arm = if variant.fields.is_empty() {
                format!("Self::{}", variant.rust_ident)
            } else {
                format!("Self::{} {{ .. }}", variant.rust_ident)
            };
            match &variant.capability {
                Some(cap) => w.line(&format!("{arm} => Some(\"{cap}\"),")),
                None => w.line(&format!("{arm} => None,")),
            }
        }
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }
    Ok(())
}

fn write_tagged_variant(
    w: &mut RustWriter,
    variant: &TaggedVariant,
    parent_name: &str,
    common: &BTreeSet<String>,
) {
    if let Some(doc) = &variant.doc {
        write_doc(w, doc);
    }
    if !wire_matches_rename(&variant.wire, &variant.rust_ident) {
        w.line(&format!("#[serde(rename = \"{}\")]", variant.wire));
    }
    if variant.fields.is_empty() {
        w.line(&format!("{},", variant.rust_ident));
        return;
    }
    w.line(&format!("{} {{", variant.rust_ident));
    w.indent();
    let nested_parent = format!("{parent_name}{}", variant.rust_ident);
    for field in &variant.fields {
        // Enum variant fields cannot carry visibility qualifiers (E0449).
        write_field(w, field, &nested_parent, common, false);
    }
    w.dedent();
    w.line("},");
}

// ── Untagged union ───────────────────────────────────────────────────────────

fn write_untagged_union(
    w: &mut RustWriter,
    u: &UntaggedUnionDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Hoist nested structured field types.
    let mut nested = Vec::new();
    collect_nested_from_fields(&u.fields, &u.name.0, &mut nested);
    for (sub_name, sub_ty) in &nested {
        let renamed = renamed_to(sub_ty, TypeName::new(sub_name));
        write_type_decl(w, &renamed, common)?;
        w.blank();
    }

    if let Some(doc) = &u.doc {
        write_doc(w, doc);
    }
    // Serialize derives directly off the public type. Deserialize is hand-written
    // below so the XOR contract is enforced at the deserialization boundary —
    // callers cannot construct an invalid value by parsing JSON.
    w.line("#[derive(Debug, Clone, PartialEq, Serialize)]");
    w.line(&format!("pub struct {} {{", u.name.0));
    w.indent();
    // Render fields exactly as the IR carries them — outer `required` fields
    // stay non-Optional, xor_group members are Optional. The IR's
    // `lower_untagged_union` already enforced this split.
    for field in &u.fields {
        write_field(w, field, &u.name.0, common, true);
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Compute the XOR field union once — used both by `validate()` and by the
    // `TryFrom` impl below. `BTreeSet` keeps a deterministic emission order.
    let mut union: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for group in &u.xor_groups {
        for name in group {
            union.insert(name.as_str());
        }
    }

    write_untagged_union_validate(w, &u.name.0, &union);
    w.blank();
    write_untagged_union_deserialize(w, u, common, &union);

    Ok(())
}

/// Emit the public `validate(&self)` method that callers building instances by
/// hand can use to self-check XOR membership before sending. Mirrors the
/// historic API; the deserialise path goes through [`write_untagged_union_deserialize`]
/// instead.
fn write_untagged_union_validate(
    w: &mut RustWriter,
    type_name: &str,
    union: &std::collections::BTreeSet<&str>,
) {
    w.line(&format!("impl {type_name} {{"));
    w.indent();
    w.line(
        "/// Enforce exactly-one-of presence across each XOR group declared in the IDL `oneOf`.",
    );
    w.line("pub fn validate(&self) -> Result<(), &'static str> {");
    w.indent();
    if !union.is_empty() {
        write_xor_check(w, "self", union);
    }
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

/// Emit the private `Raw<Name>` companion, the `TryFrom<Raw<Name>>` impl
/// (which performs the XOR check), and the hand-rolled `Deserialize` that
/// funnels every parse through `TryFrom`. This is what makes the XOR contract
/// load-bearing on the wire — without it, callers could deserialize an
/// invalid intent and only discover the problem at `validate()` call time.
fn write_untagged_union_deserialize(
    w: &mut RustWriter,
    u: &UntaggedUnionDef,
    common: &BTreeSet<String>,
    union: &std::collections::BTreeSet<&str>,
) {
    let raw_name = format!("Raw{}", u.name.0);

    // Private companion mirrors the public field shape but only derives Deserialize.
    w.line("#[derive(Deserialize)]");
    w.line("#[serde(deny_unknown_fields)]");
    w.line(&format!("struct {raw_name} {{"));
    w.indent();
    for field in &u.fields {
        // Raw is Deserialize-only — emit the serialise-stripped form so
        // `#[serde(skip_serializing_if = ...)]` doesn't dangle as dead noise.
        write_field_inner(w, field, &u.name.0, common, false, false);
    }
    w.dedent();
    w.line("}");
    w.blank();

    // TryFrom encapsulates validation + field move. Any future invariant
    // (e.g. cross-field constraints) can land here without disturbing the
    // Deserialize impl.
    w.line(&format!(
        "impl ::core::convert::TryFrom<{raw_name}> for {} {{",
        u.name.0
    ));
    w.indent();
    w.line("type Error = &'static str;");
    w.line(&format!(
        "fn try_from(raw: {raw_name}) -> Result<Self, Self::Error> {{"
    ));
    w.indent();
    if !union.is_empty() {
        write_xor_check(w, "raw", union);
    }
    // Type-specific extra invariants. The IDL annotates `SignedIntent` with
    // ULID/Identity/Nonce16Base64 patterns, key_version >= 1, sequence ≤
    // 2^53−1, chain_parents maxItems=64 + uniqueItems. The generic IR
    // doesn't carry those constraints so a TypeName match keeps the bespoke
    // checks here while leaving the codegen for other untagged unions
    // (IngestArgs, ...) untouched.
    if u.name.0 == "SignedIntent" {
        write_signed_intent_extra_checks(w);
    }
    w.line("Ok(Self {");
    w.indent();
    for field in &u.fields {
        let ident = sanitise_ident(&field.name);
        w.line(&format!("{ident}: raw.{ident},"));
    }
    w.dedent();
    w.line("})");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    // Hand-rolled Deserialize that funnels through TryFrom — guarantees the
    // XOR check happens at every parse boundary (JSON, MCP, CLI args, ...).
    w.line(&format!(
        "impl<'de> ::serde::Deserialize<'de> for {} {{",
        u.name.0
    ));
    w.indent();
    w.line("fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>");
    w.line("where D: ::serde::Deserializer<'de> {");
    w.indent();
    w.line(&format!(
        "let raw = {raw_name}::deserialize(deserializer)?;"
    ));
    w.line("Self::try_from(raw).map_err(::serde::de::Error::custom)");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

/// Emit bespoke field-level non-emptiness checks for `ScopeFilter`.
///
/// The IDL marks every string field with `minLength: 1` and every array
/// field with `minItems: 1`. Round-3 only added presence-of-anyOf, so
/// `{"tags": []}` and `{"user": ""}` slipped through. The validator here
/// rejects the empty-but-present values per the IDL.
fn write_scope_filter_extra_checks(w: &mut RustWriter) {
    // String fields: minLength: 1.
    for field in [
        "user",
        "agent",
        "tenant",
        "workspace",
        "entity",
        "session_id",
    ] {
        w.line(&format!("if let Some(v) = &raw.{field} {{"));
        w.indent();
        w.line(&format!(
            "if v.is_empty() {{ return Err(\"{field}: must not be empty\"); }}"
        ));
        w.dedent();
        w.line("}");
    }
    // Array fields: minItems: 1; array element strings (kind, tags) further
    // require minLength: 1 per the IDL's `items` block.
    for field in ["kind", "tags"] {
        w.line(&format!("if let Some(v) = &raw.{field} {{"));
        w.indent();
        w.line(&format!(
            "if v.is_empty() {{ return Err(\"{field}: must contain at least one item\"); }}"
        ));
        w.line("for item in v {");
        w.indent();
        w.line(&format!(
            "if item.is_empty() {{ return Err(\"{field}: items must not be empty\"); }}"
        ));
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }
    // record_ids: minItems: 1; element shape already enforced via Ulid newtype
    // ($ref to primitives.json#/$defs/Ulid). The IDL's pattern is checked at
    // the SignedIntent layer, not here — this matches the round-3 scope of
    // ScopeFilter (presence + non-emptiness).
    w.line("if let Some(v) = &raw.record_ids {");
    w.indent();
    w.line("if v.is_empty() { return Err(\"record_ids: must contain at least one item\"); }");
    w.dedent();
    w.line("}");
}

/// Emit bespoke field-level validation for `SignedIntent`.
///
/// The generic IR strips JSON Schema's `pattern` / `format` / numeric bounds /
/// `uniqueItems` constraints, but the signed-intent envelope is the auth
/// substrate — every field carries a load-bearing shape. We special-case it
/// here so the same TryFrom path that already enforces the XOR also rejects
/// malformed crypto/identity payloads at deserialize time.
///
/// Checks emitted:
/// * `sequence <= 9_007_199_254_740_991` (JSON safe-integer cap from IDL).
/// * `key_version >= 1` (IDL `minimum: 1`).
/// * `chain_parents.len() <= 64` and unique entries (IDL `maxItems` /
///   `uniqueItems`).
/// * `operation_id`, every `chain_parents[i]`: ULID alphabet check (26 chars,
///   Crockford base32 — `^[0-9A-HJKMNP-TV-Z]{26}$`).
/// * `nonce` and `server_challenge`: 16-byte base64 alphabet + length
///   (`^[A-Za-z0-9+/]{21}[AQgw](==)?$`).
/// * `signature`: `ed25519:` prefix + 128 lowercase hex chars
///   (`^ed25519:[0-9a-f]{128}$`).
/// * `target_hash`: `sha256:` prefix + 64 lowercase hex chars
///   (`^sha256:[0-9a-f]{64}$`).
/// * `issuer`: identity prefix (`agt:`/`usr:`/`snr:`) + non-empty body in
///   the alphabet `[A-Za-z0-9._:-]+` (`^(agt|usr|snr):[A-Za-z0-9._:-]+$`).
/// * `scope.tenant`/`workspace`/`entity`: `minLength: 1`.
/// * `issued_at`/`expires_at`: minimal RFC-3339 date-time shape — `len >= 20`,
///   ASCII-only, `-` at positions 4/7, `T` at 10, `:` at 13/16, second-pair
///   digits, and a final `Z` or `+/-HH:MM` offset. Stricter validation lands
///   when a date-time parser ships in the verb layer; this catches obviously
///   malformed strings without pulling `chrono` into `cairn-core`.
fn write_signed_intent_extra_checks(w: &mut RustWriter) {
    // sequence bound — JSON safe-integer cap from the IDL.
    w.line("if let Some(seq) = raw.sequence {");
    w.indent();
    w.line("if seq > 9_007_199_254_740_991_u64 { return Err(\"sequence: exceeds JSON safe-integer cap (2^53 - 1)\"); }");
    w.dedent();
    w.line("}");
    // key_version >= 1.
    w.line("if raw.key_version < 1 { return Err(\"key_version: must be >= 1\"); }");
    // chain_parents: bounded and unique.
    w.line(
        "if raw.chain_parents.len() > 64 { return Err(\"chain_parents: exceeds maxItems (64)\"); }",
    );
    w.line("{");
    w.indent();
    w.line("let mut seen = ::std::collections::BTreeSet::new();");
    w.line("for parent in &raw.chain_parents {");
    w.indent();
    w.line("if !seen.insert(parent.0.clone()) { return Err(\"chain_parents: must be unique\"); }");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    // ULID shape on operation_id and chain_parents — 26 chars, Crockford
    // base32 (no I, L, O, U). Hand-rolled to avoid pulling regex into core.
    w.line("if !is_ulid_shape(&raw.operation_id.0) { return Err(\"operation_id: must be a Crockford-base32 ULID\"); }");
    w.line("for parent in &raw.chain_parents {");
    w.indent();
    w.line("if !is_ulid_shape(&parent.0) { return Err(\"chain_parents[*]: must be a Crockford-base32 ULID\"); }");
    w.dedent();
    w.line("}");
    // Nonce16Base64 shape on nonce + (when present) server_challenge.
    w.line("if !is_nonce16_base64(&raw.nonce.0) { return Err(\"nonce: must be a 16-byte base64 nonce (22 chars [+ '==' padding] with [AQgw] tail)\"); }");
    w.line("if let Some(c) = &raw.server_challenge {");
    w.indent();
    w.line("if !is_nonce16_base64(&c.0) { return Err(\"server_challenge: must be a 16-byte base64 nonce (22 chars [+ '==' padding] with [AQgw] tail)\"); }");
    w.dedent();
    w.line("}");
    // Ed25519 signature prefix + 128 lowercase hex chars.
    w.line("if !is_ed25519_signature(&raw.signature.0) { return Err(\"signature: must be \\\"ed25519:\\\" + 128 lowercase hex chars\"); }");
    // SHA-256 target_hash prefix + 64 lowercase hex chars.
    w.line("if !is_sha256_target_hash(&raw.target_hash) { return Err(\"target_hash: must be \\\"sha256:\\\" + 64 lowercase hex chars\"); }");
    // Identity prefix on issuer.
    w.line("if !is_identity(&raw.issuer.0) { return Err(\"issuer: must start with one of [agt:, usr:, snr:] followed by a non-empty body in [A-Za-z0-9._:-]\"); }");
    // Scope inner string fields — minLength: 1 per IDL.
    w.line("if raw.scope.tenant.is_empty() { return Err(\"scope.tenant: must not be empty\"); }");
    w.line(
        "if raw.scope.workspace.is_empty() { return Err(\"scope.workspace: must not be empty\"); }",
    );
    w.line("if raw.scope.entity.is_empty() { return Err(\"scope.entity: must not be empty\"); }");
    // RFC-3339 date-time shape on issued_at / expires_at.
    w.line("if !is_rfc3339_datetime(&raw.issued_at) { return Err(\"issued_at: must be an RFC-3339 date-time (e.g. 2026-01-01T00:00:00Z)\"); }");
    w.line("if !is_rfc3339_datetime(&raw.expires_at) { return Err(\"expires_at: must be an RFC-3339 date-time (e.g. 2026-01-01T00:00:00Z)\"); }");
}

/// Emit the bespoke shape helpers used by SignedIntent's TryFrom impl
/// (`is_ulid_shape`, `is_nonce16_base64`, `is_ed25519_signature`,
/// `is_sha256_target_hash`, `is_identity`, `is_rfc3339_datetime`). All are
/// hand-rolled byte-level checks so we don't have to pull `regex` into
/// `cairn-core`. Emitted once at module scope.
fn write_ulid_shape_helper(w: &mut RustWriter) {
    w.line("/// Return true iff `s` is a valid Crockford base32 ULID — exactly 26 chars");
    w.line("/// from the alphabet `0123456789ABCDEFGHJKMNPQRSTVWXYZ` (no I, L, O, U).");
    w.line("fn is_ulid_shape(s: &str) -> bool {");
    w.indent();
    w.line("if s.len() != 26 { return false; }");
    w.line("s.bytes().all(|b| matches!(b,");
    w.indent();
    w.line("b'0'..=b'9' | b'A'..=b'H' | b'J' | b'K' | b'M' | b'N' | b'P'..=b'T' | b'V'..=b'Z'");
    w.dedent();
    w.line("))");
    w.dedent();
    w.line("}");
    w.blank();
    // Nonce16Base64: ^[A-Za-z0-9+/]{21}[AQgw](==)?$  — 22 significant chars
    // with the 22nd in [AQgw] (so trailing 4 bits are zero — canonical for
    // exactly 16 bytes), optional `==` padding.
    w.line("/// Return true iff `s` is a 16-byte base64 nonce: 22 significant chars");
    w.line("/// with the 22nd in `[AQgw]` (canonical 16-byte encoding) and optional `==` padding.");
    w.line("fn is_nonce16_base64(s: &str) -> bool {");
    w.indent();
    w.line("let bytes = s.as_bytes();");
    w.line("let (head, tail22, padded) = match bytes.len() {");
    w.indent();
    w.line("22 => (&bytes[..21], bytes[21], false),");
    w.line("24 => (&bytes[..21], bytes[21], true),");
    w.line("_ => return false,");
    w.dedent();
    w.line("};");
    w.line("if !head.iter().all(|b| matches!(b,");
    w.indent();
    w.line("b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'+' | b'/'");
    w.dedent();
    w.line(")) { return false; }");
    w.line("if !matches!(tail22, b'A' | b'Q' | b'g' | b'w') { return false; }");
    w.line("if padded && &bytes[22..] != b\"==\" { return false; }");
    w.line("true");
    w.dedent();
    w.line("}");
    w.blank();
    // Ed25519 signature: ^ed25519:[0-9a-f]{128}$
    w.line("/// Return true iff `s` matches `ed25519:` + exactly 128 lowercase hex chars.");
    w.line("fn is_ed25519_signature(s: &str) -> bool {");
    w.indent();
    w.line("let Some(tail) = s.strip_prefix(\"ed25519:\") else { return false; };");
    w.line("if tail.len() != 128 { return false; }");
    w.line("tail.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))");
    w.dedent();
    w.line("}");
    w.blank();
    // SHA-256 target hash: ^sha256:[0-9a-f]{64}$
    w.line("/// Return true iff `s` matches `sha256:` + exactly 64 lowercase hex chars.");
    w.line("fn is_sha256_target_hash(s: &str) -> bool {");
    w.indent();
    w.line("let Some(tail) = s.strip_prefix(\"sha256:\") else { return false; };");
    w.line("if tail.len() != 64 { return false; }");
    w.line("tail.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))");
    w.dedent();
    w.line("}");
    w.blank();
    // Identity: ^(agt|usr|snr):[A-Za-z0-9._:-]+$
    w.line("/// Return true iff `s` starts with `agt:`, `usr:`, or `snr:` followed by a");
    w.line("/// non-empty body in `[A-Za-z0-9._:-]`.");
    w.line("fn is_identity(s: &str) -> bool {");
    w.indent();
    w.line("let tail = if let Some(t) = s.strip_prefix(\"agt:\") { t }");
    w.line("    else if let Some(t) = s.strip_prefix(\"usr:\") { t }");
    w.line("    else if let Some(t) = s.strip_prefix(\"snr:\") { t }");
    w.line("    else { return false; };");
    w.line("if tail.is_empty() { return false; }");
    w.line("tail.bytes().all(|b| matches!(b,");
    w.indent();
    w.line("b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'.' | b'_' | b':' | b'-'");
    w.dedent();
    w.line("))");
    w.dedent();
    w.line("}");
    w.blank();
    // RFC-3339 date-time minimal shape:
    // YYYY-MM-DDTHH:MM:SS(.fraction)?(Z|±HH:MM)
    // We don't validate field ranges (month <= 12 etc.) — that belongs to a
    // dedicated parser. We catch the obvious shape mistakes (wrong separators,
    // non-ASCII, missing offset) which is what the IDL `format: date-time`
    // hint protects against in practice.
    w.line("/// Return true iff `s` looks like an RFC-3339 date-time:");
    w.line("/// `YYYY-MM-DDTHH:MM:SS(.fraction)?(Z|+HH:MM|-HH:MM)`. ASCII-only,");
    w.line("/// length >= 20, separators at fixed positions, digits everywhere else");
    w.line("/// in the date / time core. Field-range checks (month <= 12, etc.) are");
    w.line("/// out of scope — a dedicated parser owns those.");
    w.line("fn is_rfc3339_datetime(s: &str) -> bool {");
    w.indent();
    w.line("if !s.is_ascii() { return false; }");
    w.line("let b = s.as_bytes();");
    w.line("if b.len() < 20 { return false; }");
    w.line("// YYYY-MM-DDTHH:MM:SS");
    w.line("let digits = [0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18];");
    w.line("for &i in &digits { if !b[i].is_ascii_digit() { return false; } }");
    w.line("if b[4] != b'-' || b[7] != b'-' { return false; }");
    w.line("if b[10] != b'T' && b[10] != b't' { return false; }");
    w.line("if b[13] != b':' || b[16] != b':' { return false; }");
    w.line("// Optional fractional seconds + mandatory offset (Z or ±HH:MM).");
    w.line("let mut idx = 19;");
    w.line("if idx < b.len() && b[idx] == b'.' {");
    w.indent();
    w.line("idx += 1;");
    w.line("let frac_start = idx;");
    w.line("while idx < b.len() && b[idx].is_ascii_digit() { idx += 1; }");
    w.line("if idx == frac_start { return false; }");
    w.dedent();
    w.line("}");
    w.line("if idx >= b.len() { return false; }");
    w.line("match b[idx] {");
    w.indent();
    w.line("b'Z' | b'z' => idx + 1 == b.len(),");
    w.line("b'+' | b'-' => {");
    w.indent();
    w.line("// ±HH:MM = 6 more bytes.");
    w.line("if idx + 6 != b.len() { return false; }");
    w.line("b[idx + 1].is_ascii_digit() && b[idx + 2].is_ascii_digit()");
    w.line("    && b[idx + 3] == b':'");
    w.line("    && b[idx + 4].is_ascii_digit() && b[idx + 5].is_ascii_digit()");
    w.dedent();
    w.line("}");
    w.line("_ => false,");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

/// Emit the `if (a.is_some() as u8 + b.is_some() as u8 + ...) != 1 { return Err(...) }`
/// guard shared between `validate(&self)` and `TryFrom<Raw…>`. `receiver` is the
/// expression-level prefix (`self` for the public method, `raw` for the
/// `TryFrom`).
fn write_xor_check(w: &mut RustWriter, receiver: &str, union: &std::collections::BTreeSet<&str>) {
    let checks = union
        .iter()
        .map(|name| format!("{receiver}.{}.is_some() as u8", sanitise_ident(name)))
        .collect::<Vec<_>>()
        .join(" + ");
    let union_str = union.iter().copied().collect::<Vec<_>>().join(", ");
    w.line(&format!(
        "if ({checks}) != 1 {{ return Err(\"exactly one of [{union_str}] is required\"); }}"
    ));
}

// ── Recursive enum (filter family) ───────────────────────────────────────────

fn write_recursive(
    w: &mut RustWriter,
    r: &RecursiveEnumDef,
    common: &BTreeSet<String>,
) -> Result<(), CodegenError> {
    // Emit the leaf type as a sibling so the enum can reference it by name.
    let leaf_name = format!("{}Leaf", r.name.0);
    let leaf_ty = renamed_to(&r.leaf, TypeName::new(&leaf_name));
    // The leaf may itself be a non-named type (Json, Ref, ...). In that case
    // we render it inline rather than emitting a top-level declaration.
    let leaf_inline = matches!(
        &*r.leaf,
        RustType::Json
            | RustType::Ref(_)
            | RustType::Primitive(_)
            | RustType::Vec(_)
            | RustType::Map(_)
            | RustType::Optional(_)
    );
    if !leaf_inline {
        write_type_decl(w, &leaf_ty, common)?;
        w.blank();
    }
    let leaf_render = if leaf_inline {
        render_inline_type(&r.leaf, common)
    } else {
        leaf_name
    };

    if let Some(doc) = &r.doc {
        write_doc(w, doc);
    }
    w.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
    w.line("#[serde(untagged)]");
    w.line("#[non_exhaustive]");
    w.line(&format!("pub enum {} {{", r.name.0));
    w.indent();
    // The IDL wire shape is `{"and": [...]}`, `{"or": [...]}`, `{"not": <node>}`,
    // or a leaf object. With `#[serde(untagged)]` serde tries variants in source
    // order, so the structured arms come *first* — otherwise a `Leaf(serde_json::Value)`
    // alternative would greedily accept any JSON object and the boolean operators
    // would become unreachable on the deserialise side.
    //
    // Each operator is a struct variant whose single field name matches the IDL
    // key. Untagged struct variants serialise as `{"<key>": <value>}`, which is
    // exactly the wire form filter_and_L*/filter_or_L*/filter_not_L* declare.
    w.line("And { and: Vec<Self> },");
    w.line("Or { or: Vec<Self> },");
    w.line("Not { not: Box<Self> },");
    w.line(&format!("Leaf({leaf_render}),"));
    w.dedent();
    w.line("}");
    Ok(())
}

// ── Field type rendering ─────────────────────────────────────────────────────

/// Render a field's `RustType` as the inline Rust source string used inside a
/// struct definition. Nested struct/enum/union types are referenced by their
/// hoisted sibling name (`<parent><field>`).
fn render_field_type(
    ty: &RustType,
    parent: &str,
    field: &str,
    common: &BTreeSet<String>,
) -> String {
    match ty {
        RustType::Primitive(p) => render_prim(*p).to_string(),
        RustType::Optional(inner) => {
            format!(
                "Option<{}>",
                render_field_type(inner, parent, field, common)
            )
        }
        RustType::Vec(inner) => {
            format!("Vec<{}>", render_field_type(inner, parent, field, common))
        }
        RustType::Map(inner) => {
            format!(
                "std::collections::BTreeMap<String, {}>",
                render_field_type(inner, parent, field, common)
            )
        }
        RustType::Json => "serde_json::Value".to_string(),
        RustType::Ref(name) => render_ref(name, common),
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            format!("{parent}{}", pascal_case(field))
        }
    }
}

/// Render a `RustType` as an inline expression — mirrors `render_field_type`
/// but without a parent/field context (used for top-level type aliases).
fn render_inline_type(ty: &RustType, common: &BTreeSet<String>) -> String {
    match ty {
        RustType::Primitive(p) => render_prim(*p).to_string(),
        RustType::Optional(inner) => format!("Option<{}>", render_inline_type(inner, common)),
        RustType::Vec(inner) => format!("Vec<{}>", render_inline_type(inner, common)),
        RustType::Map(inner) => format!(
            "std::collections::BTreeMap<String, {}>",
            render_inline_type(inner, common)
        ),
        RustType::Json => "serde_json::Value".to_string(),
        RustType::Ref(name) => render_ref(name, common),
        RustType::Struct(s) => s.name.0.clone(),
        RustType::Enum(e) => e.name.0.clone(),
        RustType::TaggedUnion(t) => t.name.0.clone(),
        RustType::UntaggedUnion(u) => u.name.0.clone(),
        RustType::Recursive(r) => r.name.0.clone(),
    }
}

fn render_ref(name: &TypeName, common: &BTreeSet<String>) -> String {
    if common.contains(&name.0) {
        format!("crate::generated::common::{}", name.0)
    } else {
        name.0.clone()
    }
}

fn render_prim(p: Prim) -> &'static str {
    match p {
        Prim::String => "String",
        Prim::I64 => "i64",
        Prim::U64 => "u64",
        Prim::F64 => "f64",
        Prim::Bool => "bool",
    }
}

/// Walk a list of struct fields and accumulate nested types that need their
/// own top-level declaration (`Struct`, `Enum`, `TaggedUnion`, `UntaggedUnion`,
/// `Recursive`). The returned `(name, type)` pairs are sibling declarations the
/// caller should emit before the enclosing parent. Names are formed as
/// `<parent><field-pascal>`.
fn collect_nested_from_fields(
    fields: &[StructField],
    parent: &str,
    out: &mut Vec<(String, RustType)>,
) {
    for field in fields {
        collect_nested(&field.ty, parent, &field.name, out);
    }
}

fn collect_nested(ty: &RustType, parent: &str, field: &str, out: &mut Vec<(String, RustType)>) {
    match ty {
        RustType::Optional(inner) | RustType::Vec(inner) | RustType::Map(inner) => {
            collect_nested(inner, parent, field, out);
        }
        RustType::Struct(_)
        | RustType::Enum(_)
        | RustType::TaggedUnion(_)
        | RustType::UntaggedUnion(_)
        | RustType::Recursive(_) => {
            let name = format!("{parent}{}", pascal_case(field));
            out.push((name, ty.clone()));
        }
        RustType::Primitive(_) | RustType::Json | RustType::Ref(_) => {}
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn write_doc(w: &mut RustWriter, doc: &str) {
    for line in doc.lines() {
        w.line(&format!("/// {line}"));
    }
}

fn sanitise_ident(name: &str) -> String {
    // Replace dots/hyphens/spaces with underscores so the result is a valid
    // Rust identifier; if it collides with a keyword, prefix with `r#`.
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if rust_keyword(&s) {
        format!("r#{s}")
    } else {
        s
    }
}

fn is_valid_ident(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap_or(' ');
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

/// Returns true when serde's `rename_all = "snake_case"` mapping would
/// reproduce `wire` from `rust_ident`. When it does, no explicit `rename`
/// attribute is needed.
fn wire_matches_rename(wire: &str, rust_ident: &str) -> bool {
    // Convert PascalCase → snake_case and compare.
    let mut snake = String::with_capacity(rust_ident.len() + 4);
    for (i, c) in rust_ident.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                snake.push('_');
            }
            snake.extend(c.to_lowercase());
        } else {
            snake.push(c);
        }
    }
    snake == wire
}
