//! MCP emitter — writes tool declarations and JSON schemas into
//! `crates/cairn-mcp/src/generated/`.

use std::fmt::Write as _;
use std::path::PathBuf;

use serde_json::{Map, Value};

use super::fmt::{RustWriter, write_json_canonical};
use super::ir::{Document, VerbDef};
use super::{CodegenError, GeneratedFile};

const HEADER_RS: &str = "// @generated by cairn-codegen — DO NOT EDIT.\n";
const RUSTFMT_SKIP: &str = "#![cfg_attr(rustfmt, rustfmt_skip)]\n";
const FILE_LINTS: &str = "#![allow(clippy::module_name_repetitions, clippy::large_enum_variant, clippy::missing_errors_doc, clippy::missing_panics_doc, clippy::doc_markdown, clippy::needless_raw_string_hashes, missing_docs, dead_code)]\n";
const ROOT: &str = "crates/cairn-mcp/src/generated";

/// Emit the MCP tool declaration module plus per-verb / per-prelude JSON schemas
/// and the supporting `common/`, `errors/`, `capabilities/`, `extensions/`, and
/// `envelope/` schema bundles. The supporting bundles travel alongside the verbs
/// so cross-file `$ref` paths like `../common/scope_filter.json` continue to
/// resolve when the on-disk MCP schemas are loaded.
///
/// # Errors
///
/// Returns [`CodegenError::Emit`] if a stored schema fails to parse as JSON
/// during the canonicalisation pass.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    let mut out = Vec::new();
    out.push(emit_mod(doc));
    for verb in &doc.verbs {
        // The verb's stored bytes are now the full source file (not just
        // $defs.Args), so any `#/$defs/<sibling>` reference inside Args/Data
        // continues to resolve against schemas/verbs/<id>.json.
        out.push(emit_schema(
            &format!("{ROOT}/schemas/verbs/{}.json", verb.id),
            &verb.args_schema_bytes,
        )?);
        // Companion file rooted at $defs.Args so MCP clients have a tool
        // input schema that actually validates Args (not the verb document).
        // ToolDecl.input_schema points here.
        out.push(emit_args_input_schema(verb)?);
    }
    for prelude in &doc.preludes {
        out.push(emit_schema(
            &format!("{ROOT}/schemas/prelude/{}.json", prelude.id),
            &prelude.schema_bytes,
        )?);
    }
    // Mirror every non-verb/non-prelude IDL file under schemas/<group>/<file>.
    // The directory layout matches the IDL source tree so relative `$ref`s
    // (e.g. `../common/primitives.json`) resolve byte-for-byte.
    for group in ["common", "errors", "capabilities", "extensions", "envelope"] {
        out.extend(emit_group(group)?);
    }
    Ok(out)
}

/// Walk `crates/cairn-idl/schema/<group>/` and emit every `*.json` file under
/// `crates/cairn-mcp/src/generated/schemas/<group>/`. Non-JSON files (README,
/// etc.) are ignored.
fn emit_group(group: &str) -> Result<Vec<GeneratedFile>, CodegenError> {
    let group_dir = std::path::PathBuf::from(crate::SCHEMA_DIR).join(group);
    let mut entries: Vec<std::path::PathBuf> = std::fs::read_dir(&group_dir)
        .map_err(|e| {
            CodegenError::Emit(format!(
                "schema group {group}: read_dir {}: {e}",
                group_dir.display()
            ))
        })?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    entries.sort();

    let mut out = Vec::with_capacity(entries.len());
    for path in &entries {
        let bytes = std::fs::read(path)
            .map_err(|e| CodegenError::Emit(format!("read {}: {e}", path.display())))?;
        let stem = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| CodegenError::Emit(format!("bad filename: {}", path.display())))?;
        out.push(emit_schema(
            &format!("{ROOT}/schemas/{group}/{stem}"),
            &bytes,
        )?);
    }
    Ok(out)
}

fn emit_mod(doc: &Document) -> GeneratedFile {
    let mut w = RustWriter::new();
    w.raw(HEADER_RS);
    w.raw(RUSTFMT_SKIP);
    w.raw(FILE_LINTS);
    w.line("//! Generated MCP tool declarations for cairn.mcp.v1.");
    w.blank();
    w.line("/// One field- / mode-level auth override surfaced from the IDL's");
    w.line("/// `x-cairn-auth` annotations on Args properties or Args sub-types.");
    w.line("///");
    w.line("/// The MCP transport / verb dispatcher checks these BEFORE running a");
    w.line("/// verb when the matching path is present in the request payload, so a");
    w.line("/// caller cannot reach a write-producing mode (`lint.write_report=true`,");
    w.line("/// `summarize.persist=true`, `forget.mode=record`) under the verb-level");
    w.line("/// auth alone.");
    w.line("pub struct AuthOverride {");
    w.indent();
    w.line("/// Dot-path inside Args identifying the trigger.");
    w.line("/// * Boolean / property triggers: bare property name");
    w.line("///   (`\"write_report\"`, `\"persist\"`).");
    w.line("/// * Tagged-union sub-type triggers:");
    w.line("///   `\"<discriminator>=<wire>\"` (`\"mode=record\"`,");
    w.line("///   `\"target=session\"`).");
    w.line("pub path: &'static str,");
    w.line("/// Auth model required when `path` matches.");
    w.line("pub auth: &'static str,");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("/// One field- / mode-level capability override surfaced from the IDL's");
    w.line("/// `x-cairn-capability` annotations on Args properties or Args sub-types.");
    w.line("///");
    w.line("/// Verbs `search`, `retrieve`, and `forget` advertise no root capability");
    w.line("/// (the IDL leaves `x-cairn-capability: null` at the verb document level)");
    w.line("/// — instead each Args sub-type / mode declares its own concrete");
    w.line("/// capability string (`cairn.mcp.v1.search.keyword`,");
    w.line("/// `cairn.mcp.v1.retrieve.profile`, `cairn.mcp.v1.forget.scope`, …).");
    w.line("/// Surfacing them here lets the MCP transport check the right capability");
    w.line("/// once the request shape is known. Gating logic is out of scope for the");
    w.line("/// codegen — this struct only exposes the metadata.");
    w.line("pub struct CapabilityOverride {");
    w.indent();
    w.line("/// Dot-path inside Args identifying the trigger. Same encoding as");
    w.line("/// `AuthOverride.path`.");
    w.line("pub path: &'static str,");
    w.line("/// Capability string required when `path` matches.");
    w.line("pub capability: &'static str,");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("/// Static tool declaration the MCP transport layer registers at startup.");
    w.line("pub struct ToolDecl {");
    w.indent();
    w.line("pub name: &'static str,");
    w.line("pub description: &'static str,");
    w.line("pub input_schema: &'static [u8],");
    w.line("pub capability: Option<&'static str>,");
    w.line("pub auth: &'static str,");
    w.line("/// Field- / mode-level auth overrides. Empty when the verb's");
    w.line("/// declared `auth` covers every reachable Args shape.");
    w.line("pub auth_overrides: &'static [AuthOverride],");
    w.line("/// Field- / mode-level capability overrides. Non-empty for verbs");
    w.line("/// whose root `capability` is `None` but whose Args sub-types or");
    w.line("/// const enums advertise per-mode capabilities (search, retrieve,");
    w.line("/// forget).");
    w.line("pub capability_overrides: &'static [CapabilityOverride],");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("pub const TOOLS: &[ToolDecl] = &[");
    w.indent();
    for verb in &doc.verbs {
        emit_tool_decl(&mut w, verb);
    }
    w.dedent();
    w.line("];");
    GeneratedFile {
        path: PathBuf::from(ROOT).join("mod.rs"),
        bytes: w.finish().into_bytes(),
    }
}

fn emit_tool_decl(w: &mut RustWriter, verb: &VerbDef) {
    let description = build_description(verb);
    w.line("ToolDecl {");
    w.indent();
    w.line(&format!("name: \"{}\",", verb.id));
    // Multi-line raw string so embedded newlines stay readable.
    w.line(&format!("description: r#\"{description}\"#,"));
    w.line(&format!(
        "input_schema: include_bytes!(\"schemas/verbs/{}.input.json\"),",
        verb.id
    ));
    match &verb.capability {
        Some(c) => w.line(&format!("capability: Some(\"{c}\"),")),
        None => w.line("capability: None,"),
    }
    w.line(&format!("auth: \"{}\",", verb.auth.as_str()));
    if verb.auth_overrides.is_empty() {
        w.line("auth_overrides: &[],");
    } else {
        w.line("auth_overrides: &[");
        w.indent();
        for ov in &verb.auth_overrides {
            w.line(&format!(
                "AuthOverride {{ path: \"{}\", auth: \"{}\" }},",
                ov.path,
                ov.auth.as_str()
            ));
        }
        w.dedent();
        w.line("],");
    }
    if verb.capability_overrides.is_empty() {
        w.line("capability_overrides: &[],");
    } else {
        w.line("capability_overrides: &[");
        w.indent();
        for ov in &verb.capability_overrides {
            w.line(&format!(
                "CapabilityOverride {{ path: \"{}\", capability: \"{}\" }},",
                ov.path, ov.capability,
            ));
        }
        w.dedent();
        w.line("],");
    }
    w.dedent();
    w.line("},");
}

fn build_description(verb: &VerbDef) -> String {
    // §8.0.b: one-line purpose + positive triggers + negative triggers + exclusivity.
    let mut s = String::new();
    let _ = writeln!(s, "`{}` — verb {}.", verb.id, verb.id);
    if !verb.skill.positive.is_empty() {
        s.push_str("\nPOSITIVE — use when:\n");
        for p in &verb.skill.positive {
            s.push_str("• ");
            s.push_str(p);
            s.push('\n');
        }
    }
    if !verb.skill.negative.is_empty() {
        s.push_str("\nNEGATIVE — do not use when:\n");
        for n in &verb.skill.negative {
            s.push_str("• ");
            s.push_str(n);
            s.push('\n');
        }
    }
    if let Some(ex) = &verb.skill.exclusivity {
        s.push_str("\nEXCLUSIVITY: ");
        s.push_str(ex);
        s.push('\n');
    }
    s
}

fn emit_schema(rel_path: &str, raw_bytes: &[u8]) -> Result<GeneratedFile, CodegenError> {
    // Parse + re-serialise canonically so the on-disk schema is normalised
    // (sorted keys, two-space indent, trailing newline). Validation guarantees
    // the input parses; if it ever doesn't, surface the error.
    let value: Value = serde_json::from_slice(raw_bytes)
        .map_err(|e| CodegenError::Emit(format!("schema parse: {e}")))?;
    Ok(GeneratedFile {
        path: PathBuf::from(rel_path),
        bytes: write_json_canonical(&value).into_bytes(),
    })
}

/// Emit a per-verb tool-input schema rooted at the verb's `$defs/Args`.
///
/// MCP clients validate tool inputs against `ToolDecl.input_schema`. The full
/// verb document has `type: object` with verb metadata at the root, and Args
/// only lives under `$defs/Args` — so without this companion the schema MCP
/// clients see is a permissive object that accepts `{}` for every verb,
/// including verbs with required fields. We emit a sibling
/// `<verb>.input.json` whose root delegates via `$ref: #/$defs/Args` and
/// carries a copy of the original `$defs` so local `#/$defs/<sibling>`
/// references inside Args continue to resolve. Cross-file `../common/...`
/// refs resolve against the same schemas/ tree that MCP already publishes
/// (siblings of the verb file).
fn emit_args_input_schema(verb: &VerbDef) -> Result<GeneratedFile, CodegenError> {
    let value: Value = serde_json::from_slice(&verb.args_schema_bytes)
        .map_err(|e| CodegenError::Emit(format!("args input schema parse: {e}")))?;
    let defs = value
        .get("$defs")
        .cloned()
        .ok_or_else(|| CodegenError::Emit(format!("verb {}: missing $defs", verb.id)))?;
    if defs.get("Args").is_none() {
        return Err(CodegenError::Emit(format!(
            "verb {}: missing $defs.Args",
            verb.id
        )));
    }

    let mut root = Map::new();
    root.insert(
        "$schema".to_string(),
        Value::String("https://json-schema.org/draft/2020-12/schema".to_string()),
    );
    root.insert(
        "$id".to_string(),
        Value::String(format!(
            "https://cairn.dev/schema/cairn.mcp.v1/verbs/{}.input.json",
            verb.id
        )),
    );
    root.insert(
        "x-cairn-contract".to_string(),
        Value::String("cairn.mcp.v1".to_string()),
    );
    root.insert(
        "title".to_string(),
        Value::String(format!("Cairn verb input: {}", verb.id)),
    );
    // The root delegates to Args via $ref. JSON Schema 2020-12 allows
    // sibling keywords with $ref, but pure $ref-at-root is the cleanest
    // expression of "this document IS the Args schema".
    root.insert(
        "$ref".to_string(),
        Value::String("#/$defs/Args".to_string()),
    );
    root.insert("$defs".to_string(), defs);

    let canonical = write_json_canonical(&Value::Object(root));
    Ok(GeneratedFile {
        path: PathBuf::from(format!("{ROOT}/schemas/verbs/{}.input.json", verb.id)),
        bytes: canonical.into_bytes(),
    })
}
