//! Skill emitter — writes the Cairn skill bundle into `skills/cairn/`.

use std::fmt::Write as _;
use std::path::PathBuf;

use super::ir::{Document, VerbDef};
use super::{CodegenError, GeneratedFile};

const HEADER_MD: &str = "<!-- @generated by cairn-codegen — DO NOT EDIT. -->\n";

/// Emit the skill-bundle files (`SKILL.md`, `conventions.md`, `.version`, and
/// example stubs) for the `skills/cairn/` directory.
pub fn emit(doc: &Document) -> Result<Vec<GeneratedFile>, CodegenError> {
    let mut files = vec![emit_skill_md(doc), emit_conventions(doc), emit_version(doc)];
    files.extend(emit_examples());
    Ok(files)
}

fn emit_skill_md(doc: &Document) -> GeneratedFile {
    let mut s = String::new();
    s.push_str(HEADER_MD);
    s.push_str("---\n");
    s.push_str("name: cairn\n");
    s.push_str("description: Cairn memory system. Use for persistent memory across turns, sessions, and agents.\n");
    s.push_str("---\n\n");
    s.push_str("# Cairn Memory Skill\n\n");
    s.push_str("Persistent memory via the `cairn` CLI. The eight verbs below are the contract. ");
    s.push_str("Status / handshake are protocol preludes — see the bottom of this file.\n\n");
    for verb in &doc.verbs {
        push_verb_section(&mut s, verb);
    }
    s.push_str("---\n\n## Protocol preludes (not core verbs)\n\n");
    for prelude in &doc.preludes {
        let desc = match prelude.id.as_str() {
            "status" => "deterministic capability discovery (cacheable, no side effects).",
            "handshake" => "fresh per-call challenge mint.",
            _ => "(prelude)",
        };
        let _ = writeln!(s, "- `cairn {} --json` — {}", prelude.id, desc);
    }
    s.push('\n');
    GeneratedFile {
        path: PathBuf::from("skills/cairn/SKILL.md"),
        bytes: s.into_bytes(),
    }
}

fn push_verb_section(s: &mut String, verb: &VerbDef) {
    let _ = write!(s, "## `cairn {}`\n\n", verb.id);
    if !verb.skill.positive.is_empty() {
        s.push_str("**Use when:**\n");
        for p in &verb.skill.positive {
            s.push_str("- ");
            s.push_str(p);
            s.push('\n');
        }
        s.push('\n');
    }
    if !verb.skill.negative.is_empty() {
        s.push_str("**Do NOT use when:**\n");
        for n in &verb.skill.negative {
            s.push_str("- ");
            s.push_str(n);
            s.push('\n');
        }
        s.push('\n');
    }
    if let Some(ex) = &verb.skill.exclusivity {
        s.push_str("**Exclusivity:** ");
        s.push_str(ex);
        s.push_str("\n\n");
    }
}

fn emit_conventions(doc: &Document) -> GeneratedFile {
    let mut s = String::new();
    s.push_str(HEADER_MD);
    s.push_str("# Cairn skill conventions\n\n");
    s.push_str("Verb ids in the contract:\n\n");
    for verb in &doc.verbs {
        let _ = writeln!(s, "- `{}`", verb.id);
    }
    s.push_str("\n## Kind cheat-sheet (pick one — never invent new kinds)\n\n");
    // TODO(taxonomy-idl): generate from IDL when taxonomy slice lands
    let kinds: &[(&str, &str)] = &[
        ("user", "preferences, working style, identity"),
        ("feedback", "corrections the user gave you"),
        ("rule", r#"invariants ("never X", "always Y")"#),
        ("fact", "verifiable claims about the world"),
        ("entity", "people, projects, systems you encountered"),
        ("playbook", "reusable procedures with decision trees"),
        ("strategy_success", "an ad-hoc procedure that worked"),
        (
            "trace",
            "reasoning trajectories (auto-captured; don't call directly)",
        ),
    ];
    for (kind, desc) in kinds {
        let _ = writeln!(s, "- `{kind}` — {desc}");
    }
    s.push('\n');
    GeneratedFile {
        path: PathBuf::from("skills/cairn/conventions.md"),
        bytes: s.into_bytes(),
    }
}

fn emit_version(_doc: &Document) -> GeneratedFile {
    let s = format!(
        "contract: cairn.mcp.v1\ncairn-idl: {}\n",
        env!("CARGO_PKG_VERSION"),
    );
    GeneratedFile {
        path: PathBuf::from("skills/cairn/.version"),
        bytes: s.into_bytes(),
    }
}

/// Emit example stub files under `skills/cairn/examples/`.
///
/// These are written once by `cairn skill install` and the user may edit them
/// afterwards (they are preserved on reinstall via `write_once`). Codegen owns
/// them so that `--check` can verify the source-of-truth copies in the repo.
fn emit_examples() -> Vec<GeneratedFile> {
    let examples: &[(&str, &str)] = &[
        (
            "skills/cairn/examples/01-remember-preference.md",
            "# Example: remember a preference\n\
\n\
**User says:** \"Remember that I prefer snake_case for all variable names.\"\n\
\n\
**Cairn call:**\n\
```bash\n\
cairn ingest --kind user --body \"prefers snake_case for variable names\"\n\
```\n\
\n\
**Why `kind: user`:** A preference about working style that should persist across sessions.\n",
        ),
        (
            "skills/cairn/examples/02-forget-something.md",
            "# Example: forget a stored fact\n\
\n\
**User says:** \"Forget what I said about preferring tabs.\"\n\
\n\
**Cairn calls (two steps):**\n\
```bash\n\
# 1. Find the record id\n\
cairn search \"tabs preference\" --limit 5 --json\n\
\n\
# 2. Delete it (confirm with user before running forget)\n\
cairn forget --record <id-from-search>\n\
```\n\
\n\
**Non-negotiable:** Always confirm with the user before running `cairn forget`.\n",
        ),
        (
            "skills/cairn/examples/03-search-prior-decision.md",
            "# Example: search for a prior decision\n\
\n\
**User says:** \"What did we decide about the database schema?\"\n\
\n\
**Cairn call:**\n\
```bash\n\
cairn search \"database schema decision\" --limit 10 --json\n\
```\n\
\n\
**Parse the JSON response:**\n\
```json\n\
{\"hits\":[\n\
  {\"id\":\"01HQZ...\",\"kind\":\"fact\",\"body\":\"decided to use sqlite-vec for ANN\",\"score\":0.91}\n\
]}\n\
```\n",
        ),
        (
            "skills/cairn/examples/04-skillify-this.md",
            "# Example: skillify a procedure\n\
\n\
**User says:** \"Skillify this — we just figured out how to run the benchmarks.\"\n\
\n\
**Cairn call:**\n\
```bash\n\
cairn ingest \\\n\
  --kind strategy_success \\\n\
  --body \"Run benchmarks: cargo criterion --bench <name>; results in target/criterion/\" \\\n\
  --tag benchmark,procedure\n\
```\n\
\n\
**Why `kind: strategy_success`:** A procedure that worked — worth keeping for next time.\n",
        ),
    ];
    examples
        .iter()
        .map(|(path, content)| GeneratedFile {
            path: PathBuf::from(path),
            bytes: content.as_bytes().to_vec(),
        })
        .collect()
}
