//! Codegen pipeline: load IDL → lower to IR → emit four artefact bundles.
//!
//! Public entry point is [`run`]. Internally split into [`loader`], [`ir`],
//! and four `emit_*` modules. Stages are pure (no filesystem writes) until
//! `run` batches the union of every emitter's [`GeneratedFile`] outputs in a
//! single atomic pass, so a panic mid-emit cannot leave half-written trees.

pub mod emit_cli;
pub mod emit_mcp;
pub mod emit_sdk;
pub mod emit_skill;
pub mod fmt;
pub mod ir;
pub mod loader;
pub mod skill_compat;

use std::path::{Path, PathBuf};

/// Workspace-relative roots that codegen *owns* end-to-end. Files inside these
/// directories that aren't part of the latest emit are stale and either flagged
/// (`Check`) or pruned (`Write`). Adding a new emitter destination means
/// extending this list — that is intentional, so an unowned tree isn't silently
/// scrubbed.
const OWNED_ROOTS: &[&str] = &[
    "crates/cairn-core/src/generated",
    "crates/cairn-cli/src/generated",
    "crates/cairn-mcp/src/generated",
    "skills/cairn",
];

/// One generated artefact returned by an emitter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the workspace root.
    pub path: PathBuf,
    /// Raw bytes to write.
    pub bytes: Vec<u8>,
}

/// Errors returned by the codegen pipeline.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// Loader could not read or parse an IDL file.
    #[error("loader: {0}")]
    Loader(String),
    /// IR lowering rejected a schema construct it cannot represent.
    #[error("ir: {0}")]
    Ir(String),
    /// An emitter produced inconsistent output.
    #[error("emit: {0}")]
    Emit(String),
    /// Filesystem operation failed during write.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Options for [`run`].
#[derive(Debug, Clone)]
pub struct RunOpts {
    /// Workspace root that emitter outputs are written under. Defaults to the
    /// parent of `CARGO_MANIFEST_DIR` (i.e. the workspace root).
    pub workspace_root: PathBuf,
    /// In `Check` mode the binary exits non-zero on any byte-diff between
    /// emitter output and the on-disk file; no writes happen.
    pub mode: RunMode,
}

/// Generator mode — write outputs vs. assert no drift.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    /// Write generated files to `workspace_root`.
    Write,
    /// Compare generated bytes against on-disk; exit non-zero on drift.
    Check,
}

/// Summary returned to the caller.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Report {
    /// Total artefacts emitted.
    pub files_emitted: usize,
    /// In Check mode, files whose on-disk bytes differ from emitted bytes.
    pub drift: Vec<PathBuf>,
}

/// Run the full pipeline.
///
/// Stages:
/// 1. Load and validate every IDL file under [`crate::SCHEMA_DIR`].
/// 2. Lower the raw JSON into the typed [`ir::Document`].
/// 3. Invoke every emitter; collect [`GeneratedFile`] outputs.
/// 4. Sort outputs by path (deterministic report order).
/// 5. In [`RunMode::Write`]: write each file atomically via
///    [`tempfile::NamedTempFile::persist`] so a mid-run crash cannot leave
///    partially-written artefacts.
///    In [`RunMode::Check`]: compare emitter bytes against on-disk bytes;
///    populate [`Report::drift`] with any mismatches.
pub fn run(opts: &RunOpts) -> Result<Report, CodegenError> {
    use std::io::Write as _;

    let schema_root = std::path::PathBuf::from(crate::SCHEMA_DIR);
    let raw = loader::load(&schema_root)?;
    let doc = ir::build(&raw)?;

    let mut all = Vec::new();
    all.extend(emit_sdk::emit(&doc)?);
    all.extend(emit_cli::emit(&doc)?);
    all.extend(emit_mcp::emit(&doc)?);
    let skill_files = emit_skill::emit(&doc)?;
    // Run skill compat against freshly-emitted SKILL.md so any drift between
    // the IDL and the templated examples (verbs, flags, JSON payloads) blocks
    // both `--write` and `--check` (issue #70 acceptance: "compat checks run
    // with contract drift CI").
    check_skill_compat(&doc, &skill_files)?;
    all.extend(skill_files);

    // Stable-sort outputs so reports are deterministic.
    all.sort_by(|a, b| a.path.cmp(&b.path));

    let mut report = Report {
        files_emitted: all.len(),
        drift: Vec::new(),
    };

    // Set of expected workspace-relative paths for the current emit. Used both
    // to detect stale on-disk files (Check) and to delete them (Write).
    let expected: std::collections::BTreeSet<PathBuf> =
        all.iter().map(|f| f.path.clone()).collect();

    match opts.mode {
        RunMode::Write => {
            for file in &all {
                let abs = opts.workspace_root.join(&file.path);
                if let Some(parent) = abs.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                // Atomic write via tempfile + persist.
                let dir = abs.parent().unwrap_or(Path::new("."));
                let mut tmp = tempfile::NamedTempFile::new_in(dir)?;
                tmp.write_all(&file.bytes)?;
                tmp.persist(&abs).map_err(|e| CodegenError::Io(e.error))?;
            }
            // Prune anything inside the owned roots that the emit didn't
            // claim. Without this, removing an IDL file leaves the stale
            // generated artefact committed and `--check` keeps reporting clean.
            for stale in stale_files(&opts.workspace_root, &expected)? {
                let abs = opts.workspace_root.join(&stale);
                // `remove_file` is idempotent enough — we collected the path by
                // walking the directory, so it should still exist. Treat ENOENT
                // as benign to keep the run resilient against concurrent edits.
                if let Err(e) = std::fs::remove_file(&abs)
                    && e.kind() != std::io::ErrorKind::NotFound
                {
                    return Err(CodegenError::Io(e));
                }
            }
        }
        RunMode::Check => {
            for file in &all {
                let abs = opts.workspace_root.join(&file.path);
                let Ok(on_disk) = std::fs::read(&abs) else {
                    report.drift.push(file.path.clone());
                    continue;
                };
                if on_disk != file.bytes {
                    report.drift.push(file.path.clone());
                }
            }
            // Stale files (on-disk, inside an owned root, not produced by this
            // emit) count as drift — otherwise removing an IDL source still
            // leaves a generated artefact lying around and `--check` is silent.
            for stale in stale_files(&opts.workspace_root, &expected)? {
                report.drift.push(stale);
            }
            // Deterministic order keeps snapshot tests stable regardless of
            // the order emitters and the walker visited paths in.
            report.drift.sort();
            report.drift.dedup();
        }
    }
    Ok(report)
}

/// Validate every CLI invocation embedded in the freshly-emitted SKILL.md
/// against the IR. Returns [`CodegenError::Emit`] on the first failure so a
/// retired verb, an unknown flag, or a stale prelude reference fails the
/// codegen run rather than shipping a broken skill.
fn check_skill_compat(doc: &ir::Document, files: &[GeneratedFile]) -> Result<(), CodegenError> {
    let Some(skill) = files
        .iter()
        .find(|f| f.path.ends_with("skills/cairn/SKILL.md"))
    else {
        return Ok(());
    };
    let body = std::str::from_utf8(&skill.bytes)
        .map_err(|e| CodegenError::Emit(format!("SKILL.md not utf-8: {e}")))?;
    for block in skill_compat::extract_code_blocks(body) {
        let is_cli = matches!(block.lang.as_str(), "bash" | "shell" | "sh" | "inline")
            && block.body.trim_start().starts_with("cairn ");
        if !is_cli {
            continue;
        }
        skill_compat::validate_cli_block(&block, doc)
            .map_err(|e| CodegenError::Emit(format!("skill compat: {e}")))?;
    }
    Ok(())
}

/// Walk every [`OWNED_ROOTS`] entry under `workspace_root` and return the
/// workspace-relative paths of files NOT in `expected`. Missing roots are
/// silently skipped — the generator may legitimately run before the directory
/// exists (fresh `tempdir` in tests, first run on a new repo).
fn stale_files(
    workspace_root: &Path,
    expected: &std::collections::BTreeSet<PathBuf>,
) -> Result<Vec<PathBuf>, CodegenError> {
    let mut stale = Vec::new();
    for root in OWNED_ROOTS {
        let abs_root = workspace_root.join(root);
        if !abs_root.exists() {
            continue;
        }
        walk_files(&abs_root, &mut |abs_path| {
            // Translate back to a workspace-relative path so it matches
            // `expected` (which the emitters populate with relative paths).
            let Ok(rel) = abs_path.strip_prefix(workspace_root) else {
                return Ok(());
            };
            let rel_buf = rel.to_path_buf();
            if !expected.contains(&rel_buf) {
                stale.push(rel_buf);
            }
            Ok(())
        })?;
    }
    stale.sort();
    stale.dedup();
    Ok(stale)
}

/// Recursive directory walker — invokes `visit` once per regular file. Kept
/// inline (no `walkdir` dep) so codegen has no extra runtime dependencies.
fn walk_files(
    dir: &Path,
    visit: &mut dyn FnMut(&Path) -> Result<(), CodegenError>,
) -> Result<(), CodegenError> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            walk_files(&path, visit)?;
        } else if file_type.is_file() {
            visit(&path)?;
        }
        // Symlinks et al. are intentionally ignored — codegen never emits them
        // and following them risks straying outside the workspace.
    }
    Ok(())
}
