//! Codegen pipeline: load IDL → lower to IR → emit four artefact bundles.
//!
//! Public entry point is [`run`]. Internally split into [`loader`], [`ir`],
//! and four `emit_*` modules. Stages are pure (no filesystem writes) until
//! `run` batches the union of every emitter's [`GeneratedFile`] outputs in a
//! single atomic pass, so a panic mid-emit cannot leave half-written trees.

pub mod emit_cli;
pub mod emit_mcp;
pub mod emit_sdk;
pub mod emit_skill;
pub mod fmt;
pub mod ir;
pub mod loader;

use std::path::PathBuf;

/// One generated artefact returned by an emitter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the workspace root.
    pub path: PathBuf,
    /// Raw bytes to write.
    pub bytes: Vec<u8>,
}

/// Errors returned by the codegen pipeline.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// Loader could not read or parse an IDL file.
    #[error("loader: {0}")]
    Loader(String),
    /// IR lowering rejected a schema construct it cannot represent.
    #[error("ir: {0}")]
    Ir(String),
    /// An emitter produced inconsistent output.
    #[error("emit: {0}")]
    Emit(String),
    /// Filesystem operation failed during write.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Options for [`run`].
#[derive(Debug, Clone)]
pub struct RunOpts {
    /// Workspace root that emitter outputs are written under. Defaults to the
    /// parent of `CARGO_MANIFEST_DIR` (i.e. the workspace root).
    pub workspace_root: PathBuf,
    /// In `Check` mode the binary exits non-zero on any byte-diff between
    /// emitter output and the on-disk file; no writes happen.
    pub mode: RunMode,
}

/// Generator mode — write outputs vs. assert no drift.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    /// Write generated files to `workspace_root`.
    Write,
    /// Compare generated bytes against on-disk; exit non-zero on drift.
    Check,
}

/// Summary returned to the caller.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Report {
    /// Total artefacts emitted.
    pub files_emitted: usize,
    /// In Check mode, files whose on-disk bytes differ from emitted bytes.
    pub drift: Vec<PathBuf>,
}

/// Run the full pipeline.
///
/// Stages:
/// 1. Load and validate every IDL file under [`crate::SCHEMA_DIR`].
/// 2. Lower the raw JSON into the typed [`ir::Document`].
/// 3. Invoke every emitter; collect [`GeneratedFile`] outputs.
/// 4. Sort outputs by path (deterministic report order).
/// 5. In [`RunMode::Write`]: write each file atomically via
///    [`tempfile::NamedTempFile::persist`] so a mid-run crash cannot leave
///    partially-written artefacts.
///    In [`RunMode::Check`]: compare emitter bytes against on-disk bytes;
///    populate [`Report::drift`] with any mismatches.
pub fn run(opts: &RunOpts) -> Result<Report, CodegenError> {
    use std::io::Write as _;

    let schema_root = std::path::PathBuf::from(crate::SCHEMA_DIR);
    let raw = loader::load(&schema_root)?;
    let doc = ir::build(&raw)?;

    let mut all = Vec::new();
    all.extend(emit_sdk::emit(&doc)?);
    all.extend(emit_cli::emit(&doc)?);
    all.extend(emit_mcp::emit(&doc)?);
    all.extend(emit_skill::emit(&doc)?);

    // Stable-sort outputs so reports are deterministic.
    all.sort_by(|a, b| a.path.cmp(&b.path));

    let mut report = Report {
        files_emitted: all.len(),
        drift: Vec::new(),
    };

    match opts.mode {
        RunMode::Write => {
            for file in &all {
                let abs = opts.workspace_root.join(&file.path);
                if let Some(parent) = abs.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                // Atomic write via tempfile + persist.
                let dir = abs.parent().unwrap_or(std::path::Path::new("."));
                let mut tmp = tempfile::NamedTempFile::new_in(dir)?;
                tmp.write_all(&file.bytes)?;
                tmp.persist(&abs).map_err(|e| CodegenError::Io(e.error))?;
            }
        }
        RunMode::Check => {
            for file in &all {
                let abs = opts.workspace_root.join(&file.path);
                let Ok(on_disk) = std::fs::read(&abs) else {
                    report.drift.push(file.path.clone());
                    continue;
                };
                if on_disk != file.bytes {
                    report.drift.push(file.path.clone());
                }
            }
        }
    }
    Ok(report)
}
