//! Codegen pipeline: load IDL → lower to IR → emit four artefact bundles.
//!
//! Public entry point is [`run`]. Internally split into [`loader`], [`ir`],
//! and four `emit_*` modules. Stages are pure (no filesystem writes) until
//! `run` batches the union of every emitter's [`GeneratedFile`] outputs in a
//! single atomic pass, so a panic mid-emit cannot leave half-written trees.

pub mod emit_cli;
pub mod emit_mcp;
pub mod emit_sdk;
pub mod emit_skill;
pub mod fmt;
pub mod ir;
pub mod loader;

use std::path::PathBuf;

/// One generated artefact returned by an emitter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the workspace root.
    pub path: PathBuf,
    /// Raw bytes to write.
    pub bytes: Vec<u8>,
}

/// Errors returned by the codegen pipeline.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// Loader could not read or parse an IDL file.
    #[error("loader: {0}")]
    Loader(String),
    /// IR lowering rejected a schema construct it cannot represent.
    #[error("ir: {0}")]
    Ir(String),
    /// An emitter produced inconsistent output.
    #[error("emit: {0}")]
    Emit(String),
    /// Filesystem operation failed during write.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Options for [`run`].
#[derive(Debug, Clone)]
pub struct RunOpts {
    /// Workspace root that emitter outputs are written under. Defaults to the
    /// parent of `CARGO_MANIFEST_DIR` (i.e. the workspace root).
    pub workspace_root: PathBuf,
    /// In `Check` mode the binary exits non-zero on any byte-diff between
    /// emitter output and the on-disk file; no writes happen.
    pub mode: RunMode,
}

/// Generator mode — write outputs vs. assert no drift.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    /// Write generated files to `workspace_root`.
    Write,
    /// Compare generated bytes against on-disk; exit non-zero on drift.
    Check,
}

/// Summary returned to the caller.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Report {
    /// Total artefacts emitted.
    pub files_emitted: usize,
    /// In Check mode, files whose on-disk bytes differ from emitted bytes.
    pub drift: Vec<PathBuf>,
}

/// Run the full pipeline. Stub — implementation lands in later tasks.
pub fn run(_opts: &RunOpts) -> Result<Report, CodegenError> {
    Err(CodegenError::Emit(
        "codegen::run is not yet implemented".to_string(),
    ))
}
