//! Maintainer-time Markdown generator for the Cairn docs site.
//!
//! The generator emits committed reference docs from runtime/user-facing
//! surfaces and supports `Check` mode so CI can reject stale docs.

#![allow(clippy::module_name_repetitions, clippy::too_many_lines)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use cairn_core::config::CairnConfig;
use cairn_idl::codegen;

use crate::{command, plugins};

const GENERATED_ROOT: &str = "docs/site/src/reference/generated";
const GENERATED_HEADER: &str = "<!-- @generated by cairn-docgen - DO NOT EDIT. -->\n\n";

/// Generator mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunMode {
    /// Write generated files to disk.
    Write,
    /// Compare generated files against disk and report drift.
    Check,
}

/// Options for [`run`].
#[derive(Debug, Clone)]
pub struct RunOpts {
    /// Workspace root used for output paths and docs coverage manifest lookup.
    pub workspace_root: PathBuf,
    /// Whether to write docs or only check for drift.
    pub mode: RunMode,
    /// Test-only package name override. Production runs use `cargo metadata`.
    pub package_names: Option<Vec<String>>,
}

/// Summary returned by [`run`].
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Report {
    /// Number of generated Markdown files emitted by this run.
    pub files_emitted: usize,
    /// Workspace-relative paths that differ from generated output in check mode.
    pub drift: Vec<PathBuf>,
}

/// Errors produced by `cairn-docgen`.
#[derive(Debug, thiserror::Error)]
pub enum DocgenError {
    /// Filesystem operation failed.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    /// JSON parsing failed.
    #[error("json: {0}")]
    Json(#[from] serde_json::Error),
    /// YAML rendering failed.
    #[error("yaml: {0}")]
    Yaml(#[from] serde_yaml::Error),
    /// Cargo metadata could not be collected.
    #[error("cargo metadata: {0}")]
    Metadata(String),
    /// Docs coverage manifest is missing one or more packages.
    #[error("docs coverage missing package entries: {0}")]
    MissingPackageCoverage(String),
    /// Docs coverage manifest was malformed.
    #[error("docs coverage manifest invalid: {0}")]
    InvalidCoverage(String),
    /// Bundled plugin registry could not be loaded.
    #[error("plugins: {0}")]
    Plugins(String),
}

/// Run the docs generator.
///
/// In [`RunMode::Write`], generated Markdown is written under
/// `docs/site/src/reference/generated/`. In [`RunMode::Check`], no writes
/// happen; drift is returned in [`Report::drift`].
pub fn run(opts: &RunOpts) -> Result<Report, DocgenError> {
    let package_names = match &opts.package_names {
        Some(names) => sorted_names(names.clone()),
        None => workspace_package_names(&opts.workspace_root)?,
    };
    let coverage = load_coverage(&opts.workspace_root, &package_names)?;
    let mut files = emit_all(&opts.workspace_root, &package_names, &coverage)?;
    files.sort_by(|a, b| a.path.cmp(&b.path));

    let expected: BTreeSet<PathBuf> = files.iter().map(|f| f.path.clone()).collect();
    let mut report = Report {
        files_emitted: files.len(),
        drift: Vec::new(),
    };

    match opts.mode {
        RunMode::Write => {
            for file in &files {
                write_file(&opts.workspace_root.join(&file.path), &file.bytes)?;
            }
            for stale in stale_generated_files(&opts.workspace_root, &expected)? {
                let abs = opts.workspace_root.join(stale);
                if let Err(e) = std::fs::remove_file(&abs)
                    && e.kind() != std::io::ErrorKind::NotFound
                {
                    return Err(DocgenError::Io(e));
                }
            }
        }
        RunMode::Check => {
            for file in &files {
                let abs = opts.workspace_root.join(&file.path);
                match std::fs::read(&abs) {
                    Ok(on_disk) if on_disk == file.bytes => {}
                    Ok(_) | Err(_) => report.drift.push(file.path.clone()),
                }
            }
            report
                .drift
                .extend(stale_generated_files(&opts.workspace_root, &expected)?);
            report.drift.sort();
            report.drift.dedup();
        }
    }

    Ok(report)
}

/// Build the `cairn-docgen` maintainer CLI command tree.
#[must_use]
pub fn docgen_command() -> clap::Command {
    clap::Command::new("cairn-docgen")
        .about("Generate Cairn docs reference Markdown")
        .arg(
            clap::Arg::new("check")
                .long("check")
                .conflicts_with("write")
                .action(clap::ArgAction::SetTrue)
                .help("Run in check mode: compare emitted docs against on-disk files"),
        )
        .arg(
            clap::Arg::new("write")
                .long("write")
                .action(clap::ArgAction::SetTrue)
                .help("Write generated docs; default when neither --check nor --write is set"),
        )
        .arg(
            clap::Arg::new("out")
                .long("out")
                .value_name("PATH")
                .value_parser(clap::value_parser!(PathBuf))
                .help("Workspace root (defaults to the parent of CARGO_MANIFEST_DIR)"),
        )
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct GeneratedFile {
    path: PathBuf,
    bytes: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct CoverageEntry {
    audience: String,
    page: String,
    generated_reference: String,
}

fn emit_all(
    workspace_root: &Path,
    package_names: &[String],
    coverage: &BTreeMap<String, CoverageEntry>,
) -> Result<Vec<GeneratedFile>, DocgenError> {
    let mut files = Vec::new();
    emit_cli_docs(&mut files)?;
    emit_codegen_docs(&mut files)?;
    emit_docgen_docs(&mut files)?;
    emit_config_defaults(&mut files)?;
    emit_plugins(&mut files)?;
    emit_mcp_tools(&mut files);
    emit_packages(&mut files, package_names, coverage);
    emit_contract_verbs(&mut files, workspace_root)?;
    Ok(files)
}

fn emit_codegen_docs(files: &mut Vec<GeneratedFile>) -> Result<(), DocgenError> {
    let cmd = codegen::codegen_command();
    let mut out = generated_doc("cairn-codegen");
    out.push_str("Generated from the maintainer `cairn-codegen` clap command tree.\n\n");
    out.push_str("## Help\n\n```text\n");
    out.push_str(&help_text(&cmd)?);
    out.push_str("```\n");
    files.push(generated_file("codegen.md", out));
    Ok(())
}

fn emit_docgen_docs(files: &mut Vec<GeneratedFile>) -> Result<(), DocgenError> {
    let cmd = docgen_command();
    let mut out = generated_doc("cairn-docgen");
    out.push_str("Generated from the maintainer `cairn-docgen` clap command tree.\n\n");
    out.push_str("## Help\n\n```text\n");
    out.push_str(&help_text(&cmd)?);
    out.push_str("```\n");
    files.push(generated_file("docgen.md", out));
    Ok(())
}

fn emit_cli_docs(files: &mut Vec<GeneratedFile>) -> Result<(), DocgenError> {
    let root = command::build_command();
    let mut out = generated_doc("CLI Reference");
    out.push_str("Generated from the runtime `clap::Command` tree used by `cairn`.\n\n");
    out.push_str("## Root Help\n\n");
    out.push_str("```text\n");
    out.push_str(&help_text(&root)?);
    out.push_str("```\n\n");
    out.push_str("## Commands\n\n");
    for sub in root.get_subcommands() {
        let name = sub.get_name();
        let file = command_file_name(&[name]);
        let about = sub
            .get_about()
            .map_or_else(String::new, std::string::ToString::to_string);
        let _ = writeln!(out, "- [`cairn {name}`](commands/{file}) - {about}");
        emit_command_pages(files, &[name.to_owned()], sub)?;
    }
    files.push(generated_file("cli.md", out));
    Ok(())
}

fn emit_command_pages(
    files: &mut Vec<GeneratedFile>,
    parts: &[String],
    cmd: &clap::Command,
) -> Result<(), DocgenError> {
    let display = format!("cairn {}", parts.join(" "));
    let mut out = generated_doc(&display);
    if let Some(about) = cmd.get_about() {
        let _ = writeln!(out, "{about}\n");
    }
    out.push_str("## Help\n\n```text\n");
    out.push_str(&help_text(cmd)?);
    out.push_str("```\n");

    let subcommands: Vec<_> = cmd.get_subcommands().collect();
    if !subcommands.is_empty() {
        out.push_str("\n## Subcommands\n\n");
        for sub in subcommands {
            let mut child_parts = parts.to_owned();
            child_parts.push(sub.get_name().to_owned());
            let file = command_file_name_strs(&child_parts);
            let about = sub
                .get_about()
                .map_or_else(String::new, std::string::ToString::to_string);
            let _ = writeln!(
                out,
                "- [`cairn {}`]({file}) - {about}",
                child_parts.join(" ")
            );
            emit_command_pages(files, &child_parts, sub)?;
        }
    }

    let file_name = command_file_name_strs(parts);
    files.push(generated_file(&format!("commands/{file_name}"), out));
    Ok(())
}

fn emit_config_defaults(files: &mut Vec<GeneratedFile>) -> Result<(), DocgenError> {
    let yaml = serde_yaml::to_string(&CairnConfig::default())?;
    let mut out = generated_doc("Config Defaults");
    out.push_str("Generated from `CairnConfig::default()`.\n\n");
    out.push_str("```yaml\n");
    out.push_str(&yaml);
    out.push_str("```\n");
    files.push(generated_file("config-defaults.md", out));
    Ok(())
}

fn emit_plugins(files: &mut Vec<GeneratedFile>) -> Result<(), DocgenError> {
    let registry =
        plugins::host::register_all().map_err(|e| DocgenError::Plugins(e.to_string()))?;
    let raw = plugins::list::render_json(&registry);
    let value: serde_json::Value = serde_json::from_str(&raw)?;
    let mut out = generated_doc("Bundled Plugins");
    out.push_str("Generated from the bundled plugin registry.\n\n");
    out.push_str("| Name | Contract | Version Range | Source | Capabilities |\n");
    out.push_str("|---|---|---|---|---|\n");
    for plugin in value["plugins"].as_array().into_iter().flatten() {
        let name = plugin["name"].as_str().unwrap_or("");
        let contract = plugin["contract"].as_str().unwrap_or("");
        let min = plugin["contract_version_range"]["min"]
            .as_str()
            .unwrap_or("");
        let max = plugin["contract_version_range"]["max_exclusive"]
            .as_str()
            .unwrap_or("");
        let source = plugin["source"].as_str().unwrap_or("");
        let caps = serde_json::to_string(&plugin["capabilities"])?;
        let _ = writeln!(
            out,
            "| `{}` | `{}` | `[{min}, {max})` | `{}` | `{}` |",
            escape_cell(name),
            escape_cell(contract),
            escape_cell(source),
            escape_cell(&caps)
        );
    }
    files.push(generated_file("plugins.md", out));
    Ok(())
}

fn emit_mcp_tools(files: &mut Vec<GeneratedFile>) {
    let mut out = generated_doc("MCP Tools");
    out.push_str("Generated from `cairn_mcp::generated::TOOLS`.\n\n");
    out.push_str("| Tool | Auth | Root Capability | Overrides | Description |\n");
    out.push_str("|---|---|---|---|---|\n");
    for tool in cairn_mcp::generated::TOOLS {
        let capability = tool.capability.unwrap_or("-");
        let mut overrides = Vec::new();
        for ov in tool.auth_overrides {
            overrides.push(format!("auth `{}` -> `{}`", ov.path, ov.auth));
        }
        for ov in tool.capability_overrides {
            overrides.push(format!("cap `{}` -> `{}`", ov.path, ov.capability));
        }
        let overrides = if overrides.is_empty() {
            "-".to_owned()
        } else {
            overrides.join("<br>")
        };
        let _ = writeln!(
            out,
            "| `{}` | `{}` | `{}` | {} | {} |",
            escape_cell(tool.name),
            escape_cell(tool.auth),
            escape_cell(capability),
            escape_cell(&overrides),
            escape_cell(&first_nonempty_line(tool.description))
        );
    }
    files.push(generated_file("mcp-tools.md", out));
}

fn emit_packages(
    files: &mut Vec<GeneratedFile>,
    package_names: &[String],
    coverage: &BTreeMap<String, CoverageEntry>,
) {
    let mut out = generated_doc("Workspace Packages");
    out.push_str("Generated from workspace package metadata and `docs-coverage.toml`.\n\n");
    out.push_str("| Package | Audience | Human Page | Generated Reference |\n");
    out.push_str("|---|---|---|---|\n");
    for name in package_names {
        let Some(entry) = coverage.get(name) else {
            continue;
        };
        let page = empty_dash(&entry.page);
        let generated = empty_dash(&entry.generated_reference);
        let _ = writeln!(
            out,
            "| `{}` | `{}` | {} | {} |",
            escape_cell(name),
            escape_cell(&entry.audience),
            escape_cell(&page),
            escape_cell(&generated)
        );
    }
    files.push(generated_file("packages.md", out));
}

fn emit_contract_verbs(
    files: &mut Vec<GeneratedFile>,
    workspace_root: &Path,
) -> Result<(), DocgenError> {
    let schema_root = schema_root(workspace_root);
    let index: serde_json::Value =
        serde_json::from_slice(&std::fs::read(schema_root.join("index.json"))?)?;
    let contract = index["x-cairn-contract"].as_str().unwrap_or("unknown");
    let verb_files = index["x-cairn-files"]["verbs"].as_array().ok_or_else(|| {
        DocgenError::Metadata("index.json missing x-cairn-files.verbs".to_owned())
    })?;

    let mut out = generated_doc("Contract Verbs");
    let _ = writeln!(out, "Generated from `{contract}` IDL schema files.\n");
    out.push_str("| Verb | Auth | Root Capability | CLI Command | Args Schema | Data Schema |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for rel in verb_files {
        let Some(rel) = rel.as_str() else {
            continue;
        };
        let schema: serde_json::Value =
            serde_json::from_slice(&std::fs::read(schema_root.join(rel))?)?;
        let verb = schema["x-cairn-verb-id"].as_str().unwrap_or(rel);
        let auth = schema["x-cairn-auth"].as_str().unwrap_or("-");
        let capability = schema["x-cairn-capability"].as_str().unwrap_or("-");
        let cli = schema["x-cairn-cli"]["command"].as_str().unwrap_or("-");
        let defs = schema["$defs"].as_object();
        let args = defs.is_some_and(|d| d.contains_key("Args"));
        let data = defs.is_some_and(|d| d.contains_key("Data"));
        let _ = writeln!(
            out,
            "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` |",
            escape_cell(verb),
            escape_cell(auth),
            escape_cell(capability),
            escape_cell(cli),
            if args { "$defs.Args" } else { "-" },
            if data { "$defs.Data" } else { "-" }
        );
    }
    files.push(generated_file("contract-verbs.md", out));
    Ok(())
}

fn help_text(cmd: &clap::Command) -> Result<String, DocgenError> {
    let mut cmd = cmd.clone();
    let mut bytes = Vec::new();
    cmd.write_long_help(&mut bytes)?;
    let raw = String::from_utf8_lossy(&bytes);
    let mut cleaned = raw
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    cleaned.push('\n');
    Ok(cleaned)
}

fn command_file_name(parts: &[&str]) -> String {
    let owned: Vec<_> = parts.iter().map(|p| (*p).to_owned()).collect();
    command_file_name_strs(&owned)
}

fn command_file_name_strs(parts: &[String]) -> String {
    format!("{}.md", parts.join("-"))
}

fn generated_doc(title: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    let _ = writeln!(out, "# {title}\n");
    out
}

fn generated_file(path: &str, content: String) -> GeneratedFile {
    GeneratedFile {
        path: Path::new(GENERATED_ROOT).join(path),
        bytes: content.into_bytes(),
    }
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<(), DocgenError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, bytes)?;
    Ok(())
}

fn stale_generated_files(
    workspace_root: &Path,
    expected: &BTreeSet<PathBuf>,
) -> Result<Vec<PathBuf>, DocgenError> {
    let root = workspace_root.join(GENERATED_ROOT);
    if !root.exists() {
        return Ok(Vec::new());
    }
    let mut stale = Vec::new();
    walk_files(&root, &mut |abs| {
        let Ok(rel) = abs.strip_prefix(workspace_root) else {
            return Ok(());
        };
        let rel = rel.to_path_buf();
        if !expected.contains(&rel) {
            stale.push(rel);
        }
        Ok(())
    })?;
    stale.sort();
    stale.dedup();
    Ok(stale)
}

fn walk_files(
    dir: &Path,
    visit: &mut dyn FnMut(&Path) -> Result<(), DocgenError>,
) -> Result<(), DocgenError> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            walk_files(&path, visit)?;
        } else if file_type.is_file() {
            visit(&path)?;
        }
    }
    Ok(())
}

fn workspace_package_names(workspace_root: &Path) -> Result<Vec<String>, DocgenError> {
    let manifest = workspace_root.join("Cargo.toml");
    if !manifest.exists() {
        return Err(DocgenError::Metadata(format!(
            "{} does not exist",
            manifest.display()
        )));
    }
    let output = std::process::Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--manifest-path",
        ])
        .arg(&manifest)
        .output()?;
    if !output.status.success() {
        return Err(DocgenError::Metadata(
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ));
    }
    let value: serde_json::Value = serde_json::from_slice(&output.stdout)?;
    let members: BTreeSet<String> = value["workspace_members"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|v| v.as_str().map(str::to_owned))
        .collect();
    let mut names = Vec::new();
    for package in value["packages"].as_array().into_iter().flatten() {
        let Some(id) = package["id"].as_str() else {
            continue;
        };
        if !members.is_empty() && !members.contains(id) {
            continue;
        }
        if let Some(name) = package["name"].as_str() {
            names.push(name.to_owned());
        }
    }
    Ok(sorted_names(names))
}

fn sorted_names(mut names: Vec<String>) -> Vec<String> {
    names.sort();
    names.dedup();
    names
}

fn load_coverage(
    workspace_root: &Path,
    package_names: &[String],
) -> Result<BTreeMap<String, CoverageEntry>, DocgenError> {
    let path = workspace_root.join("docs/site/docs-coverage.toml");
    let raw = std::fs::read_to_string(&path)?;
    let value: toml::Value = toml::from_str(&raw)
        .map_err(|e| DocgenError::InvalidCoverage(format!("{}: {e}", path.display())))?;
    let packages = value
        .get("packages")
        .and_then(toml::Value::as_table)
        .ok_or_else(|| {
            DocgenError::InvalidCoverage(format!(
                "{} missing [packages.<name>] tables",
                path.display()
            ))
        })?;

    let mut entries = BTreeMap::new();
    for (name, value) in packages {
        let Some(table) = value.as_table() else {
            return Err(DocgenError::InvalidCoverage(format!(
                "packages.{name} must be a table"
            )));
        };
        entries.insert(
            name.clone(),
            CoverageEntry {
                audience: toml_string(table, "audience"),
                page: toml_string(table, "page"),
                generated_reference: toml_string(table, "generated_reference"),
            },
        );
    }

    let missing: Vec<String> = package_names
        .iter()
        .filter(|name| !entries.contains_key(*name))
        .cloned()
        .collect();
    if !missing.is_empty() {
        return Err(DocgenError::MissingPackageCoverage(missing.join(", ")));
    }

    Ok(entries)
}

fn toml_string(table: &toml::map::Map<String, toml::Value>, key: &str) -> String {
    table
        .get(key)
        .and_then(toml::Value::as_str)
        .unwrap_or("")
        .to_owned()
}

fn schema_root(workspace_root: &Path) -> PathBuf {
    let from_workspace = workspace_root.join("crates/cairn-idl/schema");
    if from_workspace.exists() {
        return from_workspace;
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("cairn-cli crate has a crates/ parent")
        .join("cairn-idl/schema")
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

fn first_nonempty_line(value: &str) -> String {
    value
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .unwrap_or("")
        .to_owned()
}

fn empty_dash(value: &str) -> String {
    if value.is_empty() {
        "-".to_owned()
    } else {
        format!("`{value}`")
    }
}
