#![allow(missing_docs)]

use cairn_idl::codegen::emit_sdk;
use cairn_idl::codegen::{ir, loader};

fn doc() -> ir::Document {
    let raw = loader::load(std::path::Path::new(cairn_idl::SCHEMA_DIR)).unwrap();
    ir::build(&raw).unwrap()
}

#[test]
fn emits_one_file_per_verb_plus_registry_plus_common_plus_errors() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let names: Vec<String> = files
        .iter()
        .map(|f| f.path.to_string_lossy().to_string())
        .collect();

    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/ingest.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/forget.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/common/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/errors/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/status.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/handshake.rs"))
    );
}

#[test]
fn verb_registry_contains_eight_verb_ids() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let mod_rs = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/mod.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&mod_rs.bytes).unwrap();
    for verb in [
        "Ingest",
        "Search",
        "Retrieve",
        "Summarize",
        "AssembleHot",
        "CaptureTrace",
        "Lint",
        "Forget",
    ] {
        assert!(body.contains(verb), "verbs/mod.rs missing variant {verb}");
    }
    // Status / handshake are NOT in the eight-verb count.
    assert!(
        !body.contains("VerbId::Status"),
        "status must not appear in VerbId"
    );
    assert!(!body.contains("VerbId::Handshake"));
}

#[test]
fn every_generated_file_carries_generated_header() {
    let files = emit_sdk::emit(&doc()).unwrap();
    for f in &files {
        let body = std::str::from_utf8(&f.bytes).unwrap();
        assert!(
            body.starts_with("// @generated by cairn-codegen"),
            "{} missing @generated header",
            f.path.display()
        );
    }
}

#[test]
fn search_mode_enum_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let search = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/search.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&search.bytes).unwrap();
    // The mode enum carries per-variant capabilities (search.semantic etc).
    assert!(
        body.contains("impl SearchArgsMode {"),
        "SearchArgsMode missing capability() impl block"
    );
    assert!(
        body.contains("Self::Semantic => Some(\"cairn.mcp.v1.search.semantic\")"),
        "SearchArgsMode::Semantic must expose its capability"
    );
    assert!(
        body.contains("Self::Keyword => Some(\"cairn.mcp.v1.search.keyword\")"),
        "SearchArgsMode::Keyword must expose its capability"
    );
    assert!(
        body.contains("Self::Hybrid => Some(\"cairn.mcp.v1.search.hybrid\")"),
        "SearchArgsMode::Hybrid must expose its capability"
    );
}

#[test]
fn retrieve_args_tagged_union_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let retrieve = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/retrieve.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&retrieve.bytes).unwrap();
    assert!(
        body.contains("impl RetrieveArgs {"),
        "RetrieveArgs missing capability() impl block"
    );
    assert!(
        body.contains("Self::Record { .. } => Some(\"cairn.mcp.v1.retrieve.record\")"),
        "RetrieveArgs::Record must expose its capability"
    );
    assert!(
        body.contains("Self::Profile { .. } => Some(\"cairn.mcp.v1.retrieve.profile\")"),
        "RetrieveArgs::Profile must expose its capability"
    );
}

#[test]
fn forget_args_tagged_union_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let forget = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/forget.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&forget.bytes).unwrap();
    assert!(
        body.contains("impl ForgetArgs {"),
        "ForgetArgs missing capability() impl block"
    );
    assert!(
        body.contains("Self::Record { .. } => Some(\"cairn.mcp.v1.forget.record\")"),
        "ForgetArgs::Record must expose its capability"
    );
}

#[test]
fn error_code_enum_omits_rename_all_so_pascal_wire_round_trips() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let errors = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/errors/mod.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&errors.bytes).unwrap();
    // The IDL error codes are PascalCase wire constants — `rename_all =
    // "snake_case"` would invert them and break the wire contract.
    assert!(
        !body.contains("#[serde(rename_all = \"snake_case\")]"),
        "ErrorCode must not declare rename_all (PascalCase wire is the contract)"
    );
}
