#![allow(missing_docs)]

use cairn_idl::codegen::emit_sdk;
use cairn_idl::codegen::{ir, loader};

fn doc() -> ir::Document {
    let raw = loader::load(std::path::Path::new(cairn_idl::SCHEMA_DIR)).unwrap();
    ir::build(&raw).unwrap()
}

#[test]
fn emits_one_file_per_verb_plus_registry_plus_common_plus_errors() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let names: Vec<String> = files
        .iter()
        .map(|f| f.path.to_string_lossy().to_string())
        .collect();

    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/ingest.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/verbs/forget.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/common/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/errors/mod.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/status.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/handshake.rs"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/schemas/verbs/ingest.json"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/schemas/prelude/status.json"))
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("crates/cairn-core/src/generated/schemas/errors/error.json"))
    );
}

#[test]
fn verb_registry_contains_eight_verb_ids() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let mod_rs = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/mod.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&mod_rs.bytes).unwrap();
    for verb in [
        "Ingest",
        "Search",
        "Retrieve",
        "Summarize",
        "AssembleHot",
        "CaptureTrace",
        "Lint",
        "Forget",
    ] {
        assert!(body.contains(verb), "verbs/mod.rs missing variant {verb}");
    }
    // Status / handshake are NOT in the eight-verb count.
    assert!(
        !body.contains("VerbId::Status"),
        "status must not appear in VerbId"
    );
    assert!(!body.contains("VerbId::Handshake"));
}

#[test]
fn every_generated_file_carries_generated_header() {
    let files = emit_sdk::emit(&doc()).unwrap();
    for f in &files {
        if f.path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }
        let body = std::str::from_utf8(&f.bytes).unwrap();
        assert!(
            body.starts_with("// @generated by cairn-codegen"),
            "{} missing @generated header",
            f.path.display()
        );
    }
}

#[test]
fn search_mode_enum_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let search = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/search.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&search.bytes).unwrap();
    // The mode enum carries per-variant capabilities (search.semantic etc).
    assert!(
        body.contains("impl SearchArgsMode {"),
        "SearchArgsMode missing capability() impl block"
    );
    assert!(
        body.contains("Self::Semantic => Some(\"cairn.mcp.v1.search.semantic\")"),
        "SearchArgsMode::Semantic must expose its capability"
    );
    assert!(
        body.contains("Self::Keyword => Some(\"cairn.mcp.v1.search.keyword\")"),
        "SearchArgsMode::Keyword must expose its capability"
    );
    assert!(
        body.contains("Self::Hybrid => Some(\"cairn.mcp.v1.search.hybrid\")"),
        "SearchArgsMode::Hybrid must expose its capability"
    );
}

#[test]
fn ingest_args_generated_validation_rejects_empty_recording() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let ingest = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/ingest.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&ingest.bytes).unwrap();
    assert!(
        body.contains("if let Some(v) = &raw.recording {"),
        "IngestArgs deserialization must validate recording minLength"
    );
    assert!(
        body.contains("return Err(\"recording: must not be empty\");"),
        "IngestArgs deserialization must reject empty recording values"
    );
}

#[test]
fn retrieve_args_tagged_union_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let retrieve = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/retrieve.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&retrieve.bytes).unwrap();
    assert!(
        body.contains("impl RetrieveArgs {"),
        "RetrieveArgs missing capability() impl block"
    );
    assert!(
        body.contains("Self::Record { .. } => Some(\"cairn.mcp.v1.retrieve.record\")"),
        "RetrieveArgs::Record must expose its capability"
    );
    assert!(
        body.contains("Self::Profile { .. } => Some(\"cairn.mcp.v1.retrieve.profile\")"),
        "RetrieveArgs::Profile must expose its capability"
    );
    assert!(
        body.contains("Self::ToolCall { .. } => Some(\"cairn.mcp.v1.retrieve.tool_call\")"),
        "RetrieveArgs::ToolCall must expose its capability"
    );
    let envelope = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/envelope/mod.rs")
        })
        .unwrap();
    let envelope_body = std::str::from_utf8(&envelope.bytes).unwrap();
    assert!(
        envelope_body.contains("ToolCall(crate::generated::verbs::retrieve::DataToolCall)"),
        "RetrieveData must expose DataToolCall"
    );
    assert!(
        envelope_body.contains("ResponseTarget::ToolCall => RetrieveData::ToolCall("),
        "Response envelope must dispatch target=tool_call to DataToolCall"
    );
}

#[test]
fn forget_args_tagged_union_exposes_per_variant_capability() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let forget = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/verbs/forget.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&forget.bytes).unwrap();
    assert!(
        body.contains("impl ForgetArgs {"),
        "ForgetArgs missing capability() impl block"
    );
    assert!(
        body.contains("Self::Record { .. } => Some(\"cairn.mcp.v1.forget.record\")"),
        "ForgetArgs::Record must expose its capability"
    );
}

#[test]
fn error_code_enum_omits_rename_all_so_pascal_wire_round_trips() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let errors = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/errors/mod.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&errors.bytes).unwrap();
    // The IDL error codes are PascalCase wire constants — `rename_all =
    // "snake_case"` would invert them and break the wire contract.
    assert!(
        !body.contains("#[serde(rename_all = \"snake_case\")]"),
        "ErrorCode must not declare rename_all (PascalCase wire is the contract)"
    );
}

#[test]
fn status_response_includes_split_health_types() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let status = files
        .iter()
        .find(|f| {
            f.path
                .ends_with("crates/cairn-core/src/generated/status.rs")
        })
        .unwrap();
    let body = std::str::from_utf8(&status.bytes).unwrap();
    assert!(body.contains("pub struct StatusResponseHealth"));
    assert!(body.contains("pub struct StatusResponseHealthAuthorityDb"));
    assert!(body.contains("pub struct StatusResponseHealthNexusProjection"));
    assert!(body.contains("pub health: StatusResponseHealth"));
}

#[test]
fn search_sdk_includes_bm25s_ranking_preference_and_signals() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let search = files
        .iter()
        .find(|file| {
            file.path
                .ends_with("crates/cairn-core/src/generated/verbs/search.rs")
        })
        .expect("search SDK output");
    let body = std::str::from_utf8(&search.bytes).expect("utf-8 search SDK");

    assert!(body.contains("pub struct SearchArgsRanking"), "{body}");
    assert!(body.contains("pub enum SearchArgsRankingBm25s"), "{body}");
    assert!(
        body.contains("pub ranking_signals: Vec<HitRankingSignals>"),
        "{body}"
    );
    assert!(body.contains("pub enum HitRankingSignalsName"), "{body}");
}

#[test]
fn lint_sdk_includes_projection_findings() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let lint = files
        .iter()
        .find(|file| {
            file.path
                .ends_with("crates/cairn-core/src/generated/verbs/lint.rs")
        })
        .expect("lint SDK output");
    let body = std::str::from_utf8(&lint.bytes).expect("utf-8 lint SDK");

    assert!(body.contains("ProjectionStale"), "{body}");
    assert!(body.contains("ProjectionMissing"), "{body}");
    assert!(body.contains("ProjectionFailed"), "{body}");
    assert!(body.contains("projection_stale"), "{body}");
}

#[test]
fn status_sdk_includes_projection_detail() {
    let files = emit_sdk::emit(&doc()).unwrap();
    let status = files
        .iter()
        .find(|file| {
            file.path
                .ends_with("crates/cairn-core/src/generated/status.rs")
        })
        .expect("status SDK output");
    let body = std::str::from_utf8(&status.bytes).expect("utf-8 status SDK");

    assert!(body.contains("pub projection_detail"), "{body}");
    assert!(
        body.contains("pub struct StatusResponseHealthNexusProjectionProjectionDetail"),
        "{body}"
    );
    assert!(body.contains("Bm25s"), "{body}");
}
