//! Integration: the bundled plugin.toml parses through the manifest
//! parser and matches the host contract version + name.

// Integration test files are not public API; doc-comments are not required.
#![allow(missing_docs)]

use cairn_core::contract::manifest::{ContractKind, PluginManifest};
use cairn_core::contract::memory_store::CONTRACT_VERSION;
use cairn_core::contract::registry::PluginName;

#[test]
fn manifest_parses_and_matches_host() {
    let manifest =
        PluginManifest::parse_toml(cairn_store_sqlite::MANIFEST_TOML).expect("manifest parses");
    assert_eq!(manifest.name().as_str(), "cairn-store-sqlite");
    assert_eq!(manifest.contract(), ContractKind::MemoryStore);
    let expected = PluginName::new("cairn-store-sqlite").expect("valid");
    manifest
        .verify_compatible_with(&expected, ContractKind::MemoryStore, CONTRACT_VERSION)
        .expect("manifest matches host");
}

// TODO #46 Task 3: restore once register_plugin! is re-enabled.
// The register() fn is generated by register_plugin! which is commented out
// while cairn-core's MemoryStore trait surface is being extended.
//
// #[test]
// fn register_populates_registry() {
//     let mut reg = cairn_core::contract::registry::PluginRegistry::new();
//     cairn_store_sqlite::register(&mut reg).expect("registers");
//     let name = PluginName::new("cairn-store-sqlite").expect("valid");
//     assert!(reg.memory_store(&name).is_some());
//     assert!(reg.parsed_manifest(&name).is_some());
// }
